// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: core/v1/change_authorization.proto

package corev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/formalco/go-sdk/v3/core/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ChangeAuthorizationServiceName is the fully-qualified name of the ChangeAuthorizationService
	// service.
	ChangeAuthorizationServiceName = "core.v1.ChangeAuthorizationService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ChangeAuthorizationServiceCreateSigningKeyProcedure is the fully-qualified name of the
	// ChangeAuthorizationService's CreateSigningKey RPC.
	ChangeAuthorizationServiceCreateSigningKeyProcedure = "/core.v1.ChangeAuthorizationService/CreateSigningKey"
	// ChangeAuthorizationServiceListSigningKeysProcedure is the fully-qualified name of the
	// ChangeAuthorizationService's ListSigningKeys RPC.
	ChangeAuthorizationServiceListSigningKeysProcedure = "/core.v1.ChangeAuthorizationService/ListSigningKeys"
	// ChangeAuthorizationServiceUpdateSigningKeyProcedure is the fully-qualified name of the
	// ChangeAuthorizationService's UpdateSigningKey RPC.
	ChangeAuthorizationServiceUpdateSigningKeyProcedure = "/core.v1.ChangeAuthorizationService/UpdateSigningKey"
	// ChangeAuthorizationServiceUpdateSigningKeyV2Procedure is the fully-qualified name of the
	// ChangeAuthorizationService's UpdateSigningKeyV2 RPC.
	ChangeAuthorizationServiceUpdateSigningKeyV2Procedure = "/core.v1.ChangeAuthorizationService/UpdateSigningKeyV2"
	// ChangeAuthorizationServiceDeleteSigningKeyProcedure is the fully-qualified name of the
	// ChangeAuthorizationService's DeleteSigningKey RPC.
	ChangeAuthorizationServiceDeleteSigningKeyProcedure = "/core.v1.ChangeAuthorizationService/DeleteSigningKey"
)

// ChangeAuthorizationServiceClient is a client for the core.v1.ChangeAuthorizationService service.
type ChangeAuthorizationServiceClient interface {
	// Create a signing key
	//
	// Register a public key for cryptographic change authorization
	CreateSigningKey(context.Context, *connect.Request[v1.CreateSigningKeyRequest]) (*connect.Response[v1.CreateSigningKeyResponse], error)
	// List signing keys
	//
	// List all change authorization signing keys for the organization
	ListSigningKeys(context.Context, *connect.Request[v1.ListSigningKeysRequest]) (*connect.Response[v1.ListSigningKeysResponse], error)
	// Update a signing key
	//
	// Update a change authorization signing key status for key rotation
	UpdateSigningKey(context.Context, *connect.Request[v1.UpdateSigningKeyRequest]) (*connect.Response[v1.UpdateSigningKeyResponse], error)
	// Update signing key (full object replacement)
	//
	// Update a signing key by sending the full object. All mutable fields are replaced.
	UpdateSigningKeyV2(context.Context, *connect.Request[v1.UpdateSigningKeyV2Request]) (*connect.Response[v1.UpdateSigningKeyV2Response], error)
	// Delete a signing key
	//
	// Delete a change authorization signing key
	DeleteSigningKey(context.Context, *connect.Request[v1.DeleteSigningKeyRequest]) (*connect.Response[v1.DeleteSigningKeyResponse], error)
}

// NewChangeAuthorizationServiceClient constructs a client for the
// core.v1.ChangeAuthorizationService service. By default, it uses the Connect protocol with the
// binary Protobuf Codec, asks for gzipped responses, and sends uncompressed requests. To use the
// gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewChangeAuthorizationServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ChangeAuthorizationServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	changeAuthorizationServiceMethods := v1.File_core_v1_change_authorization_proto.Services().ByName("ChangeAuthorizationService").Methods()
	return &changeAuthorizationServiceClient{
		createSigningKey: connect.NewClient[v1.CreateSigningKeyRequest, v1.CreateSigningKeyResponse](
			httpClient,
			baseURL+ChangeAuthorizationServiceCreateSigningKeyProcedure,
			connect.WithSchema(changeAuthorizationServiceMethods.ByName("CreateSigningKey")),
			connect.WithClientOptions(opts...),
		),
		listSigningKeys: connect.NewClient[v1.ListSigningKeysRequest, v1.ListSigningKeysResponse](
			httpClient,
			baseURL+ChangeAuthorizationServiceListSigningKeysProcedure,
			connect.WithSchema(changeAuthorizationServiceMethods.ByName("ListSigningKeys")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		updateSigningKey: connect.NewClient[v1.UpdateSigningKeyRequest, v1.UpdateSigningKeyResponse](
			httpClient,
			baseURL+ChangeAuthorizationServiceUpdateSigningKeyProcedure,
			connect.WithSchema(changeAuthorizationServiceMethods.ByName("UpdateSigningKey")),
			connect.WithClientOptions(opts...),
		),
		updateSigningKeyV2: connect.NewClient[v1.UpdateSigningKeyV2Request, v1.UpdateSigningKeyV2Response](
			httpClient,
			baseURL+ChangeAuthorizationServiceUpdateSigningKeyV2Procedure,
			connect.WithSchema(changeAuthorizationServiceMethods.ByName("UpdateSigningKeyV2")),
			connect.WithClientOptions(opts...),
		),
		deleteSigningKey: connect.NewClient[v1.DeleteSigningKeyRequest, v1.DeleteSigningKeyResponse](
			httpClient,
			baseURL+ChangeAuthorizationServiceDeleteSigningKeyProcedure,
			connect.WithSchema(changeAuthorizationServiceMethods.ByName("DeleteSigningKey")),
			connect.WithClientOptions(opts...),
		),
	}
}

// changeAuthorizationServiceClient implements ChangeAuthorizationServiceClient.
type changeAuthorizationServiceClient struct {
	createSigningKey   *connect.Client[v1.CreateSigningKeyRequest, v1.CreateSigningKeyResponse]
	listSigningKeys    *connect.Client[v1.ListSigningKeysRequest, v1.ListSigningKeysResponse]
	updateSigningKey   *connect.Client[v1.UpdateSigningKeyRequest, v1.UpdateSigningKeyResponse]
	updateSigningKeyV2 *connect.Client[v1.UpdateSigningKeyV2Request, v1.UpdateSigningKeyV2Response]
	deleteSigningKey   *connect.Client[v1.DeleteSigningKeyRequest, v1.DeleteSigningKeyResponse]
}

// CreateSigningKey calls core.v1.ChangeAuthorizationService.CreateSigningKey.
func (c *changeAuthorizationServiceClient) CreateSigningKey(ctx context.Context, req *connect.Request[v1.CreateSigningKeyRequest]) (*connect.Response[v1.CreateSigningKeyResponse], error) {
	return c.createSigningKey.CallUnary(ctx, req)
}

// ListSigningKeys calls core.v1.ChangeAuthorizationService.ListSigningKeys.
func (c *changeAuthorizationServiceClient) ListSigningKeys(ctx context.Context, req *connect.Request[v1.ListSigningKeysRequest]) (*connect.Response[v1.ListSigningKeysResponse], error) {
	return c.listSigningKeys.CallUnary(ctx, req)
}

// UpdateSigningKey calls core.v1.ChangeAuthorizationService.UpdateSigningKey.
func (c *changeAuthorizationServiceClient) UpdateSigningKey(ctx context.Context, req *connect.Request[v1.UpdateSigningKeyRequest]) (*connect.Response[v1.UpdateSigningKeyResponse], error) {
	return c.updateSigningKey.CallUnary(ctx, req)
}

// UpdateSigningKeyV2 calls core.v1.ChangeAuthorizationService.UpdateSigningKeyV2.
func (c *changeAuthorizationServiceClient) UpdateSigningKeyV2(ctx context.Context, req *connect.Request[v1.UpdateSigningKeyV2Request]) (*connect.Response[v1.UpdateSigningKeyV2Response], error) {
	return c.updateSigningKeyV2.CallUnary(ctx, req)
}

// DeleteSigningKey calls core.v1.ChangeAuthorizationService.DeleteSigningKey.
func (c *changeAuthorizationServiceClient) DeleteSigningKey(ctx context.Context, req *connect.Request[v1.DeleteSigningKeyRequest]) (*connect.Response[v1.DeleteSigningKeyResponse], error) {
	return c.deleteSigningKey.CallUnary(ctx, req)
}

// ChangeAuthorizationServiceHandler is an implementation of the core.v1.ChangeAuthorizationService
// service.
type ChangeAuthorizationServiceHandler interface {
	// Create a signing key
	//
	// Register a public key for cryptographic change authorization
	CreateSigningKey(context.Context, *connect.Request[v1.CreateSigningKeyRequest]) (*connect.Response[v1.CreateSigningKeyResponse], error)
	// List signing keys
	//
	// List all change authorization signing keys for the organization
	ListSigningKeys(context.Context, *connect.Request[v1.ListSigningKeysRequest]) (*connect.Response[v1.ListSigningKeysResponse], error)
	// Update a signing key
	//
	// Update a change authorization signing key status for key rotation
	UpdateSigningKey(context.Context, *connect.Request[v1.UpdateSigningKeyRequest]) (*connect.Response[v1.UpdateSigningKeyResponse], error)
	// Update signing key (full object replacement)
	//
	// Update a signing key by sending the full object. All mutable fields are replaced.
	UpdateSigningKeyV2(context.Context, *connect.Request[v1.UpdateSigningKeyV2Request]) (*connect.Response[v1.UpdateSigningKeyV2Response], error)
	// Delete a signing key
	//
	// Delete a change authorization signing key
	DeleteSigningKey(context.Context, *connect.Request[v1.DeleteSigningKeyRequest]) (*connect.Response[v1.DeleteSigningKeyResponse], error)
}

// NewChangeAuthorizationServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewChangeAuthorizationServiceHandler(svc ChangeAuthorizationServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	changeAuthorizationServiceMethods := v1.File_core_v1_change_authorization_proto.Services().ByName("ChangeAuthorizationService").Methods()
	changeAuthorizationServiceCreateSigningKeyHandler := connect.NewUnaryHandler(
		ChangeAuthorizationServiceCreateSigningKeyProcedure,
		svc.CreateSigningKey,
		connect.WithSchema(changeAuthorizationServiceMethods.ByName("CreateSigningKey")),
		connect.WithHandlerOptions(opts...),
	)
	changeAuthorizationServiceListSigningKeysHandler := connect.NewUnaryHandler(
		ChangeAuthorizationServiceListSigningKeysProcedure,
		svc.ListSigningKeys,
		connect.WithSchema(changeAuthorizationServiceMethods.ByName("ListSigningKeys")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	changeAuthorizationServiceUpdateSigningKeyHandler := connect.NewUnaryHandler(
		ChangeAuthorizationServiceUpdateSigningKeyProcedure,
		svc.UpdateSigningKey,
		connect.WithSchema(changeAuthorizationServiceMethods.ByName("UpdateSigningKey")),
		connect.WithHandlerOptions(opts...),
	)
	changeAuthorizationServiceUpdateSigningKeyV2Handler := connect.NewUnaryHandler(
		ChangeAuthorizationServiceUpdateSigningKeyV2Procedure,
		svc.UpdateSigningKeyV2,
		connect.WithSchema(changeAuthorizationServiceMethods.ByName("UpdateSigningKeyV2")),
		connect.WithHandlerOptions(opts...),
	)
	changeAuthorizationServiceDeleteSigningKeyHandler := connect.NewUnaryHandler(
		ChangeAuthorizationServiceDeleteSigningKeyProcedure,
		svc.DeleteSigningKey,
		connect.WithSchema(changeAuthorizationServiceMethods.ByName("DeleteSigningKey")),
		connect.WithHandlerOptions(opts...),
	)
	return "/core.v1.ChangeAuthorizationService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ChangeAuthorizationServiceCreateSigningKeyProcedure:
			changeAuthorizationServiceCreateSigningKeyHandler.ServeHTTP(w, r)
		case ChangeAuthorizationServiceListSigningKeysProcedure:
			changeAuthorizationServiceListSigningKeysHandler.ServeHTTP(w, r)
		case ChangeAuthorizationServiceUpdateSigningKeyProcedure:
			changeAuthorizationServiceUpdateSigningKeyHandler.ServeHTTP(w, r)
		case ChangeAuthorizationServiceUpdateSigningKeyV2Procedure:
			changeAuthorizationServiceUpdateSigningKeyV2Handler.ServeHTTP(w, r)
		case ChangeAuthorizationServiceDeleteSigningKeyProcedure:
			changeAuthorizationServiceDeleteSigningKeyHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedChangeAuthorizationServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedChangeAuthorizationServiceHandler struct{}

func (UnimplementedChangeAuthorizationServiceHandler) CreateSigningKey(context.Context, *connect.Request[v1.CreateSigningKeyRequest]) (*connect.Response[v1.CreateSigningKeyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("core.v1.ChangeAuthorizationService.CreateSigningKey is not implemented"))
}

func (UnimplementedChangeAuthorizationServiceHandler) ListSigningKeys(context.Context, *connect.Request[v1.ListSigningKeysRequest]) (*connect.Response[v1.ListSigningKeysResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("core.v1.ChangeAuthorizationService.ListSigningKeys is not implemented"))
}

func (UnimplementedChangeAuthorizationServiceHandler) UpdateSigningKey(context.Context, *connect.Request[v1.UpdateSigningKeyRequest]) (*connect.Response[v1.UpdateSigningKeyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("core.v1.ChangeAuthorizationService.UpdateSigningKey is not implemented"))
}

func (UnimplementedChangeAuthorizationServiceHandler) UpdateSigningKeyV2(context.Context, *connect.Request[v1.UpdateSigningKeyV2Request]) (*connect.Response[v1.UpdateSigningKeyV2Response], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("core.v1.ChangeAuthorizationService.UpdateSigningKeyV2 is not implemented"))
}

func (UnimplementedChangeAuthorizationServiceHandler) DeleteSigningKey(context.Context, *connect.Request[v1.DeleteSigningKeyRequest]) (*connect.Response[v1.DeleteSigningKeyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("core.v1.ChangeAuthorizationService.DeleteSigningKey is not implemented"))
}
