// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: core/v1/mcp.proto

package corev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/formalco/go-sdk/v3/core/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// McpServiceName is the fully-qualified name of the McpService service.
	McpServiceName = "core.v1.McpService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// McpServiceListMcpServersProcedure is the fully-qualified name of the McpService's ListMcpServers
	// RPC.
	McpServiceListMcpServersProcedure = "/core.v1.McpService/ListMcpServers"
	// McpServiceGetMcpServerProcedure is the fully-qualified name of the McpService's GetMcpServer RPC.
	McpServiceGetMcpServerProcedure = "/core.v1.McpService/GetMcpServer"
	// McpServiceCreateMcpServerProcedure is the fully-qualified name of the McpService's
	// CreateMcpServer RPC.
	McpServiceCreateMcpServerProcedure = "/core.v1.McpService/CreateMcpServer"
	// McpServiceUpdateMcpServerProcedure is the fully-qualified name of the McpService's
	// UpdateMcpServer RPC.
	McpServiceUpdateMcpServerProcedure = "/core.v1.McpService/UpdateMcpServer"
	// McpServiceDeleteMcpServerProcedure is the fully-qualified name of the McpService's
	// DeleteMcpServer RPC.
	McpServiceDeleteMcpServerProcedure = "/core.v1.McpService/DeleteMcpServer"
	// McpServiceListShadowMcpsProcedure is the fully-qualified name of the McpService's ListShadowMcps
	// RPC.
	McpServiceListShadowMcpsProcedure = "/core.v1.McpService/ListShadowMcps"
)

// McpServiceClient is a client for the core.v1.McpService service.
type McpServiceClient interface {
	// List MCP servers
	//
	// List managed MCP servers for the organization.
	ListMcpServers(context.Context, *connect.Request[v1.ListMcpServersRequest]) (*connect.Response[v1.ListMcpServersResponse], error)
	// Get MCP server
	//
	// Get a managed MCP server by ID.
	GetMcpServer(context.Context, *connect.Request[v1.GetMcpServerRequest]) (*connect.Response[v1.GetMcpServerResponse], error)
	// Create MCP server
	//
	// Create a managed MCP server.
	CreateMcpServer(context.Context, *connect.Request[v1.CreateMcpServerRequest]) (*connect.Response[v1.CreateMcpServerResponse], error)
	// Update MCP server
	//
	// Update a managed MCP server.
	UpdateMcpServer(context.Context, *connect.Request[v1.UpdateMcpServerRequest]) (*connect.Response[v1.UpdateMcpServerResponse], error)
	// Delete MCP server
	//
	// Delete a managed MCP server.
	DeleteMcpServer(context.Context, *connect.Request[v1.DeleteMcpServerRequest]) (*connect.Response[v1.DeleteMcpServerResponse], error)
	// List shadow MCP servers
	//
	// List observed MCP servers that are not yet managed.
	ListShadowMcps(context.Context, *connect.Request[v1.ListShadowMcpsRequest]) (*connect.Response[v1.ListShadowMcpsResponse], error)
}

// NewMcpServiceClient constructs a client for the core.v1.McpService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewMcpServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) McpServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	mcpServiceMethods := v1.File_core_v1_mcp_proto.Services().ByName("McpService").Methods()
	return &mcpServiceClient{
		listMcpServers: connect.NewClient[v1.ListMcpServersRequest, v1.ListMcpServersResponse](
			httpClient,
			baseURL+McpServiceListMcpServersProcedure,
			connect.WithSchema(mcpServiceMethods.ByName("ListMcpServers")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		getMcpServer: connect.NewClient[v1.GetMcpServerRequest, v1.GetMcpServerResponse](
			httpClient,
			baseURL+McpServiceGetMcpServerProcedure,
			connect.WithSchema(mcpServiceMethods.ByName("GetMcpServer")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		createMcpServer: connect.NewClient[v1.CreateMcpServerRequest, v1.CreateMcpServerResponse](
			httpClient,
			baseURL+McpServiceCreateMcpServerProcedure,
			connect.WithSchema(mcpServiceMethods.ByName("CreateMcpServer")),
			connect.WithClientOptions(opts...),
		),
		updateMcpServer: connect.NewClient[v1.UpdateMcpServerRequest, v1.UpdateMcpServerResponse](
			httpClient,
			baseURL+McpServiceUpdateMcpServerProcedure,
			connect.WithSchema(mcpServiceMethods.ByName("UpdateMcpServer")),
			connect.WithClientOptions(opts...),
		),
		deleteMcpServer: connect.NewClient[v1.DeleteMcpServerRequest, v1.DeleteMcpServerResponse](
			httpClient,
			baseURL+McpServiceDeleteMcpServerProcedure,
			connect.WithSchema(mcpServiceMethods.ByName("DeleteMcpServer")),
			connect.WithClientOptions(opts...),
		),
		listShadowMcps: connect.NewClient[v1.ListShadowMcpsRequest, v1.ListShadowMcpsResponse](
			httpClient,
			baseURL+McpServiceListShadowMcpsProcedure,
			connect.WithSchema(mcpServiceMethods.ByName("ListShadowMcps")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
	}
}

// mcpServiceClient implements McpServiceClient.
type mcpServiceClient struct {
	listMcpServers  *connect.Client[v1.ListMcpServersRequest, v1.ListMcpServersResponse]
	getMcpServer    *connect.Client[v1.GetMcpServerRequest, v1.GetMcpServerResponse]
	createMcpServer *connect.Client[v1.CreateMcpServerRequest, v1.CreateMcpServerResponse]
	updateMcpServer *connect.Client[v1.UpdateMcpServerRequest, v1.UpdateMcpServerResponse]
	deleteMcpServer *connect.Client[v1.DeleteMcpServerRequest, v1.DeleteMcpServerResponse]
	listShadowMcps  *connect.Client[v1.ListShadowMcpsRequest, v1.ListShadowMcpsResponse]
}

// ListMcpServers calls core.v1.McpService.ListMcpServers.
func (c *mcpServiceClient) ListMcpServers(ctx context.Context, req *connect.Request[v1.ListMcpServersRequest]) (*connect.Response[v1.ListMcpServersResponse], error) {
	return c.listMcpServers.CallUnary(ctx, req)
}

// GetMcpServer calls core.v1.McpService.GetMcpServer.
func (c *mcpServiceClient) GetMcpServer(ctx context.Context, req *connect.Request[v1.GetMcpServerRequest]) (*connect.Response[v1.GetMcpServerResponse], error) {
	return c.getMcpServer.CallUnary(ctx, req)
}

// CreateMcpServer calls core.v1.McpService.CreateMcpServer.
func (c *mcpServiceClient) CreateMcpServer(ctx context.Context, req *connect.Request[v1.CreateMcpServerRequest]) (*connect.Response[v1.CreateMcpServerResponse], error) {
	return c.createMcpServer.CallUnary(ctx, req)
}

// UpdateMcpServer calls core.v1.McpService.UpdateMcpServer.
func (c *mcpServiceClient) UpdateMcpServer(ctx context.Context, req *connect.Request[v1.UpdateMcpServerRequest]) (*connect.Response[v1.UpdateMcpServerResponse], error) {
	return c.updateMcpServer.CallUnary(ctx, req)
}

// DeleteMcpServer calls core.v1.McpService.DeleteMcpServer.
func (c *mcpServiceClient) DeleteMcpServer(ctx context.Context, req *connect.Request[v1.DeleteMcpServerRequest]) (*connect.Response[v1.DeleteMcpServerResponse], error) {
	return c.deleteMcpServer.CallUnary(ctx, req)
}

// ListShadowMcps calls core.v1.McpService.ListShadowMcps.
func (c *mcpServiceClient) ListShadowMcps(ctx context.Context, req *connect.Request[v1.ListShadowMcpsRequest]) (*connect.Response[v1.ListShadowMcpsResponse], error) {
	return c.listShadowMcps.CallUnary(ctx, req)
}

// McpServiceHandler is an implementation of the core.v1.McpService service.
type McpServiceHandler interface {
	// List MCP servers
	//
	// List managed MCP servers for the organization.
	ListMcpServers(context.Context, *connect.Request[v1.ListMcpServersRequest]) (*connect.Response[v1.ListMcpServersResponse], error)
	// Get MCP server
	//
	// Get a managed MCP server by ID.
	GetMcpServer(context.Context, *connect.Request[v1.GetMcpServerRequest]) (*connect.Response[v1.GetMcpServerResponse], error)
	// Create MCP server
	//
	// Create a managed MCP server.
	CreateMcpServer(context.Context, *connect.Request[v1.CreateMcpServerRequest]) (*connect.Response[v1.CreateMcpServerResponse], error)
	// Update MCP server
	//
	// Update a managed MCP server.
	UpdateMcpServer(context.Context, *connect.Request[v1.UpdateMcpServerRequest]) (*connect.Response[v1.UpdateMcpServerResponse], error)
	// Delete MCP server
	//
	// Delete a managed MCP server.
	DeleteMcpServer(context.Context, *connect.Request[v1.DeleteMcpServerRequest]) (*connect.Response[v1.DeleteMcpServerResponse], error)
	// List shadow MCP servers
	//
	// List observed MCP servers that are not yet managed.
	ListShadowMcps(context.Context, *connect.Request[v1.ListShadowMcpsRequest]) (*connect.Response[v1.ListShadowMcpsResponse], error)
}

// NewMcpServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewMcpServiceHandler(svc McpServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	mcpServiceMethods := v1.File_core_v1_mcp_proto.Services().ByName("McpService").Methods()
	mcpServiceListMcpServersHandler := connect.NewUnaryHandler(
		McpServiceListMcpServersProcedure,
		svc.ListMcpServers,
		connect.WithSchema(mcpServiceMethods.ByName("ListMcpServers")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	mcpServiceGetMcpServerHandler := connect.NewUnaryHandler(
		McpServiceGetMcpServerProcedure,
		svc.GetMcpServer,
		connect.WithSchema(mcpServiceMethods.ByName("GetMcpServer")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	mcpServiceCreateMcpServerHandler := connect.NewUnaryHandler(
		McpServiceCreateMcpServerProcedure,
		svc.CreateMcpServer,
		connect.WithSchema(mcpServiceMethods.ByName("CreateMcpServer")),
		connect.WithHandlerOptions(opts...),
	)
	mcpServiceUpdateMcpServerHandler := connect.NewUnaryHandler(
		McpServiceUpdateMcpServerProcedure,
		svc.UpdateMcpServer,
		connect.WithSchema(mcpServiceMethods.ByName("UpdateMcpServer")),
		connect.WithHandlerOptions(opts...),
	)
	mcpServiceDeleteMcpServerHandler := connect.NewUnaryHandler(
		McpServiceDeleteMcpServerProcedure,
		svc.DeleteMcpServer,
		connect.WithSchema(mcpServiceMethods.ByName("DeleteMcpServer")),
		connect.WithHandlerOptions(opts...),
	)
	mcpServiceListShadowMcpsHandler := connect.NewUnaryHandler(
		McpServiceListShadowMcpsProcedure,
		svc.ListShadowMcps,
		connect.WithSchema(mcpServiceMethods.ByName("ListShadowMcps")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	return "/core.v1.McpService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case McpServiceListMcpServersProcedure:
			mcpServiceListMcpServersHandler.ServeHTTP(w, r)
		case McpServiceGetMcpServerProcedure:
			mcpServiceGetMcpServerHandler.ServeHTTP(w, r)
		case McpServiceCreateMcpServerProcedure:
			mcpServiceCreateMcpServerHandler.ServeHTTP(w, r)
		case McpServiceUpdateMcpServerProcedure:
			mcpServiceUpdateMcpServerHandler.ServeHTTP(w, r)
		case McpServiceDeleteMcpServerProcedure:
			mcpServiceDeleteMcpServerHandler.ServeHTTP(w, r)
		case McpServiceListShadowMcpsProcedure:
			mcpServiceListShadowMcpsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedMcpServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedMcpServiceHandler struct{}

func (UnimplementedMcpServiceHandler) ListMcpServers(context.Context, *connect.Request[v1.ListMcpServersRequest]) (*connect.Response[v1.ListMcpServersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("core.v1.McpService.ListMcpServers is not implemented"))
}

func (UnimplementedMcpServiceHandler) GetMcpServer(context.Context, *connect.Request[v1.GetMcpServerRequest]) (*connect.Response[v1.GetMcpServerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("core.v1.McpService.GetMcpServer is not implemented"))
}

func (UnimplementedMcpServiceHandler) CreateMcpServer(context.Context, *connect.Request[v1.CreateMcpServerRequest]) (*connect.Response[v1.CreateMcpServerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("core.v1.McpService.CreateMcpServer is not implemented"))
}

func (UnimplementedMcpServiceHandler) UpdateMcpServer(context.Context, *connect.Request[v1.UpdateMcpServerRequest]) (*connect.Response[v1.UpdateMcpServerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("core.v1.McpService.UpdateMcpServer is not implemented"))
}

func (UnimplementedMcpServiceHandler) DeleteMcpServer(context.Context, *connect.Request[v1.DeleteMcpServerRequest]) (*connect.Response[v1.DeleteMcpServerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("core.v1.McpService.DeleteMcpServer is not implemented"))
}

func (UnimplementedMcpServiceHandler) ListShadowMcps(context.Context, *connect.Request[v1.ListShadowMcpsRequest]) (*connect.Response[v1.ListShadowMcpsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("core.v1.McpService.ListShadowMcps is not implemented"))
}
