// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: core/v1/policies.proto

package corev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/formalco/go-sdk/v3/core/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// PoliciesServiceName is the fully-qualified name of the PoliciesService service.
	PoliciesServiceName = "core.v1.PoliciesService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PoliciesServiceListPoliciesProcedure is the fully-qualified name of the PoliciesService's
	// ListPolicies RPC.
	PoliciesServiceListPoliciesProcedure = "/core.v1.PoliciesService/ListPolicies"
	// PoliciesServiceGetPolicyProcedure is the fully-qualified name of the PoliciesService's GetPolicy
	// RPC.
	PoliciesServiceGetPolicyProcedure = "/core.v1.PoliciesService/GetPolicy"
	// PoliciesServiceGetPolicyCodeValidityProcedure is the fully-qualified name of the
	// PoliciesService's GetPolicyCodeValidity RPC.
	PoliciesServiceGetPolicyCodeValidityProcedure = "/core.v1.PoliciesService/GetPolicyCodeValidity"
	// PoliciesServiceCreatePolicyProcedure is the fully-qualified name of the PoliciesService's
	// CreatePolicy RPC.
	PoliciesServiceCreatePolicyProcedure = "/core.v1.PoliciesService/CreatePolicy"
	// PoliciesServiceUpdatePolicyProcedure is the fully-qualified name of the PoliciesService's
	// UpdatePolicy RPC.
	PoliciesServiceUpdatePolicyProcedure = "/core.v1.PoliciesService/UpdatePolicy"
	// PoliciesServiceUpdatePolicyV2Procedure is the fully-qualified name of the PoliciesService's
	// UpdatePolicyV2 RPC.
	PoliciesServiceUpdatePolicyV2Procedure = "/core.v1.PoliciesService/UpdatePolicyV2"
	// PoliciesServiceDeletePolicyProcedure is the fully-qualified name of the PoliciesService's
	// DeletePolicy RPC.
	PoliciesServiceDeletePolicyProcedure = "/core.v1.PoliciesService/DeletePolicy"
	// PoliciesServiceCreatePolicyReportProcedure is the fully-qualified name of the PoliciesService's
	// CreatePolicyReport RPC.
	PoliciesServiceCreatePolicyReportProcedure = "/core.v1.PoliciesService/CreatePolicyReport"
	// PoliciesServiceGetPolicyReportProcedure is the fully-qualified name of the PoliciesService's
	// GetPolicyReport RPC.
	PoliciesServiceGetPolicyReportProcedure = "/core.v1.PoliciesService/GetPolicyReport"
	// PoliciesServiceGetPolicyImpactReportGraphProcedure is the fully-qualified name of the
	// PoliciesService's GetPolicyImpactReportGraph RPC.
	PoliciesServiceGetPolicyImpactReportGraphProcedure = "/core.v1.PoliciesService/GetPolicyImpactReportGraph"
	// PoliciesServiceListPolicyImpactReportLogsProcedure is the fully-qualified name of the
	// PoliciesService's ListPolicyImpactReportLogs RPC.
	PoliciesServiceListPolicyImpactReportLogsProcedure = "/core.v1.PoliciesService/ListPolicyImpactReportLogs"
	// PoliciesServiceCreatePolicyStageConfigurationProcedure is the fully-qualified name of the
	// PoliciesService's CreatePolicyStageConfiguration RPC.
	PoliciesServiceCreatePolicyStageConfigurationProcedure = "/core.v1.PoliciesService/CreatePolicyStageConfiguration"
	// PoliciesServiceGetPolicyStageConfigurationProcedure is the fully-qualified name of the
	// PoliciesService's GetPolicyStageConfiguration RPC.
	PoliciesServiceGetPolicyStageConfigurationProcedure = "/core.v1.PoliciesService/GetPolicyStageConfiguration"
	// PoliciesServiceListPolicyStageConfigurationsProcedure is the fully-qualified name of the
	// PoliciesService's ListPolicyStageConfigurations RPC.
	PoliciesServiceListPolicyStageConfigurationsProcedure = "/core.v1.PoliciesService/ListPolicyStageConfigurations"
	// PoliciesServiceUpdatePolicyStageConfigurationProcedure is the fully-qualified name of the
	// PoliciesService's UpdatePolicyStageConfiguration RPC.
	PoliciesServiceUpdatePolicyStageConfigurationProcedure = "/core.v1.PoliciesService/UpdatePolicyStageConfiguration"
	// PoliciesServiceUpdatePolicyStageConfigurationV2Procedure is the fully-qualified name of the
	// PoliciesService's UpdatePolicyStageConfigurationV2 RPC.
	PoliciesServiceUpdatePolicyStageConfigurationV2Procedure = "/core.v1.PoliciesService/UpdatePolicyStageConfigurationV2"
	// PoliciesServiceDeletePolicyStageConfigurationProcedure is the fully-qualified name of the
	// PoliciesService's DeletePolicyStageConfiguration RPC.
	PoliciesServiceDeletePolicyStageConfigurationProcedure = "/core.v1.PoliciesService/DeletePolicyStageConfiguration"
	// PoliciesServiceGetPolicyVersionProcedure is the fully-qualified name of the PoliciesService's
	// GetPolicyVersion RPC.
	PoliciesServiceGetPolicyVersionProcedure = "/core.v1.PoliciesService/GetPolicyVersion"
	// PoliciesServiceListPolicyVersionsProcedure is the fully-qualified name of the PoliciesService's
	// ListPolicyVersions RPC.
	PoliciesServiceListPolicyVersionsProcedure = "/core.v1.PoliciesService/ListPolicyVersions"
	// PoliciesServiceCreatePolicySuspensionProcedure is the fully-qualified name of the
	// PoliciesService's CreatePolicySuspension RPC.
	PoliciesServiceCreatePolicySuspensionProcedure = "/core.v1.PoliciesService/CreatePolicySuspension"
	// PoliciesServiceGetPolicySuspensionProcedure is the fully-qualified name of the PoliciesService's
	// GetPolicySuspension RPC.
	PoliciesServiceGetPolicySuspensionProcedure = "/core.v1.PoliciesService/GetPolicySuspension"
	// PoliciesServiceListPolicySuspensionsProcedure is the fully-qualified name of the
	// PoliciesService's ListPolicySuspensions RPC.
	PoliciesServiceListPolicySuspensionsProcedure = "/core.v1.PoliciesService/ListPolicySuspensions"
	// PoliciesServiceDeletePolicySuspensionProcedure is the fully-qualified name of the
	// PoliciesService's DeletePolicySuspension RPC.
	PoliciesServiceDeletePolicySuspensionProcedure = "/core.v1.PoliciesService/DeletePolicySuspension"
	// PoliciesServiceCreateRegoCodeFromNaturalLanguageProcedure is the fully-qualified name of the
	// PoliciesService's CreateRegoCodeFromNaturalLanguage RPC.
	PoliciesServiceCreateRegoCodeFromNaturalLanguageProcedure = "/core.v1.PoliciesService/CreateRegoCodeFromNaturalLanguage"
)

// PoliciesServiceClient is a client for the core.v1.PoliciesService service.
type PoliciesServiceClient interface {
	// List policies
	//
	// List all policies
	ListPolicies(context.Context, *connect.Request[v1.ListPoliciesRequest]) (*connect.Response[v1.ListPoliciesResponse], error)
	// Get policy
	//
	// Get a policy
	GetPolicy(context.Context, *connect.Request[v1.GetPolicyRequest]) (*connect.Response[v1.GetPolicyResponse], error)
	// Get policy code validity
	//
	// Get the validity of a policy code
	GetPolicyCodeValidity(context.Context, *connect.Request[v1.GetPolicyCodeValidityRequest]) (*connect.Response[v1.GetPolicyCodeValidityResponse], error)
	// Create policy
	//
	// Create a policy
	CreatePolicy(context.Context, *connect.Request[v1.CreatePolicyRequest]) (*connect.Response[v1.CreatePolicyResponse], error)
	// Update policy
	//
	// Update a policy
	UpdatePolicy(context.Context, *connect.Request[v1.UpdatePolicyRequest]) (*connect.Response[v1.UpdatePolicyResponse], error)
	// Update policy (full object replacement)
	//
	// Update a policy by sending the full object. All mutable fields are replaced.
	UpdatePolicyV2(context.Context, *connect.Request[v1.UpdatePolicyV2Request]) (*connect.Response[v1.UpdatePolicyV2Response], error)
	// Delete policy
	//
	// Delete a policy
	DeletePolicy(context.Context, *connect.Request[v1.DeletePolicyRequest]) (*connect.Response[v1.DeletePolicyResponse], error)
	// Create policy report
	//
	// Generate a policy report from policy code
	CreatePolicyReport(context.Context, *connect.Request[v1.CreatePolicyReportRequest]) (*connect.Response[v1.CreatePolicyReportResponse], error)
	// Get policy report
	//
	// Get a specific policy report by ID
	GetPolicyReport(context.Context, *connect.Request[v1.GetPolicyReportRequest]) (*connect.Response[v1.GetPolicyReportResponse], error)
	// Get policy report connector graph
	//
	// Get the connector graph for a specific policy report
	GetPolicyImpactReportGraph(context.Context, *connect.Request[v1.GetPolicyImpactReportGraphRequest]) (*connect.Response[v1.GetPolicyImpactReportGraphResponse], error)
	// List policy impact report logs
	//
	// List logs that would have been triggered by the policy in the report
	ListPolicyImpactReportLogs(context.Context, *connect.Request[v1.ListPolicyImpactReportLogsRequest]) (*connect.Response[v1.ListPolicyImpactReportLogsResponse], error)
	// Create policy stage configuration
	//
	// Create a policy stage configuration
	CreatePolicyStageConfiguration(context.Context, *connect.Request[v1.CreatePolicyStageConfigurationRequest]) (*connect.Response[v1.CreatePolicyStageConfigurationResponse], error)
	GetPolicyStageConfiguration(context.Context, *connect.Request[v1.GetPolicyStageConfigurationRequest]) (*connect.Response[v1.GetPolicyStageConfigurationResponse], error)
	ListPolicyStageConfigurations(context.Context, *connect.Request[v1.ListPolicyStageConfigurationsRequest]) (*connect.Response[v1.ListPolicyStageConfigurationsResponse], error)
	// Update policy stage configuration
	//
	// Update a policy stage configuration
	UpdatePolicyStageConfiguration(context.Context, *connect.Request[v1.UpdatePolicyStageConfigurationRequest]) (*connect.Response[v1.UpdatePolicyStageConfigurationResponse], error)
	// Update policy stage configuration (full object replacement)
	//
	// Update a policy stage configuration by sending the full object. All mutable fields are replaced.
	UpdatePolicyStageConfigurationV2(context.Context, *connect.Request[v1.UpdatePolicyStageConfigurationV2Request]) (*connect.Response[v1.UpdatePolicyStageConfigurationV2Response], error)
	// Delete policy stage configuration
	//
	// Delete a policy stage configuration
	DeletePolicyStageConfiguration(context.Context, *connect.Request[v1.DeletePolicyStageConfigurationRequest]) (*connect.Response[v1.DeletePolicyStageConfigurationResponse], error)
	GetPolicyVersion(context.Context, *connect.Request[v1.GetPolicyVersionRequest]) (*connect.Response[v1.GetPolicyVersionResponse], error)
	ListPolicyVersions(context.Context, *connect.Request[v1.ListPolicyVersionsRequest]) (*connect.Response[v1.ListPolicyVersionsResponse], error)
	// Create policy suspension
	//
	// Create a policy suspension for a specific identity
	CreatePolicySuspension(context.Context, *connect.Request[v1.CreatePolicySuspensionRequest]) (*connect.Response[v1.CreatePolicySuspensionResponse], error)
	// Get policy suspension
	//
	// Get a policy suspension by ID
	GetPolicySuspension(context.Context, *connect.Request[v1.GetPolicySuspensionRequest]) (*connect.Response[v1.GetPolicySuspensionResponse], error)
	// List policy suspensions
	//
	// List all policy suspensions for the organization
	ListPolicySuspensions(context.Context, *connect.Request[v1.ListPolicySuspensionsRequest]) (*connect.Response[v1.ListPolicySuspensionsResponse], error)
	// Delete policy suspension
	//
	// Delete a policy suspension
	DeletePolicySuspension(context.Context, *connect.Request[v1.DeletePolicySuspensionRequest]) (*connect.Response[v1.DeletePolicySuspensionResponse], error)
	// Generate Rego code from natural language
	//
	// Translates a natural language prompt into OPA/Rego policy or permission code using an LLM.
	CreateRegoCodeFromNaturalLanguage(context.Context, *connect.Request[v1.CreateRegoCodeFromNaturalLanguageRequest]) (*connect.Response[v1.CreateRegoCodeFromNaturalLanguageResponse], error)
}

// NewPoliciesServiceClient constructs a client for the core.v1.PoliciesService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPoliciesServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PoliciesServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	policiesServiceMethods := v1.File_core_v1_policies_proto.Services().ByName("PoliciesService").Methods()
	return &policiesServiceClient{
		listPolicies: connect.NewClient[v1.ListPoliciesRequest, v1.ListPoliciesResponse](
			httpClient,
			baseURL+PoliciesServiceListPoliciesProcedure,
			connect.WithSchema(policiesServiceMethods.ByName("ListPolicies")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		getPolicy: connect.NewClient[v1.GetPolicyRequest, v1.GetPolicyResponse](
			httpClient,
			baseURL+PoliciesServiceGetPolicyProcedure,
			connect.WithSchema(policiesServiceMethods.ByName("GetPolicy")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		getPolicyCodeValidity: connect.NewClient[v1.GetPolicyCodeValidityRequest, v1.GetPolicyCodeValidityResponse](
			httpClient,
			baseURL+PoliciesServiceGetPolicyCodeValidityProcedure,
			connect.WithSchema(policiesServiceMethods.ByName("GetPolicyCodeValidity")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		createPolicy: connect.NewClient[v1.CreatePolicyRequest, v1.CreatePolicyResponse](
			httpClient,
			baseURL+PoliciesServiceCreatePolicyProcedure,
			connect.WithSchema(policiesServiceMethods.ByName("CreatePolicy")),
			connect.WithClientOptions(opts...),
		),
		updatePolicy: connect.NewClient[v1.UpdatePolicyRequest, v1.UpdatePolicyResponse](
			httpClient,
			baseURL+PoliciesServiceUpdatePolicyProcedure,
			connect.WithSchema(policiesServiceMethods.ByName("UpdatePolicy")),
			connect.WithClientOptions(opts...),
		),
		updatePolicyV2: connect.NewClient[v1.UpdatePolicyV2Request, v1.UpdatePolicyV2Response](
			httpClient,
			baseURL+PoliciesServiceUpdatePolicyV2Procedure,
			connect.WithSchema(policiesServiceMethods.ByName("UpdatePolicyV2")),
			connect.WithClientOptions(opts...),
		),
		deletePolicy: connect.NewClient[v1.DeletePolicyRequest, v1.DeletePolicyResponse](
			httpClient,
			baseURL+PoliciesServiceDeletePolicyProcedure,
			connect.WithSchema(policiesServiceMethods.ByName("DeletePolicy")),
			connect.WithClientOptions(opts...),
		),
		createPolicyReport: connect.NewClient[v1.CreatePolicyReportRequest, v1.CreatePolicyReportResponse](
			httpClient,
			baseURL+PoliciesServiceCreatePolicyReportProcedure,
			connect.WithSchema(policiesServiceMethods.ByName("CreatePolicyReport")),
			connect.WithClientOptions(opts...),
		),
		getPolicyReport: connect.NewClient[v1.GetPolicyReportRequest, v1.GetPolicyReportResponse](
			httpClient,
			baseURL+PoliciesServiceGetPolicyReportProcedure,
			connect.WithSchema(policiesServiceMethods.ByName("GetPolicyReport")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		getPolicyImpactReportGraph: connect.NewClient[v1.GetPolicyImpactReportGraphRequest, v1.GetPolicyImpactReportGraphResponse](
			httpClient,
			baseURL+PoliciesServiceGetPolicyImpactReportGraphProcedure,
			connect.WithSchema(policiesServiceMethods.ByName("GetPolicyImpactReportGraph")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		listPolicyImpactReportLogs: connect.NewClient[v1.ListPolicyImpactReportLogsRequest, v1.ListPolicyImpactReportLogsResponse](
			httpClient,
			baseURL+PoliciesServiceListPolicyImpactReportLogsProcedure,
			connect.WithSchema(policiesServiceMethods.ByName("ListPolicyImpactReportLogs")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		createPolicyStageConfiguration: connect.NewClient[v1.CreatePolicyStageConfigurationRequest, v1.CreatePolicyStageConfigurationResponse](
			httpClient,
			baseURL+PoliciesServiceCreatePolicyStageConfigurationProcedure,
			connect.WithSchema(policiesServiceMethods.ByName("CreatePolicyStageConfiguration")),
			connect.WithClientOptions(opts...),
		),
		getPolicyStageConfiguration: connect.NewClient[v1.GetPolicyStageConfigurationRequest, v1.GetPolicyStageConfigurationResponse](
			httpClient,
			baseURL+PoliciesServiceGetPolicyStageConfigurationProcedure,
			connect.WithSchema(policiesServiceMethods.ByName("GetPolicyStageConfiguration")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		listPolicyStageConfigurations: connect.NewClient[v1.ListPolicyStageConfigurationsRequest, v1.ListPolicyStageConfigurationsResponse](
			httpClient,
			baseURL+PoliciesServiceListPolicyStageConfigurationsProcedure,
			connect.WithSchema(policiesServiceMethods.ByName("ListPolicyStageConfigurations")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		updatePolicyStageConfiguration: connect.NewClient[v1.UpdatePolicyStageConfigurationRequest, v1.UpdatePolicyStageConfigurationResponse](
			httpClient,
			baseURL+PoliciesServiceUpdatePolicyStageConfigurationProcedure,
			connect.WithSchema(policiesServiceMethods.ByName("UpdatePolicyStageConfiguration")),
			connect.WithClientOptions(opts...),
		),
		updatePolicyStageConfigurationV2: connect.NewClient[v1.UpdatePolicyStageConfigurationV2Request, v1.UpdatePolicyStageConfigurationV2Response](
			httpClient,
			baseURL+PoliciesServiceUpdatePolicyStageConfigurationV2Procedure,
			connect.WithSchema(policiesServiceMethods.ByName("UpdatePolicyStageConfigurationV2")),
			connect.WithClientOptions(opts...),
		),
		deletePolicyStageConfiguration: connect.NewClient[v1.DeletePolicyStageConfigurationRequest, v1.DeletePolicyStageConfigurationResponse](
			httpClient,
			baseURL+PoliciesServiceDeletePolicyStageConfigurationProcedure,
			connect.WithSchema(policiesServiceMethods.ByName("DeletePolicyStageConfiguration")),
			connect.WithClientOptions(opts...),
		),
		getPolicyVersion: connect.NewClient[v1.GetPolicyVersionRequest, v1.GetPolicyVersionResponse](
			httpClient,
			baseURL+PoliciesServiceGetPolicyVersionProcedure,
			connect.WithSchema(policiesServiceMethods.ByName("GetPolicyVersion")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		listPolicyVersions: connect.NewClient[v1.ListPolicyVersionsRequest, v1.ListPolicyVersionsResponse](
			httpClient,
			baseURL+PoliciesServiceListPolicyVersionsProcedure,
			connect.WithSchema(policiesServiceMethods.ByName("ListPolicyVersions")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		createPolicySuspension: connect.NewClient[v1.CreatePolicySuspensionRequest, v1.CreatePolicySuspensionResponse](
			httpClient,
			baseURL+PoliciesServiceCreatePolicySuspensionProcedure,
			connect.WithSchema(policiesServiceMethods.ByName("CreatePolicySuspension")),
			connect.WithClientOptions(opts...),
		),
		getPolicySuspension: connect.NewClient[v1.GetPolicySuspensionRequest, v1.GetPolicySuspensionResponse](
			httpClient,
			baseURL+PoliciesServiceGetPolicySuspensionProcedure,
			connect.WithSchema(policiesServiceMethods.ByName("GetPolicySuspension")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		listPolicySuspensions: connect.NewClient[v1.ListPolicySuspensionsRequest, v1.ListPolicySuspensionsResponse](
			httpClient,
			baseURL+PoliciesServiceListPolicySuspensionsProcedure,
			connect.WithSchema(policiesServiceMethods.ByName("ListPolicySuspensions")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		deletePolicySuspension: connect.NewClient[v1.DeletePolicySuspensionRequest, v1.DeletePolicySuspensionResponse](
			httpClient,
			baseURL+PoliciesServiceDeletePolicySuspensionProcedure,
			connect.WithSchema(policiesServiceMethods.ByName("DeletePolicySuspension")),
			connect.WithClientOptions(opts...),
		),
		createRegoCodeFromNaturalLanguage: connect.NewClient[v1.CreateRegoCodeFromNaturalLanguageRequest, v1.CreateRegoCodeFromNaturalLanguageResponse](
			httpClient,
			baseURL+PoliciesServiceCreateRegoCodeFromNaturalLanguageProcedure,
			connect.WithSchema(policiesServiceMethods.ByName("CreateRegoCodeFromNaturalLanguage")),
			connect.WithClientOptions(opts...),
		),
	}
}

// policiesServiceClient implements PoliciesServiceClient.
type policiesServiceClient struct {
	listPolicies                      *connect.Client[v1.ListPoliciesRequest, v1.ListPoliciesResponse]
	getPolicy                         *connect.Client[v1.GetPolicyRequest, v1.GetPolicyResponse]
	getPolicyCodeValidity             *connect.Client[v1.GetPolicyCodeValidityRequest, v1.GetPolicyCodeValidityResponse]
	createPolicy                      *connect.Client[v1.CreatePolicyRequest, v1.CreatePolicyResponse]
	updatePolicy                      *connect.Client[v1.UpdatePolicyRequest, v1.UpdatePolicyResponse]
	updatePolicyV2                    *connect.Client[v1.UpdatePolicyV2Request, v1.UpdatePolicyV2Response]
	deletePolicy                      *connect.Client[v1.DeletePolicyRequest, v1.DeletePolicyResponse]
	createPolicyReport                *connect.Client[v1.CreatePolicyReportRequest, v1.CreatePolicyReportResponse]
	getPolicyReport                   *connect.Client[v1.GetPolicyReportRequest, v1.GetPolicyReportResponse]
	getPolicyImpactReportGraph        *connect.Client[v1.GetPolicyImpactReportGraphRequest, v1.GetPolicyImpactReportGraphResponse]
	listPolicyImpactReportLogs        *connect.Client[v1.ListPolicyImpactReportLogsRequest, v1.ListPolicyImpactReportLogsResponse]
	createPolicyStageConfiguration    *connect.Client[v1.CreatePolicyStageConfigurationRequest, v1.CreatePolicyStageConfigurationResponse]
	getPolicyStageConfiguration       *connect.Client[v1.GetPolicyStageConfigurationRequest, v1.GetPolicyStageConfigurationResponse]
	listPolicyStageConfigurations     *connect.Client[v1.ListPolicyStageConfigurationsRequest, v1.ListPolicyStageConfigurationsResponse]
	updatePolicyStageConfiguration    *connect.Client[v1.UpdatePolicyStageConfigurationRequest, v1.UpdatePolicyStageConfigurationResponse]
	updatePolicyStageConfigurationV2  *connect.Client[v1.UpdatePolicyStageConfigurationV2Request, v1.UpdatePolicyStageConfigurationV2Response]
	deletePolicyStageConfiguration    *connect.Client[v1.DeletePolicyStageConfigurationRequest, v1.DeletePolicyStageConfigurationResponse]
	getPolicyVersion                  *connect.Client[v1.GetPolicyVersionRequest, v1.GetPolicyVersionResponse]
	listPolicyVersions                *connect.Client[v1.ListPolicyVersionsRequest, v1.ListPolicyVersionsResponse]
	createPolicySuspension            *connect.Client[v1.CreatePolicySuspensionRequest, v1.CreatePolicySuspensionResponse]
	getPolicySuspension               *connect.Client[v1.GetPolicySuspensionRequest, v1.GetPolicySuspensionResponse]
	listPolicySuspensions             *connect.Client[v1.ListPolicySuspensionsRequest, v1.ListPolicySuspensionsResponse]
	deletePolicySuspension            *connect.Client[v1.DeletePolicySuspensionRequest, v1.DeletePolicySuspensionResponse]
	createRegoCodeFromNaturalLanguage *connect.Client[v1.CreateRegoCodeFromNaturalLanguageRequest, v1.CreateRegoCodeFromNaturalLanguageResponse]
}

// ListPolicies calls core.v1.PoliciesService.ListPolicies.
func (c *policiesServiceClient) ListPolicies(ctx context.Context, req *connect.Request[v1.ListPoliciesRequest]) (*connect.Response[v1.ListPoliciesResponse], error) {
	return c.listPolicies.CallUnary(ctx, req)
}

// GetPolicy calls core.v1.PoliciesService.GetPolicy.
func (c *policiesServiceClient) GetPolicy(ctx context.Context, req *connect.Request[v1.GetPolicyRequest]) (*connect.Response[v1.GetPolicyResponse], error) {
	return c.getPolicy.CallUnary(ctx, req)
}

// GetPolicyCodeValidity calls core.v1.PoliciesService.GetPolicyCodeValidity.
func (c *policiesServiceClient) GetPolicyCodeValidity(ctx context.Context, req *connect.Request[v1.GetPolicyCodeValidityRequest]) (*connect.Response[v1.GetPolicyCodeValidityResponse], error) {
	return c.getPolicyCodeValidity.CallUnary(ctx, req)
}

// CreatePolicy calls core.v1.PoliciesService.CreatePolicy.
func (c *policiesServiceClient) CreatePolicy(ctx context.Context, req *connect.Request[v1.CreatePolicyRequest]) (*connect.Response[v1.CreatePolicyResponse], error) {
	return c.createPolicy.CallUnary(ctx, req)
}

// UpdatePolicy calls core.v1.PoliciesService.UpdatePolicy.
func (c *policiesServiceClient) UpdatePolicy(ctx context.Context, req *connect.Request[v1.UpdatePolicyRequest]) (*connect.Response[v1.UpdatePolicyResponse], error) {
	return c.updatePolicy.CallUnary(ctx, req)
}

// UpdatePolicyV2 calls core.v1.PoliciesService.UpdatePolicyV2.
func (c *policiesServiceClient) UpdatePolicyV2(ctx context.Context, req *connect.Request[v1.UpdatePolicyV2Request]) (*connect.Response[v1.UpdatePolicyV2Response], error) {
	return c.updatePolicyV2.CallUnary(ctx, req)
}

// DeletePolicy calls core.v1.PoliciesService.DeletePolicy.
func (c *policiesServiceClient) DeletePolicy(ctx context.Context, req *connect.Request[v1.DeletePolicyRequest]) (*connect.Response[v1.DeletePolicyResponse], error) {
	return c.deletePolicy.CallUnary(ctx, req)
}

// CreatePolicyReport calls core.v1.PoliciesService.CreatePolicyReport.
func (c *policiesServiceClient) CreatePolicyReport(ctx context.Context, req *connect.Request[v1.CreatePolicyReportRequest]) (*connect.Response[v1.CreatePolicyReportResponse], error) {
	return c.createPolicyReport.CallUnary(ctx, req)
}

// GetPolicyReport calls core.v1.PoliciesService.GetPolicyReport.
func (c *policiesServiceClient) GetPolicyReport(ctx context.Context, req *connect.Request[v1.GetPolicyReportRequest]) (*connect.Response[v1.GetPolicyReportResponse], error) {
	return c.getPolicyReport.CallUnary(ctx, req)
}

// GetPolicyImpactReportGraph calls core.v1.PoliciesService.GetPolicyImpactReportGraph.
func (c *policiesServiceClient) GetPolicyImpactReportGraph(ctx context.Context, req *connect.Request[v1.GetPolicyImpactReportGraphRequest]) (*connect.Response[v1.GetPolicyImpactReportGraphResponse], error) {
	return c.getPolicyImpactReportGraph.CallUnary(ctx, req)
}

// ListPolicyImpactReportLogs calls core.v1.PoliciesService.ListPolicyImpactReportLogs.
func (c *policiesServiceClient) ListPolicyImpactReportLogs(ctx context.Context, req *connect.Request[v1.ListPolicyImpactReportLogsRequest]) (*connect.Response[v1.ListPolicyImpactReportLogsResponse], error) {
	return c.listPolicyImpactReportLogs.CallUnary(ctx, req)
}

// CreatePolicyStageConfiguration calls core.v1.PoliciesService.CreatePolicyStageConfiguration.
func (c *policiesServiceClient) CreatePolicyStageConfiguration(ctx context.Context, req *connect.Request[v1.CreatePolicyStageConfigurationRequest]) (*connect.Response[v1.CreatePolicyStageConfigurationResponse], error) {
	return c.createPolicyStageConfiguration.CallUnary(ctx, req)
}

// GetPolicyStageConfiguration calls core.v1.PoliciesService.GetPolicyStageConfiguration.
func (c *policiesServiceClient) GetPolicyStageConfiguration(ctx context.Context, req *connect.Request[v1.GetPolicyStageConfigurationRequest]) (*connect.Response[v1.GetPolicyStageConfigurationResponse], error) {
	return c.getPolicyStageConfiguration.CallUnary(ctx, req)
}

// ListPolicyStageConfigurations calls core.v1.PoliciesService.ListPolicyStageConfigurations.
func (c *policiesServiceClient) ListPolicyStageConfigurations(ctx context.Context, req *connect.Request[v1.ListPolicyStageConfigurationsRequest]) (*connect.Response[v1.ListPolicyStageConfigurationsResponse], error) {
	return c.listPolicyStageConfigurations.CallUnary(ctx, req)
}

// UpdatePolicyStageConfiguration calls core.v1.PoliciesService.UpdatePolicyStageConfiguration.
func (c *policiesServiceClient) UpdatePolicyStageConfiguration(ctx context.Context, req *connect.Request[v1.UpdatePolicyStageConfigurationRequest]) (*connect.Response[v1.UpdatePolicyStageConfigurationResponse], error) {
	return c.updatePolicyStageConfiguration.CallUnary(ctx, req)
}

// UpdatePolicyStageConfigurationV2 calls core.v1.PoliciesService.UpdatePolicyStageConfigurationV2.
func (c *policiesServiceClient) UpdatePolicyStageConfigurationV2(ctx context.Context, req *connect.Request[v1.UpdatePolicyStageConfigurationV2Request]) (*connect.Response[v1.UpdatePolicyStageConfigurationV2Response], error) {
	return c.updatePolicyStageConfigurationV2.CallUnary(ctx, req)
}

// DeletePolicyStageConfiguration calls core.v1.PoliciesService.DeletePolicyStageConfiguration.
func (c *policiesServiceClient) DeletePolicyStageConfiguration(ctx context.Context, req *connect.Request[v1.DeletePolicyStageConfigurationRequest]) (*connect.Response[v1.DeletePolicyStageConfigurationResponse], error) {
	return c.deletePolicyStageConfiguration.CallUnary(ctx, req)
}

// GetPolicyVersion calls core.v1.PoliciesService.GetPolicyVersion.
func (c *policiesServiceClient) GetPolicyVersion(ctx context.Context, req *connect.Request[v1.GetPolicyVersionRequest]) (*connect.Response[v1.GetPolicyVersionResponse], error) {
	return c.getPolicyVersion.CallUnary(ctx, req)
}

// ListPolicyVersions calls core.v1.PoliciesService.ListPolicyVersions.
func (c *policiesServiceClient) ListPolicyVersions(ctx context.Context, req *connect.Request[v1.ListPolicyVersionsRequest]) (*connect.Response[v1.ListPolicyVersionsResponse], error) {
	return c.listPolicyVersions.CallUnary(ctx, req)
}

// CreatePolicySuspension calls core.v1.PoliciesService.CreatePolicySuspension.
func (c *policiesServiceClient) CreatePolicySuspension(ctx context.Context, req *connect.Request[v1.CreatePolicySuspensionRequest]) (*connect.Response[v1.CreatePolicySuspensionResponse], error) {
	return c.createPolicySuspension.CallUnary(ctx, req)
}

// GetPolicySuspension calls core.v1.PoliciesService.GetPolicySuspension.
func (c *policiesServiceClient) GetPolicySuspension(ctx context.Context, req *connect.Request[v1.GetPolicySuspensionRequest]) (*connect.Response[v1.GetPolicySuspensionResponse], error) {
	return c.getPolicySuspension.CallUnary(ctx, req)
}

// ListPolicySuspensions calls core.v1.PoliciesService.ListPolicySuspensions.
func (c *policiesServiceClient) ListPolicySuspensions(ctx context.Context, req *connect.Request[v1.ListPolicySuspensionsRequest]) (*connect.Response[v1.ListPolicySuspensionsResponse], error) {
	return c.listPolicySuspensions.CallUnary(ctx, req)
}

// DeletePolicySuspension calls core.v1.PoliciesService.DeletePolicySuspension.
func (c *policiesServiceClient) DeletePolicySuspension(ctx context.Context, req *connect.Request[v1.DeletePolicySuspensionRequest]) (*connect.Response[v1.DeletePolicySuspensionResponse], error) {
	return c.deletePolicySuspension.CallUnary(ctx, req)
}

// CreateRegoCodeFromNaturalLanguage calls
// core.v1.PoliciesService.CreateRegoCodeFromNaturalLanguage.
func (c *policiesServiceClient) CreateRegoCodeFromNaturalLanguage(ctx context.Context, req *connect.Request[v1.CreateRegoCodeFromNaturalLanguageRequest]) (*connect.Response[v1.CreateRegoCodeFromNaturalLanguageResponse], error) {
	return c.createRegoCodeFromNaturalLanguage.CallUnary(ctx, req)
}

// PoliciesServiceHandler is an implementation of the core.v1.PoliciesService service.
type PoliciesServiceHandler interface {
	// List policies
	//
	// List all policies
	ListPolicies(context.Context, *connect.Request[v1.ListPoliciesRequest]) (*connect.Response[v1.ListPoliciesResponse], error)
	// Get policy
	//
	// Get a policy
	GetPolicy(context.Context, *connect.Request[v1.GetPolicyRequest]) (*connect.Response[v1.GetPolicyResponse], error)
	// Get policy code validity
	//
	// Get the validity of a policy code
	GetPolicyCodeValidity(context.Context, *connect.Request[v1.GetPolicyCodeValidityRequest]) (*connect.Response[v1.GetPolicyCodeValidityResponse], error)
	// Create policy
	//
	// Create a policy
	CreatePolicy(context.Context, *connect.Request[v1.CreatePolicyRequest]) (*connect.Response[v1.CreatePolicyResponse], error)
	// Update policy
	//
	// Update a policy
	UpdatePolicy(context.Context, *connect.Request[v1.UpdatePolicyRequest]) (*connect.Response[v1.UpdatePolicyResponse], error)
	// Update policy (full object replacement)
	//
	// Update a policy by sending the full object. All mutable fields are replaced.
	UpdatePolicyV2(context.Context, *connect.Request[v1.UpdatePolicyV2Request]) (*connect.Response[v1.UpdatePolicyV2Response], error)
	// Delete policy
	//
	// Delete a policy
	DeletePolicy(context.Context, *connect.Request[v1.DeletePolicyRequest]) (*connect.Response[v1.DeletePolicyResponse], error)
	// Create policy report
	//
	// Generate a policy report from policy code
	CreatePolicyReport(context.Context, *connect.Request[v1.CreatePolicyReportRequest]) (*connect.Response[v1.CreatePolicyReportResponse], error)
	// Get policy report
	//
	// Get a specific policy report by ID
	GetPolicyReport(context.Context, *connect.Request[v1.GetPolicyReportRequest]) (*connect.Response[v1.GetPolicyReportResponse], error)
	// Get policy report connector graph
	//
	// Get the connector graph for a specific policy report
	GetPolicyImpactReportGraph(context.Context, *connect.Request[v1.GetPolicyImpactReportGraphRequest]) (*connect.Response[v1.GetPolicyImpactReportGraphResponse], error)
	// List policy impact report logs
	//
	// List logs that would have been triggered by the policy in the report
	ListPolicyImpactReportLogs(context.Context, *connect.Request[v1.ListPolicyImpactReportLogsRequest]) (*connect.Response[v1.ListPolicyImpactReportLogsResponse], error)
	// Create policy stage configuration
	//
	// Create a policy stage configuration
	CreatePolicyStageConfiguration(context.Context, *connect.Request[v1.CreatePolicyStageConfigurationRequest]) (*connect.Response[v1.CreatePolicyStageConfigurationResponse], error)
	GetPolicyStageConfiguration(context.Context, *connect.Request[v1.GetPolicyStageConfigurationRequest]) (*connect.Response[v1.GetPolicyStageConfigurationResponse], error)
	ListPolicyStageConfigurations(context.Context, *connect.Request[v1.ListPolicyStageConfigurationsRequest]) (*connect.Response[v1.ListPolicyStageConfigurationsResponse], error)
	// Update policy stage configuration
	//
	// Update a policy stage configuration
	UpdatePolicyStageConfiguration(context.Context, *connect.Request[v1.UpdatePolicyStageConfigurationRequest]) (*connect.Response[v1.UpdatePolicyStageConfigurationResponse], error)
	// Update policy stage configuration (full object replacement)
	//
	// Update a policy stage configuration by sending the full object. All mutable fields are replaced.
	UpdatePolicyStageConfigurationV2(context.Context, *connect.Request[v1.UpdatePolicyStageConfigurationV2Request]) (*connect.Response[v1.UpdatePolicyStageConfigurationV2Response], error)
	// Delete policy stage configuration
	//
	// Delete a policy stage configuration
	DeletePolicyStageConfiguration(context.Context, *connect.Request[v1.DeletePolicyStageConfigurationRequest]) (*connect.Response[v1.DeletePolicyStageConfigurationResponse], error)
	GetPolicyVersion(context.Context, *connect.Request[v1.GetPolicyVersionRequest]) (*connect.Response[v1.GetPolicyVersionResponse], error)
	ListPolicyVersions(context.Context, *connect.Request[v1.ListPolicyVersionsRequest]) (*connect.Response[v1.ListPolicyVersionsResponse], error)
	// Create policy suspension
	//
	// Create a policy suspension for a specific identity
	CreatePolicySuspension(context.Context, *connect.Request[v1.CreatePolicySuspensionRequest]) (*connect.Response[v1.CreatePolicySuspensionResponse], error)
	// Get policy suspension
	//
	// Get a policy suspension by ID
	GetPolicySuspension(context.Context, *connect.Request[v1.GetPolicySuspensionRequest]) (*connect.Response[v1.GetPolicySuspensionResponse], error)
	// List policy suspensions
	//
	// List all policy suspensions for the organization
	ListPolicySuspensions(context.Context, *connect.Request[v1.ListPolicySuspensionsRequest]) (*connect.Response[v1.ListPolicySuspensionsResponse], error)
	// Delete policy suspension
	//
	// Delete a policy suspension
	DeletePolicySuspension(context.Context, *connect.Request[v1.DeletePolicySuspensionRequest]) (*connect.Response[v1.DeletePolicySuspensionResponse], error)
	// Generate Rego code from natural language
	//
	// Translates a natural language prompt into OPA/Rego policy or permission code using an LLM.
	CreateRegoCodeFromNaturalLanguage(context.Context, *connect.Request[v1.CreateRegoCodeFromNaturalLanguageRequest]) (*connect.Response[v1.CreateRegoCodeFromNaturalLanguageResponse], error)
}

// NewPoliciesServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPoliciesServiceHandler(svc PoliciesServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	policiesServiceMethods := v1.File_core_v1_policies_proto.Services().ByName("PoliciesService").Methods()
	policiesServiceListPoliciesHandler := connect.NewUnaryHandler(
		PoliciesServiceListPoliciesProcedure,
		svc.ListPolicies,
		connect.WithSchema(policiesServiceMethods.ByName("ListPolicies")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	policiesServiceGetPolicyHandler := connect.NewUnaryHandler(
		PoliciesServiceGetPolicyProcedure,
		svc.GetPolicy,
		connect.WithSchema(policiesServiceMethods.ByName("GetPolicy")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	policiesServiceGetPolicyCodeValidityHandler := connect.NewUnaryHandler(
		PoliciesServiceGetPolicyCodeValidityProcedure,
		svc.GetPolicyCodeValidity,
		connect.WithSchema(policiesServiceMethods.ByName("GetPolicyCodeValidity")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	policiesServiceCreatePolicyHandler := connect.NewUnaryHandler(
		PoliciesServiceCreatePolicyProcedure,
		svc.CreatePolicy,
		connect.WithSchema(policiesServiceMethods.ByName("CreatePolicy")),
		connect.WithHandlerOptions(opts...),
	)
	policiesServiceUpdatePolicyHandler := connect.NewUnaryHandler(
		PoliciesServiceUpdatePolicyProcedure,
		svc.UpdatePolicy,
		connect.WithSchema(policiesServiceMethods.ByName("UpdatePolicy")),
		connect.WithHandlerOptions(opts...),
	)
	policiesServiceUpdatePolicyV2Handler := connect.NewUnaryHandler(
		PoliciesServiceUpdatePolicyV2Procedure,
		svc.UpdatePolicyV2,
		connect.WithSchema(policiesServiceMethods.ByName("UpdatePolicyV2")),
		connect.WithHandlerOptions(opts...),
	)
	policiesServiceDeletePolicyHandler := connect.NewUnaryHandler(
		PoliciesServiceDeletePolicyProcedure,
		svc.DeletePolicy,
		connect.WithSchema(policiesServiceMethods.ByName("DeletePolicy")),
		connect.WithHandlerOptions(opts...),
	)
	policiesServiceCreatePolicyReportHandler := connect.NewUnaryHandler(
		PoliciesServiceCreatePolicyReportProcedure,
		svc.CreatePolicyReport,
		connect.WithSchema(policiesServiceMethods.ByName("CreatePolicyReport")),
		connect.WithHandlerOptions(opts...),
	)
	policiesServiceGetPolicyReportHandler := connect.NewUnaryHandler(
		PoliciesServiceGetPolicyReportProcedure,
		svc.GetPolicyReport,
		connect.WithSchema(policiesServiceMethods.ByName("GetPolicyReport")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	policiesServiceGetPolicyImpactReportGraphHandler := connect.NewUnaryHandler(
		PoliciesServiceGetPolicyImpactReportGraphProcedure,
		svc.GetPolicyImpactReportGraph,
		connect.WithSchema(policiesServiceMethods.ByName("GetPolicyImpactReportGraph")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	policiesServiceListPolicyImpactReportLogsHandler := connect.NewUnaryHandler(
		PoliciesServiceListPolicyImpactReportLogsProcedure,
		svc.ListPolicyImpactReportLogs,
		connect.WithSchema(policiesServiceMethods.ByName("ListPolicyImpactReportLogs")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	policiesServiceCreatePolicyStageConfigurationHandler := connect.NewUnaryHandler(
		PoliciesServiceCreatePolicyStageConfigurationProcedure,
		svc.CreatePolicyStageConfiguration,
		connect.WithSchema(policiesServiceMethods.ByName("CreatePolicyStageConfiguration")),
		connect.WithHandlerOptions(opts...),
	)
	policiesServiceGetPolicyStageConfigurationHandler := connect.NewUnaryHandler(
		PoliciesServiceGetPolicyStageConfigurationProcedure,
		svc.GetPolicyStageConfiguration,
		connect.WithSchema(policiesServiceMethods.ByName("GetPolicyStageConfiguration")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	policiesServiceListPolicyStageConfigurationsHandler := connect.NewUnaryHandler(
		PoliciesServiceListPolicyStageConfigurationsProcedure,
		svc.ListPolicyStageConfigurations,
		connect.WithSchema(policiesServiceMethods.ByName("ListPolicyStageConfigurations")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	policiesServiceUpdatePolicyStageConfigurationHandler := connect.NewUnaryHandler(
		PoliciesServiceUpdatePolicyStageConfigurationProcedure,
		svc.UpdatePolicyStageConfiguration,
		connect.WithSchema(policiesServiceMethods.ByName("UpdatePolicyStageConfiguration")),
		connect.WithHandlerOptions(opts...),
	)
	policiesServiceUpdatePolicyStageConfigurationV2Handler := connect.NewUnaryHandler(
		PoliciesServiceUpdatePolicyStageConfigurationV2Procedure,
		svc.UpdatePolicyStageConfigurationV2,
		connect.WithSchema(policiesServiceMethods.ByName("UpdatePolicyStageConfigurationV2")),
		connect.WithHandlerOptions(opts...),
	)
	policiesServiceDeletePolicyStageConfigurationHandler := connect.NewUnaryHandler(
		PoliciesServiceDeletePolicyStageConfigurationProcedure,
		svc.DeletePolicyStageConfiguration,
		connect.WithSchema(policiesServiceMethods.ByName("DeletePolicyStageConfiguration")),
		connect.WithHandlerOptions(opts...),
	)
	policiesServiceGetPolicyVersionHandler := connect.NewUnaryHandler(
		PoliciesServiceGetPolicyVersionProcedure,
		svc.GetPolicyVersion,
		connect.WithSchema(policiesServiceMethods.ByName("GetPolicyVersion")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	policiesServiceListPolicyVersionsHandler := connect.NewUnaryHandler(
		PoliciesServiceListPolicyVersionsProcedure,
		svc.ListPolicyVersions,
		connect.WithSchema(policiesServiceMethods.ByName("ListPolicyVersions")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	policiesServiceCreatePolicySuspensionHandler := connect.NewUnaryHandler(
		PoliciesServiceCreatePolicySuspensionProcedure,
		svc.CreatePolicySuspension,
		connect.WithSchema(policiesServiceMethods.ByName("CreatePolicySuspension")),
		connect.WithHandlerOptions(opts...),
	)
	policiesServiceGetPolicySuspensionHandler := connect.NewUnaryHandler(
		PoliciesServiceGetPolicySuspensionProcedure,
		svc.GetPolicySuspension,
		connect.WithSchema(policiesServiceMethods.ByName("GetPolicySuspension")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	policiesServiceListPolicySuspensionsHandler := connect.NewUnaryHandler(
		PoliciesServiceListPolicySuspensionsProcedure,
		svc.ListPolicySuspensions,
		connect.WithSchema(policiesServiceMethods.ByName("ListPolicySuspensions")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	policiesServiceDeletePolicySuspensionHandler := connect.NewUnaryHandler(
		PoliciesServiceDeletePolicySuspensionProcedure,
		svc.DeletePolicySuspension,
		connect.WithSchema(policiesServiceMethods.ByName("DeletePolicySuspension")),
		connect.WithHandlerOptions(opts...),
	)
	policiesServiceCreateRegoCodeFromNaturalLanguageHandler := connect.NewUnaryHandler(
		PoliciesServiceCreateRegoCodeFromNaturalLanguageProcedure,
		svc.CreateRegoCodeFromNaturalLanguage,
		connect.WithSchema(policiesServiceMethods.ByName("CreateRegoCodeFromNaturalLanguage")),
		connect.WithHandlerOptions(opts...),
	)
	return "/core.v1.PoliciesService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PoliciesServiceListPoliciesProcedure:
			policiesServiceListPoliciesHandler.ServeHTTP(w, r)
		case PoliciesServiceGetPolicyProcedure:
			policiesServiceGetPolicyHandler.ServeHTTP(w, r)
		case PoliciesServiceGetPolicyCodeValidityProcedure:
			policiesServiceGetPolicyCodeValidityHandler.ServeHTTP(w, r)
		case PoliciesServiceCreatePolicyProcedure:
			policiesServiceCreatePolicyHandler.ServeHTTP(w, r)
		case PoliciesServiceUpdatePolicyProcedure:
			policiesServiceUpdatePolicyHandler.ServeHTTP(w, r)
		case PoliciesServiceUpdatePolicyV2Procedure:
			policiesServiceUpdatePolicyV2Handler.ServeHTTP(w, r)
		case PoliciesServiceDeletePolicyProcedure:
			policiesServiceDeletePolicyHandler.ServeHTTP(w, r)
		case PoliciesServiceCreatePolicyReportProcedure:
			policiesServiceCreatePolicyReportHandler.ServeHTTP(w, r)
		case PoliciesServiceGetPolicyReportProcedure:
			policiesServiceGetPolicyReportHandler.ServeHTTP(w, r)
		case PoliciesServiceGetPolicyImpactReportGraphProcedure:
			policiesServiceGetPolicyImpactReportGraphHandler.ServeHTTP(w, r)
		case PoliciesServiceListPolicyImpactReportLogsProcedure:
			policiesServiceListPolicyImpactReportLogsHandler.ServeHTTP(w, r)
		case PoliciesServiceCreatePolicyStageConfigurationProcedure:
			policiesServiceCreatePolicyStageConfigurationHandler.ServeHTTP(w, r)
		case PoliciesServiceGetPolicyStageConfigurationProcedure:
			policiesServiceGetPolicyStageConfigurationHandler.ServeHTTP(w, r)
		case PoliciesServiceListPolicyStageConfigurationsProcedure:
			policiesServiceListPolicyStageConfigurationsHandler.ServeHTTP(w, r)
		case PoliciesServiceUpdatePolicyStageConfigurationProcedure:
			policiesServiceUpdatePolicyStageConfigurationHandler.ServeHTTP(w, r)
		case PoliciesServiceUpdatePolicyStageConfigurationV2Procedure:
			policiesServiceUpdatePolicyStageConfigurationV2Handler.ServeHTTP(w, r)
		case PoliciesServiceDeletePolicyStageConfigurationProcedure:
			policiesServiceDeletePolicyStageConfigurationHandler.ServeHTTP(w, r)
		case PoliciesServiceGetPolicyVersionProcedure:
			policiesServiceGetPolicyVersionHandler.ServeHTTP(w, r)
		case PoliciesServiceListPolicyVersionsProcedure:
			policiesServiceListPolicyVersionsHandler.ServeHTTP(w, r)
		case PoliciesServiceCreatePolicySuspensionProcedure:
			policiesServiceCreatePolicySuspensionHandler.ServeHTTP(w, r)
		case PoliciesServiceGetPolicySuspensionProcedure:
			policiesServiceGetPolicySuspensionHandler.ServeHTTP(w, r)
		case PoliciesServiceListPolicySuspensionsProcedure:
			policiesServiceListPolicySuspensionsHandler.ServeHTTP(w, r)
		case PoliciesServiceDeletePolicySuspensionProcedure:
			policiesServiceDeletePolicySuspensionHandler.ServeHTTP(w, r)
		case PoliciesServiceCreateRegoCodeFromNaturalLanguageProcedure:
			policiesServiceCreateRegoCodeFromNaturalLanguageHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPoliciesServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPoliciesServiceHandler struct{}

func (UnimplementedPoliciesServiceHandler) ListPolicies(context.Context, *connect.Request[v1.ListPoliciesRequest]) (*connect.Response[v1.ListPoliciesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("core.v1.PoliciesService.ListPolicies is not implemented"))
}

func (UnimplementedPoliciesServiceHandler) GetPolicy(context.Context, *connect.Request[v1.GetPolicyRequest]) (*connect.Response[v1.GetPolicyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("core.v1.PoliciesService.GetPolicy is not implemented"))
}

func (UnimplementedPoliciesServiceHandler) GetPolicyCodeValidity(context.Context, *connect.Request[v1.GetPolicyCodeValidityRequest]) (*connect.Response[v1.GetPolicyCodeValidityResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("core.v1.PoliciesService.GetPolicyCodeValidity is not implemented"))
}

func (UnimplementedPoliciesServiceHandler) CreatePolicy(context.Context, *connect.Request[v1.CreatePolicyRequest]) (*connect.Response[v1.CreatePolicyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("core.v1.PoliciesService.CreatePolicy is not implemented"))
}

func (UnimplementedPoliciesServiceHandler) UpdatePolicy(context.Context, *connect.Request[v1.UpdatePolicyRequest]) (*connect.Response[v1.UpdatePolicyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("core.v1.PoliciesService.UpdatePolicy is not implemented"))
}

func (UnimplementedPoliciesServiceHandler) UpdatePolicyV2(context.Context, *connect.Request[v1.UpdatePolicyV2Request]) (*connect.Response[v1.UpdatePolicyV2Response], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("core.v1.PoliciesService.UpdatePolicyV2 is not implemented"))
}

func (UnimplementedPoliciesServiceHandler) DeletePolicy(context.Context, *connect.Request[v1.DeletePolicyRequest]) (*connect.Response[v1.DeletePolicyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("core.v1.PoliciesService.DeletePolicy is not implemented"))
}

func (UnimplementedPoliciesServiceHandler) CreatePolicyReport(context.Context, *connect.Request[v1.CreatePolicyReportRequest]) (*connect.Response[v1.CreatePolicyReportResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("core.v1.PoliciesService.CreatePolicyReport is not implemented"))
}

func (UnimplementedPoliciesServiceHandler) GetPolicyReport(context.Context, *connect.Request[v1.GetPolicyReportRequest]) (*connect.Response[v1.GetPolicyReportResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("core.v1.PoliciesService.GetPolicyReport is not implemented"))
}

func (UnimplementedPoliciesServiceHandler) GetPolicyImpactReportGraph(context.Context, *connect.Request[v1.GetPolicyImpactReportGraphRequest]) (*connect.Response[v1.GetPolicyImpactReportGraphResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("core.v1.PoliciesService.GetPolicyImpactReportGraph is not implemented"))
}

func (UnimplementedPoliciesServiceHandler) ListPolicyImpactReportLogs(context.Context, *connect.Request[v1.ListPolicyImpactReportLogsRequest]) (*connect.Response[v1.ListPolicyImpactReportLogsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("core.v1.PoliciesService.ListPolicyImpactReportLogs is not implemented"))
}

func (UnimplementedPoliciesServiceHandler) CreatePolicyStageConfiguration(context.Context, *connect.Request[v1.CreatePolicyStageConfigurationRequest]) (*connect.Response[v1.CreatePolicyStageConfigurationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("core.v1.PoliciesService.CreatePolicyStageConfiguration is not implemented"))
}

func (UnimplementedPoliciesServiceHandler) GetPolicyStageConfiguration(context.Context, *connect.Request[v1.GetPolicyStageConfigurationRequest]) (*connect.Response[v1.GetPolicyStageConfigurationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("core.v1.PoliciesService.GetPolicyStageConfiguration is not implemented"))
}

func (UnimplementedPoliciesServiceHandler) ListPolicyStageConfigurations(context.Context, *connect.Request[v1.ListPolicyStageConfigurationsRequest]) (*connect.Response[v1.ListPolicyStageConfigurationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("core.v1.PoliciesService.ListPolicyStageConfigurations is not implemented"))
}

func (UnimplementedPoliciesServiceHandler) UpdatePolicyStageConfiguration(context.Context, *connect.Request[v1.UpdatePolicyStageConfigurationRequest]) (*connect.Response[v1.UpdatePolicyStageConfigurationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("core.v1.PoliciesService.UpdatePolicyStageConfiguration is not implemented"))
}

func (UnimplementedPoliciesServiceHandler) UpdatePolicyStageConfigurationV2(context.Context, *connect.Request[v1.UpdatePolicyStageConfigurationV2Request]) (*connect.Response[v1.UpdatePolicyStageConfigurationV2Response], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("core.v1.PoliciesService.UpdatePolicyStageConfigurationV2 is not implemented"))
}

func (UnimplementedPoliciesServiceHandler) DeletePolicyStageConfiguration(context.Context, *connect.Request[v1.DeletePolicyStageConfigurationRequest]) (*connect.Response[v1.DeletePolicyStageConfigurationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("core.v1.PoliciesService.DeletePolicyStageConfiguration is not implemented"))
}

func (UnimplementedPoliciesServiceHandler) GetPolicyVersion(context.Context, *connect.Request[v1.GetPolicyVersionRequest]) (*connect.Response[v1.GetPolicyVersionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("core.v1.PoliciesService.GetPolicyVersion is not implemented"))
}

func (UnimplementedPoliciesServiceHandler) ListPolicyVersions(context.Context, *connect.Request[v1.ListPolicyVersionsRequest]) (*connect.Response[v1.ListPolicyVersionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("core.v1.PoliciesService.ListPolicyVersions is not implemented"))
}

func (UnimplementedPoliciesServiceHandler) CreatePolicySuspension(context.Context, *connect.Request[v1.CreatePolicySuspensionRequest]) (*connect.Response[v1.CreatePolicySuspensionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("core.v1.PoliciesService.CreatePolicySuspension is not implemented"))
}

func (UnimplementedPoliciesServiceHandler) GetPolicySuspension(context.Context, *connect.Request[v1.GetPolicySuspensionRequest]) (*connect.Response[v1.GetPolicySuspensionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("core.v1.PoliciesService.GetPolicySuspension is not implemented"))
}

func (UnimplementedPoliciesServiceHandler) ListPolicySuspensions(context.Context, *connect.Request[v1.ListPolicySuspensionsRequest]) (*connect.Response[v1.ListPolicySuspensionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("core.v1.PoliciesService.ListPolicySuspensions is not implemented"))
}

func (UnimplementedPoliciesServiceHandler) DeletePolicySuspension(context.Context, *connect.Request[v1.DeletePolicySuspensionRequest]) (*connect.Response[v1.DeletePolicySuspensionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("core.v1.PoliciesService.DeletePolicySuspension is not implemented"))
}

func (UnimplementedPoliciesServiceHandler) CreateRegoCodeFromNaturalLanguage(context.Context, *connect.Request[v1.CreateRegoCodeFromNaturalLanguageRequest]) (*connect.Response[v1.CreateRegoCodeFromNaturalLanguageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("core.v1.PoliciesService.CreateRegoCodeFromNaturalLanguage is not implemented"))
}
