// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: core/v1/scenario_monitoring.proto

package corev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/formalco/go-sdk/v3/core/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ScenarioMonitoringServiceName is the fully-qualified name of the ScenarioMonitoringService
	// service.
	ScenarioMonitoringServiceName = "core.v1.ScenarioMonitoringService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ScenarioMonitoringServiceCreateScenarioMonitorProcedure is the fully-qualified name of the
	// ScenarioMonitoringService's CreateScenarioMonitor RPC.
	ScenarioMonitoringServiceCreateScenarioMonitorProcedure = "/core.v1.ScenarioMonitoringService/CreateScenarioMonitor"
	// ScenarioMonitoringServiceDeleteScenarioMonitorProcedure is the fully-qualified name of the
	// ScenarioMonitoringService's DeleteScenarioMonitor RPC.
	ScenarioMonitoringServiceDeleteScenarioMonitorProcedure = "/core.v1.ScenarioMonitoringService/DeleteScenarioMonitor"
	// ScenarioMonitoringServiceGetScenarioMonitorProcedure is the fully-qualified name of the
	// ScenarioMonitoringService's GetScenarioMonitor RPC.
	ScenarioMonitoringServiceGetScenarioMonitorProcedure = "/core.v1.ScenarioMonitoringService/GetScenarioMonitor"
	// ScenarioMonitoringServiceListScenarioMonitorsProcedure is the fully-qualified name of the
	// ScenarioMonitoringService's ListScenarioMonitors RPC.
	ScenarioMonitoringServiceListScenarioMonitorsProcedure = "/core.v1.ScenarioMonitoringService/ListScenarioMonitors"
	// ScenarioMonitoringServiceUpdateScenarioMonitorProcedure is the fully-qualified name of the
	// ScenarioMonitoringService's UpdateScenarioMonitor RPC.
	ScenarioMonitoringServiceUpdateScenarioMonitorProcedure = "/core.v1.ScenarioMonitoringService/UpdateScenarioMonitor"
	// ScenarioMonitoringServiceUpdateScenarioMonitorV2Procedure is the fully-qualified name of the
	// ScenarioMonitoringService's UpdateScenarioMonitorV2 RPC.
	ScenarioMonitoringServiceUpdateScenarioMonitorV2Procedure = "/core.v1.ScenarioMonitoringService/UpdateScenarioMonitorV2"
)

// ScenarioMonitoringServiceClient is a client for the core.v1.ScenarioMonitoringService service.
type ScenarioMonitoringServiceClient interface {
	// Add a scenario for LLM SSH Monitoring
	CreateScenarioMonitor(context.Context, *connect.Request[v1.CreateScenarioMonitorRequest]) (*connect.Response[v1.CreateScenarioMonitorResponse], error)
	// Delete a scenario from LLM SSH Monitoring
	DeleteScenarioMonitor(context.Context, *connect.Request[v1.DeleteScenarioMonitorRequest]) (*connect.Response[v1.DeleteScenarioMonitorResponse], error)
	// Retrieve all LLM session monitoring scenarios and their statuses
	GetScenarioMonitor(context.Context, *connect.Request[v1.GetScenarioMonitorRequest]) (*connect.Response[v1.GetScenarioMonitorResponse], error)
	ListScenarioMonitors(context.Context, *connect.Request[v1.ListScenarioMonitorsRequest]) (*connect.Response[v1.ListScenarioMonitorsResponse], error)
	// Update the status of a scenario used for LLM session monitoring
	UpdateScenarioMonitor(context.Context, *connect.Request[v1.UpdateScenarioMonitorRequest]) (*connect.Response[v1.UpdateScenarioMonitorResponse], error)
	// Update scenario monitor (full object replacement)
	//
	// Update a scenario monitor by sending the full object. All mutable fields are replaced.
	UpdateScenarioMonitorV2(context.Context, *connect.Request[v1.UpdateScenarioMonitorV2Request]) (*connect.Response[v1.UpdateScenarioMonitorV2Response], error)
}

// NewScenarioMonitoringServiceClient constructs a client for the core.v1.ScenarioMonitoringService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewScenarioMonitoringServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ScenarioMonitoringServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	scenarioMonitoringServiceMethods := v1.File_core_v1_scenario_monitoring_proto.Services().ByName("ScenarioMonitoringService").Methods()
	return &scenarioMonitoringServiceClient{
		createScenarioMonitor: connect.NewClient[v1.CreateScenarioMonitorRequest, v1.CreateScenarioMonitorResponse](
			httpClient,
			baseURL+ScenarioMonitoringServiceCreateScenarioMonitorProcedure,
			connect.WithSchema(scenarioMonitoringServiceMethods.ByName("CreateScenarioMonitor")),
			connect.WithClientOptions(opts...),
		),
		deleteScenarioMonitor: connect.NewClient[v1.DeleteScenarioMonitorRequest, v1.DeleteScenarioMonitorResponse](
			httpClient,
			baseURL+ScenarioMonitoringServiceDeleteScenarioMonitorProcedure,
			connect.WithSchema(scenarioMonitoringServiceMethods.ByName("DeleteScenarioMonitor")),
			connect.WithClientOptions(opts...),
		),
		getScenarioMonitor: connect.NewClient[v1.GetScenarioMonitorRequest, v1.GetScenarioMonitorResponse](
			httpClient,
			baseURL+ScenarioMonitoringServiceGetScenarioMonitorProcedure,
			connect.WithSchema(scenarioMonitoringServiceMethods.ByName("GetScenarioMonitor")),
			connect.WithClientOptions(opts...),
		),
		listScenarioMonitors: connect.NewClient[v1.ListScenarioMonitorsRequest, v1.ListScenarioMonitorsResponse](
			httpClient,
			baseURL+ScenarioMonitoringServiceListScenarioMonitorsProcedure,
			connect.WithSchema(scenarioMonitoringServiceMethods.ByName("ListScenarioMonitors")),
			connect.WithClientOptions(opts...),
		),
		updateScenarioMonitor: connect.NewClient[v1.UpdateScenarioMonitorRequest, v1.UpdateScenarioMonitorResponse](
			httpClient,
			baseURL+ScenarioMonitoringServiceUpdateScenarioMonitorProcedure,
			connect.WithSchema(scenarioMonitoringServiceMethods.ByName("UpdateScenarioMonitor")),
			connect.WithClientOptions(opts...),
		),
		updateScenarioMonitorV2: connect.NewClient[v1.UpdateScenarioMonitorV2Request, v1.UpdateScenarioMonitorV2Response](
			httpClient,
			baseURL+ScenarioMonitoringServiceUpdateScenarioMonitorV2Procedure,
			connect.WithSchema(scenarioMonitoringServiceMethods.ByName("UpdateScenarioMonitorV2")),
			connect.WithClientOptions(opts...),
		),
	}
}

// scenarioMonitoringServiceClient implements ScenarioMonitoringServiceClient.
type scenarioMonitoringServiceClient struct {
	createScenarioMonitor   *connect.Client[v1.CreateScenarioMonitorRequest, v1.CreateScenarioMonitorResponse]
	deleteScenarioMonitor   *connect.Client[v1.DeleteScenarioMonitorRequest, v1.DeleteScenarioMonitorResponse]
	getScenarioMonitor      *connect.Client[v1.GetScenarioMonitorRequest, v1.GetScenarioMonitorResponse]
	listScenarioMonitors    *connect.Client[v1.ListScenarioMonitorsRequest, v1.ListScenarioMonitorsResponse]
	updateScenarioMonitor   *connect.Client[v1.UpdateScenarioMonitorRequest, v1.UpdateScenarioMonitorResponse]
	updateScenarioMonitorV2 *connect.Client[v1.UpdateScenarioMonitorV2Request, v1.UpdateScenarioMonitorV2Response]
}

// CreateScenarioMonitor calls core.v1.ScenarioMonitoringService.CreateScenarioMonitor.
func (c *scenarioMonitoringServiceClient) CreateScenarioMonitor(ctx context.Context, req *connect.Request[v1.CreateScenarioMonitorRequest]) (*connect.Response[v1.CreateScenarioMonitorResponse], error) {
	return c.createScenarioMonitor.CallUnary(ctx, req)
}

// DeleteScenarioMonitor calls core.v1.ScenarioMonitoringService.DeleteScenarioMonitor.
func (c *scenarioMonitoringServiceClient) DeleteScenarioMonitor(ctx context.Context, req *connect.Request[v1.DeleteScenarioMonitorRequest]) (*connect.Response[v1.DeleteScenarioMonitorResponse], error) {
	return c.deleteScenarioMonitor.CallUnary(ctx, req)
}

// GetScenarioMonitor calls core.v1.ScenarioMonitoringService.GetScenarioMonitor.
func (c *scenarioMonitoringServiceClient) GetScenarioMonitor(ctx context.Context, req *connect.Request[v1.GetScenarioMonitorRequest]) (*connect.Response[v1.GetScenarioMonitorResponse], error) {
	return c.getScenarioMonitor.CallUnary(ctx, req)
}

// ListScenarioMonitors calls core.v1.ScenarioMonitoringService.ListScenarioMonitors.
func (c *scenarioMonitoringServiceClient) ListScenarioMonitors(ctx context.Context, req *connect.Request[v1.ListScenarioMonitorsRequest]) (*connect.Response[v1.ListScenarioMonitorsResponse], error) {
	return c.listScenarioMonitors.CallUnary(ctx, req)
}

// UpdateScenarioMonitor calls core.v1.ScenarioMonitoringService.UpdateScenarioMonitor.
func (c *scenarioMonitoringServiceClient) UpdateScenarioMonitor(ctx context.Context, req *connect.Request[v1.UpdateScenarioMonitorRequest]) (*connect.Response[v1.UpdateScenarioMonitorResponse], error) {
	return c.updateScenarioMonitor.CallUnary(ctx, req)
}

// UpdateScenarioMonitorV2 calls core.v1.ScenarioMonitoringService.UpdateScenarioMonitorV2.
func (c *scenarioMonitoringServiceClient) UpdateScenarioMonitorV2(ctx context.Context, req *connect.Request[v1.UpdateScenarioMonitorV2Request]) (*connect.Response[v1.UpdateScenarioMonitorV2Response], error) {
	return c.updateScenarioMonitorV2.CallUnary(ctx, req)
}

// ScenarioMonitoringServiceHandler is an implementation of the core.v1.ScenarioMonitoringService
// service.
type ScenarioMonitoringServiceHandler interface {
	// Add a scenario for LLM SSH Monitoring
	CreateScenarioMonitor(context.Context, *connect.Request[v1.CreateScenarioMonitorRequest]) (*connect.Response[v1.CreateScenarioMonitorResponse], error)
	// Delete a scenario from LLM SSH Monitoring
	DeleteScenarioMonitor(context.Context, *connect.Request[v1.DeleteScenarioMonitorRequest]) (*connect.Response[v1.DeleteScenarioMonitorResponse], error)
	// Retrieve all LLM session monitoring scenarios and their statuses
	GetScenarioMonitor(context.Context, *connect.Request[v1.GetScenarioMonitorRequest]) (*connect.Response[v1.GetScenarioMonitorResponse], error)
	ListScenarioMonitors(context.Context, *connect.Request[v1.ListScenarioMonitorsRequest]) (*connect.Response[v1.ListScenarioMonitorsResponse], error)
	// Update the status of a scenario used for LLM session monitoring
	UpdateScenarioMonitor(context.Context, *connect.Request[v1.UpdateScenarioMonitorRequest]) (*connect.Response[v1.UpdateScenarioMonitorResponse], error)
	// Update scenario monitor (full object replacement)
	//
	// Update a scenario monitor by sending the full object. All mutable fields are replaced.
	UpdateScenarioMonitorV2(context.Context, *connect.Request[v1.UpdateScenarioMonitorV2Request]) (*connect.Response[v1.UpdateScenarioMonitorV2Response], error)
}

// NewScenarioMonitoringServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewScenarioMonitoringServiceHandler(svc ScenarioMonitoringServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	scenarioMonitoringServiceMethods := v1.File_core_v1_scenario_monitoring_proto.Services().ByName("ScenarioMonitoringService").Methods()
	scenarioMonitoringServiceCreateScenarioMonitorHandler := connect.NewUnaryHandler(
		ScenarioMonitoringServiceCreateScenarioMonitorProcedure,
		svc.CreateScenarioMonitor,
		connect.WithSchema(scenarioMonitoringServiceMethods.ByName("CreateScenarioMonitor")),
		connect.WithHandlerOptions(opts...),
	)
	scenarioMonitoringServiceDeleteScenarioMonitorHandler := connect.NewUnaryHandler(
		ScenarioMonitoringServiceDeleteScenarioMonitorProcedure,
		svc.DeleteScenarioMonitor,
		connect.WithSchema(scenarioMonitoringServiceMethods.ByName("DeleteScenarioMonitor")),
		connect.WithHandlerOptions(opts...),
	)
	scenarioMonitoringServiceGetScenarioMonitorHandler := connect.NewUnaryHandler(
		ScenarioMonitoringServiceGetScenarioMonitorProcedure,
		svc.GetScenarioMonitor,
		connect.WithSchema(scenarioMonitoringServiceMethods.ByName("GetScenarioMonitor")),
		connect.WithHandlerOptions(opts...),
	)
	scenarioMonitoringServiceListScenarioMonitorsHandler := connect.NewUnaryHandler(
		ScenarioMonitoringServiceListScenarioMonitorsProcedure,
		svc.ListScenarioMonitors,
		connect.WithSchema(scenarioMonitoringServiceMethods.ByName("ListScenarioMonitors")),
		connect.WithHandlerOptions(opts...),
	)
	scenarioMonitoringServiceUpdateScenarioMonitorHandler := connect.NewUnaryHandler(
		ScenarioMonitoringServiceUpdateScenarioMonitorProcedure,
		svc.UpdateScenarioMonitor,
		connect.WithSchema(scenarioMonitoringServiceMethods.ByName("UpdateScenarioMonitor")),
		connect.WithHandlerOptions(opts...),
	)
	scenarioMonitoringServiceUpdateScenarioMonitorV2Handler := connect.NewUnaryHandler(
		ScenarioMonitoringServiceUpdateScenarioMonitorV2Procedure,
		svc.UpdateScenarioMonitorV2,
		connect.WithSchema(scenarioMonitoringServiceMethods.ByName("UpdateScenarioMonitorV2")),
		connect.WithHandlerOptions(opts...),
	)
	return "/core.v1.ScenarioMonitoringService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ScenarioMonitoringServiceCreateScenarioMonitorProcedure:
			scenarioMonitoringServiceCreateScenarioMonitorHandler.ServeHTTP(w, r)
		case ScenarioMonitoringServiceDeleteScenarioMonitorProcedure:
			scenarioMonitoringServiceDeleteScenarioMonitorHandler.ServeHTTP(w, r)
		case ScenarioMonitoringServiceGetScenarioMonitorProcedure:
			scenarioMonitoringServiceGetScenarioMonitorHandler.ServeHTTP(w, r)
		case ScenarioMonitoringServiceListScenarioMonitorsProcedure:
			scenarioMonitoringServiceListScenarioMonitorsHandler.ServeHTTP(w, r)
		case ScenarioMonitoringServiceUpdateScenarioMonitorProcedure:
			scenarioMonitoringServiceUpdateScenarioMonitorHandler.ServeHTTP(w, r)
		case ScenarioMonitoringServiceUpdateScenarioMonitorV2Procedure:
			scenarioMonitoringServiceUpdateScenarioMonitorV2Handler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedScenarioMonitoringServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedScenarioMonitoringServiceHandler struct{}

func (UnimplementedScenarioMonitoringServiceHandler) CreateScenarioMonitor(context.Context, *connect.Request[v1.CreateScenarioMonitorRequest]) (*connect.Response[v1.CreateScenarioMonitorResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("core.v1.ScenarioMonitoringService.CreateScenarioMonitor is not implemented"))
}

func (UnimplementedScenarioMonitoringServiceHandler) DeleteScenarioMonitor(context.Context, *connect.Request[v1.DeleteScenarioMonitorRequest]) (*connect.Response[v1.DeleteScenarioMonitorResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("core.v1.ScenarioMonitoringService.DeleteScenarioMonitor is not implemented"))
}

func (UnimplementedScenarioMonitoringServiceHandler) GetScenarioMonitor(context.Context, *connect.Request[v1.GetScenarioMonitorRequest]) (*connect.Response[v1.GetScenarioMonitorResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("core.v1.ScenarioMonitoringService.GetScenarioMonitor is not implemented"))
}

func (UnimplementedScenarioMonitoringServiceHandler) ListScenarioMonitors(context.Context, *connect.Request[v1.ListScenarioMonitorsRequest]) (*connect.Response[v1.ListScenarioMonitorsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("core.v1.ScenarioMonitoringService.ListScenarioMonitors is not implemented"))
}

func (UnimplementedScenarioMonitoringServiceHandler) UpdateScenarioMonitor(context.Context, *connect.Request[v1.UpdateScenarioMonitorRequest]) (*connect.Response[v1.UpdateScenarioMonitorResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("core.v1.ScenarioMonitoringService.UpdateScenarioMonitor is not implemented"))
}

func (UnimplementedScenarioMonitoringServiceHandler) UpdateScenarioMonitorV2(context.Context, *connect.Request[v1.UpdateScenarioMonitorV2Request]) (*connect.Response[v1.UpdateScenarioMonitorV2Response], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("core.v1.ScenarioMonitoringService.UpdateScenarioMonitorV2 is not implemented"))
}
