// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        (unknown)
// source: core/v1/approval.proto

package corev1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListApprovalRequestsStatus int32

const (
	ListApprovalRequestsStatus_LIST_APPROVAL_REQUESTS_STATUS_UNSPECIFIED ListApprovalRequestsStatus = 0
	ListApprovalRequestsStatus_LIST_APPROVAL_REQUESTS_STATUS_PENDING     ListApprovalRequestsStatus = 1
	ListApprovalRequestsStatus_LIST_APPROVAL_REQUESTS_STATUS_APPROVED    ListApprovalRequestsStatus = 2
	ListApprovalRequestsStatus_LIST_APPROVAL_REQUESTS_STATUS_REJECTED    ListApprovalRequestsStatus = 3
)

// Enum value maps for ListApprovalRequestsStatus.
var (
	ListApprovalRequestsStatus_name = map[int32]string{
		0: "LIST_APPROVAL_REQUESTS_STATUS_UNSPECIFIED",
		1: "LIST_APPROVAL_REQUESTS_STATUS_PENDING",
		2: "LIST_APPROVAL_REQUESTS_STATUS_APPROVED",
		3: "LIST_APPROVAL_REQUESTS_STATUS_REJECTED",
	}
	ListApprovalRequestsStatus_value = map[string]int32{
		"LIST_APPROVAL_REQUESTS_STATUS_UNSPECIFIED": 0,
		"LIST_APPROVAL_REQUESTS_STATUS_PENDING":     1,
		"LIST_APPROVAL_REQUESTS_STATUS_APPROVED":    2,
		"LIST_APPROVAL_REQUESTS_STATUS_REJECTED":    3,
	}
)

func (x ListApprovalRequestsStatus) Enum() *ListApprovalRequestsStatus {
	p := new(ListApprovalRequestsStatus)
	*p = x
	return p
}

func (x ListApprovalRequestsStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListApprovalRequestsStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_core_v1_approval_proto_enumTypes[0].Descriptor()
}

func (ListApprovalRequestsStatus) Type() protoreflect.EnumType {
	return &file_core_v1_approval_proto_enumTypes[0]
}

func (x ListApprovalRequestsStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListApprovalRequestsStatus.Descriptor instead.
func (ListApprovalRequestsStatus) EnumDescriptor() ([]byte, []int) {
	return file_core_v1_approval_proto_rawDescGZIP(), []int{0}
}

type UpdateApprovalRequestAction int32

const (
	UpdateApprovalRequestAction_UPDATE_APPROVAL_REQUEST_ACTION_UNSPECIFIED UpdateApprovalRequestAction = 0
	UpdateApprovalRequestAction_UPDATE_APPROVAL_REQUEST_ACTION_APPROVE     UpdateApprovalRequestAction = 1
	UpdateApprovalRequestAction_UPDATE_APPROVAL_REQUEST_ACTION_REJECT      UpdateApprovalRequestAction = 2
)

// Enum value maps for UpdateApprovalRequestAction.
var (
	UpdateApprovalRequestAction_name = map[int32]string{
		0: "UPDATE_APPROVAL_REQUEST_ACTION_UNSPECIFIED",
		1: "UPDATE_APPROVAL_REQUEST_ACTION_APPROVE",
		2: "UPDATE_APPROVAL_REQUEST_ACTION_REJECT",
	}
	UpdateApprovalRequestAction_value = map[string]int32{
		"UPDATE_APPROVAL_REQUEST_ACTION_UNSPECIFIED": 0,
		"UPDATE_APPROVAL_REQUEST_ACTION_APPROVE":     1,
		"UPDATE_APPROVAL_REQUEST_ACTION_REJECT":      2,
	}
)

func (x UpdateApprovalRequestAction) Enum() *UpdateApprovalRequestAction {
	p := new(UpdateApprovalRequestAction)
	*p = x
	return p
}

func (x UpdateApprovalRequestAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdateApprovalRequestAction) Descriptor() protoreflect.EnumDescriptor {
	return file_core_v1_approval_proto_enumTypes[1].Descriptor()
}

func (UpdateApprovalRequestAction) Type() protoreflect.EnumType {
	return &file_core_v1_approval_proto_enumTypes[1]
}

func (x UpdateApprovalRequestAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdateApprovalRequestAction.Descriptor instead.
func (UpdateApprovalRequestAction) EnumDescriptor() ([]byte, []int) {
	return file_core_v1_approval_proto_rawDescGZIP(), []int{1}
}

type ApprovalRequest struct {
	state             protoimpl.MessageState  `protogen:"open.v1"`
	Id                string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RequesterUserId   string                  `protobuf:"bytes,2,opt,name=requester_user_id,json=requesterUserId,proto3" json:"requester_user_id,omitempty"`
	RequesterEmail    string                  `protobuf:"bytes,3,opt,name=requester_email,json=requesterEmail,proto3" json:"requester_email,omitempty"`
	Payload           *ApprovalRequestPayload `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	Reason            string                  `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	Status            string                  `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt         *timestamppb.Timestamp  `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	PolicyId          string                  `protobuf:"bytes,8,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	DecisionUserId    string                  `protobuf:"bytes,9,opt,name=decision_user_id,json=decisionUserId,proto3" json:"decision_user_id,omitempty"`
	DecisionUserEmail string                  `protobuf:"bytes,10,opt,name=decision_user_email,json=decisionUserEmail,proto3" json:"decision_user_email,omitempty"`
	DecisionReason    string                  `protobuf:"bytes,11,opt,name=decision_reason,json=decisionReason,proto3" json:"decision_reason,omitempty"`
	DecidedAt         *timestamppb.Timestamp  `protobuf:"bytes,12,opt,name=decided_at,json=decidedAt,proto3" json:"decided_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ApprovalRequest) Reset() {
	*x = ApprovalRequest{}
	mi := &file_core_v1_approval_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalRequest) ProtoMessage() {}

func (x *ApprovalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_approval_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalRequest.ProtoReflect.Descriptor instead.
func (*ApprovalRequest) Descriptor() ([]byte, []int) {
	return file_core_v1_approval_proto_rawDescGZIP(), []int{0}
}

func (x *ApprovalRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ApprovalRequest) GetRequesterUserId() string {
	if x != nil {
		return x.RequesterUserId
	}
	return ""
}

func (x *ApprovalRequest) GetRequesterEmail() string {
	if x != nil {
		return x.RequesterEmail
	}
	return ""
}

func (x *ApprovalRequest) GetPayload() *ApprovalRequestPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ApprovalRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ApprovalRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApprovalRequest) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ApprovalRequest) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *ApprovalRequest) GetDecisionUserId() string {
	if x != nil {
		return x.DecisionUserId
	}
	return ""
}

func (x *ApprovalRequest) GetDecisionUserEmail() string {
	if x != nil {
		return x.DecisionUserEmail
	}
	return ""
}

func (x *ApprovalRequest) GetDecisionReason() string {
	if x != nil {
		return x.DecisionReason
	}
	return ""
}

func (x *ApprovalRequest) GetDecidedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DecidedAt
	}
	return nil
}

type ApprovalRequestPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*ApprovalRequestPayload_McpServerCreate
	//	*ApprovalRequestPayload_PolicySuspension
	//	*ApprovalRequestPayload_McpRegistryAccess
	//	*ApprovalRequestPayload_CustomPolicyAccess
	Kind          isApprovalRequestPayload_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovalRequestPayload) Reset() {
	*x = ApprovalRequestPayload{}
	mi := &file_core_v1_approval_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalRequestPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalRequestPayload) ProtoMessage() {}

func (x *ApprovalRequestPayload) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_approval_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalRequestPayload.ProtoReflect.Descriptor instead.
func (*ApprovalRequestPayload) Descriptor() ([]byte, []int) {
	return file_core_v1_approval_proto_rawDescGZIP(), []int{1}
}

func (x *ApprovalRequestPayload) GetKind() isApprovalRequestPayload_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *ApprovalRequestPayload) GetMcpServerCreate() *CreateMcpServerRequest {
	if x != nil {
		if x, ok := x.Kind.(*ApprovalRequestPayload_McpServerCreate); ok {
			return x.McpServerCreate
		}
	}
	return nil
}

func (x *ApprovalRequestPayload) GetPolicySuspension() *PolicySuspensionApprovalRequest {
	if x != nil {
		if x, ok := x.Kind.(*ApprovalRequestPayload_PolicySuspension); ok {
			return x.PolicySuspension
		}
	}
	return nil
}

func (x *ApprovalRequestPayload) GetMcpRegistryAccess() *McpRegistryAccessApprovalRequest {
	if x != nil {
		if x, ok := x.Kind.(*ApprovalRequestPayload_McpRegistryAccess); ok {
			return x.McpRegistryAccess
		}
	}
	return nil
}

func (x *ApprovalRequestPayload) GetCustomPolicyAccess() *CustomPolicyAccessApprovalRequest {
	if x != nil {
		if x, ok := x.Kind.(*ApprovalRequestPayload_CustomPolicyAccess); ok {
			return x.CustomPolicyAccess
		}
	}
	return nil
}

type isApprovalRequestPayload_Kind interface {
	isApprovalRequestPayload_Kind()
}

type ApprovalRequestPayload_McpServerCreate struct {
	McpServerCreate *CreateMcpServerRequest `protobuf:"bytes,1,opt,name=mcp_server_create,json=mcpServerCreate,proto3,oneof"`
}

type ApprovalRequestPayload_PolicySuspension struct {
	PolicySuspension *PolicySuspensionApprovalRequest `protobuf:"bytes,2,opt,name=policy_suspension,json=policySuspension,proto3,oneof"`
}

type ApprovalRequestPayload_McpRegistryAccess struct {
	McpRegistryAccess *McpRegistryAccessApprovalRequest `protobuf:"bytes,3,opt,name=mcp_registry_access,json=mcpRegistryAccess,proto3,oneof"`
}

type ApprovalRequestPayload_CustomPolicyAccess struct {
	CustomPolicyAccess *CustomPolicyAccessApprovalRequest `protobuf:"bytes,4,opt,name=custom_policy_access,json=customPolicyAccess,proto3,oneof"`
}

func (*ApprovalRequestPayload_McpServerCreate) isApprovalRequestPayload_Kind() {}

func (*ApprovalRequestPayload_PolicySuspension) isApprovalRequestPayload_Kind() {}

func (*ApprovalRequestPayload_McpRegistryAccess) isApprovalRequestPayload_Kind() {}

func (*ApprovalRequestPayload_CustomPolicyAccess) isApprovalRequestPayload_Kind() {}

type PolicySuspensionApprovalRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Duration:
	//
	//	*PolicySuspensionApprovalRequest_OneTime
	//	*PolicySuspensionApprovalRequest_TimeBound
	Duration      isPolicySuspensionApprovalRequest_Duration `protobuf_oneof:"duration"`
	Scope         *ApprovalAccessScope                       `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicySuspensionApprovalRequest) Reset() {
	*x = PolicySuspensionApprovalRequest{}
	mi := &file_core_v1_approval_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicySuspensionApprovalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicySuspensionApprovalRequest) ProtoMessage() {}

func (x *PolicySuspensionApprovalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_approval_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicySuspensionApprovalRequest.ProtoReflect.Descriptor instead.
func (*PolicySuspensionApprovalRequest) Descriptor() ([]byte, []int) {
	return file_core_v1_approval_proto_rawDescGZIP(), []int{2}
}

func (x *PolicySuspensionApprovalRequest) GetDuration() isPolicySuspensionApprovalRequest_Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *PolicySuspensionApprovalRequest) GetOneTime() *OneTimeApprovalAccess {
	if x != nil {
		if x, ok := x.Duration.(*PolicySuspensionApprovalRequest_OneTime); ok {
			return x.OneTime
		}
	}
	return nil
}

func (x *PolicySuspensionApprovalRequest) GetTimeBound() *TimeBoundApprovalAccess {
	if x != nil {
		if x, ok := x.Duration.(*PolicySuspensionApprovalRequest_TimeBound); ok {
			return x.TimeBound
		}
	}
	return nil
}

func (x *PolicySuspensionApprovalRequest) GetScope() *ApprovalAccessScope {
	if x != nil {
		return x.Scope
	}
	return nil
}

type isPolicySuspensionApprovalRequest_Duration interface {
	isPolicySuspensionApprovalRequest_Duration()
}

type PolicySuspensionApprovalRequest_OneTime struct {
	OneTime *OneTimeApprovalAccess `protobuf:"bytes,1,opt,name=one_time,json=oneTime,proto3,oneof"`
}

type PolicySuspensionApprovalRequest_TimeBound struct {
	TimeBound *TimeBoundApprovalAccess `protobuf:"bytes,2,opt,name=time_bound,json=timeBound,proto3,oneof"`
}

func (*PolicySuspensionApprovalRequest_OneTime) isPolicySuspensionApprovalRequest_Duration() {}

func (*PolicySuspensionApprovalRequest_TimeBound) isPolicySuspensionApprovalRequest_Duration() {}

type OneTimeApprovalAccess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OneTimeApprovalAccess) Reset() {
	*x = OneTimeApprovalAccess{}
	mi := &file_core_v1_approval_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneTimeApprovalAccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneTimeApprovalAccess) ProtoMessage() {}

func (x *OneTimeApprovalAccess) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_approval_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneTimeApprovalAccess.ProtoReflect.Descriptor instead.
func (*OneTimeApprovalAccess) Descriptor() ([]byte, []int) {
	return file_core_v1_approval_proto_rawDescGZIP(), []int{3}
}

type TimeBoundApprovalAccess struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ExpirationMinutes uint64                 `protobuf:"varint,1,opt,name=expiration_minutes,json=expirationMinutes,proto3" json:"expiration_minutes,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TimeBoundApprovalAccess) Reset() {
	*x = TimeBoundApprovalAccess{}
	mi := &file_core_v1_approval_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeBoundApprovalAccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeBoundApprovalAccess) ProtoMessage() {}

func (x *TimeBoundApprovalAccess) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_approval_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeBoundApprovalAccess.ProtoReflect.Descriptor instead.
func (*TimeBoundApprovalAccess) Descriptor() ([]byte, []int) {
	return file_core_v1_approval_proto_rawDescGZIP(), []int{4}
}

func (x *TimeBoundApprovalAccess) GetExpirationMinutes() uint64 {
	if x != nil {
		return x.ExpirationMinutes
	}
	return 0
}

type ApprovalAccessScope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*ApprovalAccessScope_ExactAction
	//	*ApprovalAccessScope_Tool
	//	*ApprovalAccessScope_Method
	//	*ApprovalAccessScope_Device
	//	*ApprovalAccessScope_Full
	Kind          isApprovalAccessScope_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovalAccessScope) Reset() {
	*x = ApprovalAccessScope{}
	mi := &file_core_v1_approval_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalAccessScope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalAccessScope) ProtoMessage() {}

func (x *ApprovalAccessScope) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_approval_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalAccessScope.ProtoReflect.Descriptor instead.
func (*ApprovalAccessScope) Descriptor() ([]byte, []int) {
	return file_core_v1_approval_proto_rawDescGZIP(), []int{5}
}

func (x *ApprovalAccessScope) GetKind() isApprovalAccessScope_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *ApprovalAccessScope) GetExactAction() *ExactActionApprovalScope {
	if x != nil {
		if x, ok := x.Kind.(*ApprovalAccessScope_ExactAction); ok {
			return x.ExactAction
		}
	}
	return nil
}

func (x *ApprovalAccessScope) GetTool() *ToolApprovalScope {
	if x != nil {
		if x, ok := x.Kind.(*ApprovalAccessScope_Tool); ok {
			return x.Tool
		}
	}
	return nil
}

func (x *ApprovalAccessScope) GetMethod() *MethodApprovalScope {
	if x != nil {
		if x, ok := x.Kind.(*ApprovalAccessScope_Method); ok {
			return x.Method
		}
	}
	return nil
}

func (x *ApprovalAccessScope) GetDevice() *DeviceApprovalScope {
	if x != nil {
		if x, ok := x.Kind.(*ApprovalAccessScope_Device); ok {
			return x.Device
		}
	}
	return nil
}

func (x *ApprovalAccessScope) GetFull() *FullApprovalScope {
	if x != nil {
		if x, ok := x.Kind.(*ApprovalAccessScope_Full); ok {
			return x.Full
		}
	}
	return nil
}

type isApprovalAccessScope_Kind interface {
	isApprovalAccessScope_Kind()
}

type ApprovalAccessScope_ExactAction struct {
	ExactAction *ExactActionApprovalScope `protobuf:"bytes,1,opt,name=exact_action,json=exactAction,proto3,oneof"`
}

type ApprovalAccessScope_Tool struct {
	Tool *ToolApprovalScope `protobuf:"bytes,2,opt,name=tool,proto3,oneof"`
}

type ApprovalAccessScope_Method struct {
	Method *MethodApprovalScope `protobuf:"bytes,3,opt,name=method,proto3,oneof"`
}

type ApprovalAccessScope_Device struct {
	Device *DeviceApprovalScope `protobuf:"bytes,4,opt,name=device,proto3,oneof"`
}

type ApprovalAccessScope_Full struct {
	Full *FullApprovalScope `protobuf:"bytes,5,opt,name=full,proto3,oneof"`
}

func (*ApprovalAccessScope_ExactAction) isApprovalAccessScope_Kind() {}

func (*ApprovalAccessScope_Tool) isApprovalAccessScope_Kind() {}

func (*ApprovalAccessScope_Method) isApprovalAccessScope_Kind() {}

func (*ApprovalAccessScope_Device) isApprovalAccessScope_Kind() {}

func (*ApprovalAccessScope_Full) isApprovalAccessScope_Kind() {}

type ExactActionApprovalScope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	McpMethod     string                 `protobuf:"bytes,1,opt,name=mcp_method,json=mcpMethod,proto3" json:"mcp_method,omitempty"`
	ToolName      string                 `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	ToolArguments *structpb.Struct       `protobuf:"bytes,3,opt,name=tool_arguments,json=toolArguments,proto3" json:"tool_arguments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExactActionApprovalScope) Reset() {
	*x = ExactActionApprovalScope{}
	mi := &file_core_v1_approval_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExactActionApprovalScope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExactActionApprovalScope) ProtoMessage() {}

func (x *ExactActionApprovalScope) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_approval_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExactActionApprovalScope.ProtoReflect.Descriptor instead.
func (*ExactActionApprovalScope) Descriptor() ([]byte, []int) {
	return file_core_v1_approval_proto_rawDescGZIP(), []int{6}
}

func (x *ExactActionApprovalScope) GetMcpMethod() string {
	if x != nil {
		return x.McpMethod
	}
	return ""
}

func (x *ExactActionApprovalScope) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ExactActionApprovalScope) GetToolArguments() *structpb.Struct {
	if x != nil {
		return x.ToolArguments
	}
	return nil
}

type ToolApprovalScope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	McpMethod     string                 `protobuf:"bytes,1,opt,name=mcp_method,json=mcpMethod,proto3" json:"mcp_method,omitempty"`
	ToolName      string                 `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolApprovalScope) Reset() {
	*x = ToolApprovalScope{}
	mi := &file_core_v1_approval_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolApprovalScope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolApprovalScope) ProtoMessage() {}

func (x *ToolApprovalScope) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_approval_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolApprovalScope.ProtoReflect.Descriptor instead.
func (*ToolApprovalScope) Descriptor() ([]byte, []int) {
	return file_core_v1_approval_proto_rawDescGZIP(), []int{7}
}

func (x *ToolApprovalScope) GetMcpMethod() string {
	if x != nil {
		return x.McpMethod
	}
	return ""
}

func (x *ToolApprovalScope) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

type MethodApprovalScope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	McpMethod     string                 `protobuf:"bytes,1,opt,name=mcp_method,json=mcpMethod,proto3" json:"mcp_method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MethodApprovalScope) Reset() {
	*x = MethodApprovalScope{}
	mi := &file_core_v1_approval_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MethodApprovalScope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodApprovalScope) ProtoMessage() {}

func (x *MethodApprovalScope) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_approval_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MethodApprovalScope.ProtoReflect.Descriptor instead.
func (*MethodApprovalScope) Descriptor() ([]byte, []int) {
	return file_core_v1_approval_proto_rawDescGZIP(), []int{8}
}

func (x *MethodApprovalScope) GetMcpMethod() string {
	if x != nil {
		return x.McpMethod
	}
	return ""
}

type DeviceApprovalScope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceName    string                 `protobuf:"bytes,1,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceApprovalScope) Reset() {
	*x = DeviceApprovalScope{}
	mi := &file_core_v1_approval_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceApprovalScope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceApprovalScope) ProtoMessage() {}

func (x *DeviceApprovalScope) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_approval_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceApprovalScope.ProtoReflect.Descriptor instead.
func (*DeviceApprovalScope) Descriptor() ([]byte, []int) {
	return file_core_v1_approval_proto_rawDescGZIP(), []int{9}
}

func (x *DeviceApprovalScope) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

type FullApprovalScope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FullApprovalScope) Reset() {
	*x = FullApprovalScope{}
	mi := &file_core_v1_approval_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FullApprovalScope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullApprovalScope) ProtoMessage() {}

func (x *FullApprovalScope) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_approval_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullApprovalScope.ProtoReflect.Descriptor instead.
func (*FullApprovalScope) Descriptor() ([]byte, []int) {
	return file_core_v1_approval_proto_rawDescGZIP(), []int{10}
}

type McpRegistryAccessApprovalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *McpRegistryAccessApprovalRequest) Reset() {
	*x = McpRegistryAccessApprovalRequest{}
	mi := &file_core_v1_approval_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *McpRegistryAccessApprovalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*McpRegistryAccessApprovalRequest) ProtoMessage() {}

func (x *McpRegistryAccessApprovalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_approval_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use McpRegistryAccessApprovalRequest.ProtoReflect.Descriptor instead.
func (*McpRegistryAccessApprovalRequest) Descriptor() ([]byte, []int) {
	return file_core_v1_approval_proto_rawDescGZIP(), []int{11}
}

func (x *McpRegistryAccessApprovalRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

type CustomPolicyAccessApprovalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         *ApprovalAccessScope   `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomPolicyAccessApprovalRequest) Reset() {
	*x = CustomPolicyAccessApprovalRequest{}
	mi := &file_core_v1_approval_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomPolicyAccessApprovalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomPolicyAccessApprovalRequest) ProtoMessage() {}

func (x *CustomPolicyAccessApprovalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_approval_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomPolicyAccessApprovalRequest.ProtoReflect.Descriptor instead.
func (*CustomPolicyAccessApprovalRequest) Descriptor() ([]byte, []int) {
	return file_core_v1_approval_proto_rawDescGZIP(), []int{12}
}

func (x *CustomPolicyAccessApprovalRequest) GetScope() *ApprovalAccessScope {
	if x != nil {
		return x.Scope
	}
	return nil
}

type ListApprovalRequestsRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Limit         int32                      `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                     `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Status        ListApprovalRequestsStatus `protobuf:"varint,3,opt,name=status,proto3,enum=core.v1.ListApprovalRequestsStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListApprovalRequestsRequest) Reset() {
	*x = ListApprovalRequestsRequest{}
	mi := &file_core_v1_approval_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListApprovalRequestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListApprovalRequestsRequest) ProtoMessage() {}

func (x *ListApprovalRequestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_approval_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListApprovalRequestsRequest.ProtoReflect.Descriptor instead.
func (*ListApprovalRequestsRequest) Descriptor() ([]byte, []int) {
	return file_core_v1_approval_proto_rawDescGZIP(), []int{13}
}

func (x *ListApprovalRequestsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListApprovalRequestsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListApprovalRequestsRequest) GetStatus() ListApprovalRequestsStatus {
	if x != nil {
		return x.Status
	}
	return ListApprovalRequestsStatus_LIST_APPROVAL_REQUESTS_STATUS_UNSPECIFIED
}

type ListApprovalRequestsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*ApprovalRequest     `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	ListMetadata  *ListMetadata          `protobuf:"bytes,2,opt,name=list_metadata,json=listMetadata,proto3" json:"list_metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListApprovalRequestsResponse) Reset() {
	*x = ListApprovalRequestsResponse{}
	mi := &file_core_v1_approval_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListApprovalRequestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListApprovalRequestsResponse) ProtoMessage() {}

func (x *ListApprovalRequestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_approval_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListApprovalRequestsResponse.ProtoReflect.Descriptor instead.
func (*ListApprovalRequestsResponse) Descriptor() ([]byte, []int) {
	return file_core_v1_approval_proto_rawDescGZIP(), []int{14}
}

func (x *ListApprovalRequestsResponse) GetRequests() []*ApprovalRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

func (x *ListApprovalRequestsResponse) GetListMetadata() *ListMetadata {
	if x != nil {
		return x.ListMetadata
	}
	return nil
}

type UpdateApprovalRequestRequest struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Id            string                      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Action        UpdateApprovalRequestAction `protobuf:"varint,2,opt,name=action,proto3,enum=core.v1.UpdateApprovalRequestAction" json:"action,omitempty"`
	Reason        string                      `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateApprovalRequestRequest) Reset() {
	*x = UpdateApprovalRequestRequest{}
	mi := &file_core_v1_approval_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateApprovalRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateApprovalRequestRequest) ProtoMessage() {}

func (x *UpdateApprovalRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_approval_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateApprovalRequestRequest.ProtoReflect.Descriptor instead.
func (*UpdateApprovalRequestRequest) Descriptor() ([]byte, []int) {
	return file_core_v1_approval_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateApprovalRequestRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateApprovalRequestRequest) GetAction() UpdateApprovalRequestAction {
	if x != nil {
		return x.Action
	}
	return UpdateApprovalRequestAction_UPDATE_APPROVAL_REQUEST_ACTION_UNSPECIFIED
}

func (x *UpdateApprovalRequestRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type UpdateApprovalRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       *ApprovalRequest       `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateApprovalRequestResponse) Reset() {
	*x = UpdateApprovalRequestResponse{}
	mi := &file_core_v1_approval_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateApprovalRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateApprovalRequestResponse) ProtoMessage() {}

func (x *UpdateApprovalRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_approval_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateApprovalRequestResponse.ProtoReflect.Descriptor instead.
func (*UpdateApprovalRequestResponse) Descriptor() ([]byte, []int) {
	return file_core_v1_approval_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateApprovalRequestResponse) GetRequest() *ApprovalRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type ListAccessRequestsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccessRequestsRequest) Reset() {
	*x = ListAccessRequestsRequest{}
	mi := &file_core_v1_approval_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccessRequestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccessRequestsRequest) ProtoMessage() {}

func (x *ListAccessRequestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_approval_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccessRequestsRequest.ProtoReflect.Descriptor instead.
func (*ListAccessRequestsRequest) Descriptor() ([]byte, []int) {
	return file_core_v1_approval_proto_rawDescGZIP(), []int{17}
}

func (x *ListAccessRequestsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListAccessRequestsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type ListAccessRequestsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*UserAccessRequest   `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	ListMetadata  *ListMetadata          `protobuf:"bytes,2,opt,name=list_metadata,json=listMetadata,proto3" json:"list_metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccessRequestsResponse) Reset() {
	*x = ListAccessRequestsResponse{}
	mi := &file_core_v1_approval_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccessRequestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccessRequestsResponse) ProtoMessage() {}

func (x *ListAccessRequestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_approval_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccessRequestsResponse.ProtoReflect.Descriptor instead.
func (*ListAccessRequestsResponse) Descriptor() ([]byte, []int) {
	return file_core_v1_approval_proto_rawDescGZIP(), []int{18}
}

func (x *ListAccessRequestsResponse) GetRequests() []*UserAccessRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

func (x *ListAccessRequestsResponse) GetListMetadata() *ListMetadata {
	if x != nil {
		return x.ListMetadata
	}
	return nil
}

type UserAccessRequest struct {
	state             protoimpl.MessageState    `protogen:"open.v1"`
	Id                string                    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Payload           *UserAccessRequestPayload `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Reason            string                    `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Status            string                    `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt         *timestamppb.Timestamp    `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	DecisionUserId    string                    `protobuf:"bytes,6,opt,name=decision_user_id,json=decisionUserId,proto3" json:"decision_user_id,omitempty"`
	DecisionUserEmail string                    `protobuf:"bytes,7,opt,name=decision_user_email,json=decisionUserEmail,proto3" json:"decision_user_email,omitempty"`
	DecisionReason    string                    `protobuf:"bytes,8,opt,name=decision_reason,json=decisionReason,proto3" json:"decision_reason,omitempty"`
	DecidedAt         *timestamppb.Timestamp    `protobuf:"bytes,9,opt,name=decided_at,json=decidedAt,proto3" json:"decided_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UserAccessRequest) Reset() {
	*x = UserAccessRequest{}
	mi := &file_core_v1_approval_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAccessRequest) ProtoMessage() {}

func (x *UserAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_approval_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAccessRequest.ProtoReflect.Descriptor instead.
func (*UserAccessRequest) Descriptor() ([]byte, []int) {
	return file_core_v1_approval_proto_rawDescGZIP(), []int{19}
}

func (x *UserAccessRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserAccessRequest) GetPayload() *UserAccessRequestPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *UserAccessRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *UserAccessRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UserAccessRequest) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UserAccessRequest) GetDecisionUserId() string {
	if x != nil {
		return x.DecisionUserId
	}
	return ""
}

func (x *UserAccessRequest) GetDecisionUserEmail() string {
	if x != nil {
		return x.DecisionUserEmail
	}
	return ""
}

func (x *UserAccessRequest) GetDecisionReason() string {
	if x != nil {
		return x.DecisionReason
	}
	return ""
}

func (x *UserAccessRequest) GetDecidedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DecidedAt
	}
	return nil
}

type UserAccessRequestPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*UserAccessRequestPayload_McpServerCreate
	//	*UserAccessRequestPayload_PolicySuspension
	//	*UserAccessRequestPayload_McpRegistryAccess
	//	*UserAccessRequestPayload_CustomPolicyAccess
	Kind          isUserAccessRequestPayload_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAccessRequestPayload) Reset() {
	*x = UserAccessRequestPayload{}
	mi := &file_core_v1_approval_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAccessRequestPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAccessRequestPayload) ProtoMessage() {}

func (x *UserAccessRequestPayload) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_approval_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAccessRequestPayload.ProtoReflect.Descriptor instead.
func (*UserAccessRequestPayload) Descriptor() ([]byte, []int) {
	return file_core_v1_approval_proto_rawDescGZIP(), []int{20}
}

func (x *UserAccessRequestPayload) GetKind() isUserAccessRequestPayload_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *UserAccessRequestPayload) GetMcpServerCreate() *UserMcpServerCreate {
	if x != nil {
		if x, ok := x.Kind.(*UserAccessRequestPayload_McpServerCreate); ok {
			return x.McpServerCreate
		}
	}
	return nil
}

func (x *UserAccessRequestPayload) GetPolicySuspension() *UserPolicySuspension {
	if x != nil {
		if x, ok := x.Kind.(*UserAccessRequestPayload_PolicySuspension); ok {
			return x.PolicySuspension
		}
	}
	return nil
}

func (x *UserAccessRequestPayload) GetMcpRegistryAccess() *UserMcpRegistryAccess {
	if x != nil {
		if x, ok := x.Kind.(*UserAccessRequestPayload_McpRegistryAccess); ok {
			return x.McpRegistryAccess
		}
	}
	return nil
}

func (x *UserAccessRequestPayload) GetCustomPolicyAccess() *UserCustomPolicyAccess {
	if x != nil {
		if x, ok := x.Kind.(*UserAccessRequestPayload_CustomPolicyAccess); ok {
			return x.CustomPolicyAccess
		}
	}
	return nil
}

type isUserAccessRequestPayload_Kind interface {
	isUserAccessRequestPayload_Kind()
}

type UserAccessRequestPayload_McpServerCreate struct {
	McpServerCreate *UserMcpServerCreate `protobuf:"bytes,1,opt,name=mcp_server_create,json=mcpServerCreate,proto3,oneof"`
}

type UserAccessRequestPayload_PolicySuspension struct {
	PolicySuspension *UserPolicySuspension `protobuf:"bytes,2,opt,name=policy_suspension,json=policySuspension,proto3,oneof"`
}

type UserAccessRequestPayload_McpRegistryAccess struct {
	McpRegistryAccess *UserMcpRegistryAccess `protobuf:"bytes,3,opt,name=mcp_registry_access,json=mcpRegistryAccess,proto3,oneof"`
}

type UserAccessRequestPayload_CustomPolicyAccess struct {
	CustomPolicyAccess *UserCustomPolicyAccess `protobuf:"bytes,4,opt,name=custom_policy_access,json=customPolicyAccess,proto3,oneof"`
}

func (*UserAccessRequestPayload_McpServerCreate) isUserAccessRequestPayload_Kind() {}

func (*UserAccessRequestPayload_PolicySuspension) isUserAccessRequestPayload_Kind() {}

func (*UserAccessRequestPayload_McpRegistryAccess) isUserAccessRequestPayload_Kind() {}

func (*UserAccessRequestPayload_CustomPolicyAccess) isUserAccessRequestPayload_Kind() {}

type UserMcpServerCreate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserMcpServerCreate) Reset() {
	*x = UserMcpServerCreate{}
	mi := &file_core_v1_approval_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserMcpServerCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMcpServerCreate) ProtoMessage() {}

func (x *UserMcpServerCreate) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_approval_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMcpServerCreate.ProtoReflect.Descriptor instead.
func (*UserMcpServerCreate) Descriptor() ([]byte, []int) {
	return file_core_v1_approval_proto_rawDescGZIP(), []int{21}
}

func (x *UserMcpServerCreate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserMcpServerCreate) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type UserPolicySuspension struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Duration:
	//
	//	*UserPolicySuspension_OneTime
	//	*UserPolicySuspension_TimeBound
	Duration      isUserPolicySuspension_Duration `protobuf_oneof:"duration"`
	Scope         *UserApprovalAccessScope        `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPolicySuspension) Reset() {
	*x = UserPolicySuspension{}
	mi := &file_core_v1_approval_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPolicySuspension) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPolicySuspension) ProtoMessage() {}

func (x *UserPolicySuspension) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_approval_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPolicySuspension.ProtoReflect.Descriptor instead.
func (*UserPolicySuspension) Descriptor() ([]byte, []int) {
	return file_core_v1_approval_proto_rawDescGZIP(), []int{22}
}

func (x *UserPolicySuspension) GetDuration() isUserPolicySuspension_Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *UserPolicySuspension) GetOneTime() *UserOneTimeAccess {
	if x != nil {
		if x, ok := x.Duration.(*UserPolicySuspension_OneTime); ok {
			return x.OneTime
		}
	}
	return nil
}

func (x *UserPolicySuspension) GetTimeBound() *UserTimeBoundAccess {
	if x != nil {
		if x, ok := x.Duration.(*UserPolicySuspension_TimeBound); ok {
			return x.TimeBound
		}
	}
	return nil
}

func (x *UserPolicySuspension) GetScope() *UserApprovalAccessScope {
	if x != nil {
		return x.Scope
	}
	return nil
}

type isUserPolicySuspension_Duration interface {
	isUserPolicySuspension_Duration()
}

type UserPolicySuspension_OneTime struct {
	OneTime *UserOneTimeAccess `protobuf:"bytes,1,opt,name=one_time,json=oneTime,proto3,oneof"`
}

type UserPolicySuspension_TimeBound struct {
	TimeBound *UserTimeBoundAccess `protobuf:"bytes,2,opt,name=time_bound,json=timeBound,proto3,oneof"`
}

func (*UserPolicySuspension_OneTime) isUserPolicySuspension_Duration() {}

func (*UserPolicySuspension_TimeBound) isUserPolicySuspension_Duration() {}

type UserOneTimeAccess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserOneTimeAccess) Reset() {
	*x = UserOneTimeAccess{}
	mi := &file_core_v1_approval_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserOneTimeAccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOneTimeAccess) ProtoMessage() {}

func (x *UserOneTimeAccess) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_approval_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOneTimeAccess.ProtoReflect.Descriptor instead.
func (*UserOneTimeAccess) Descriptor() ([]byte, []int) {
	return file_core_v1_approval_proto_rawDescGZIP(), []int{23}
}

type UserTimeBoundAccess struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ExpirationMinutes uint64                 `protobuf:"varint,1,opt,name=expiration_minutes,json=expirationMinutes,proto3" json:"expiration_minutes,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UserTimeBoundAccess) Reset() {
	*x = UserTimeBoundAccess{}
	mi := &file_core_v1_approval_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserTimeBoundAccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTimeBoundAccess) ProtoMessage() {}

func (x *UserTimeBoundAccess) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_approval_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTimeBoundAccess.ProtoReflect.Descriptor instead.
func (*UserTimeBoundAccess) Descriptor() ([]byte, []int) {
	return file_core_v1_approval_proto_rawDescGZIP(), []int{24}
}

func (x *UserTimeBoundAccess) GetExpirationMinutes() uint64 {
	if x != nil {
		return x.ExpirationMinutes
	}
	return 0
}

type UserExactActionScope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	McpMethod     string                 `protobuf:"bytes,1,opt,name=mcp_method,json=mcpMethod,proto3" json:"mcp_method,omitempty"`
	ToolName      string                 `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	ToolArguments *structpb.Struct       `protobuf:"bytes,3,opt,name=tool_arguments,json=toolArguments,proto3" json:"tool_arguments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserExactActionScope) Reset() {
	*x = UserExactActionScope{}
	mi := &file_core_v1_approval_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserExactActionScope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserExactActionScope) ProtoMessage() {}

func (x *UserExactActionScope) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_approval_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserExactActionScope.ProtoReflect.Descriptor instead.
func (*UserExactActionScope) Descriptor() ([]byte, []int) {
	return file_core_v1_approval_proto_rawDescGZIP(), []int{25}
}

func (x *UserExactActionScope) GetMcpMethod() string {
	if x != nil {
		return x.McpMethod
	}
	return ""
}

func (x *UserExactActionScope) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *UserExactActionScope) GetToolArguments() *structpb.Struct {
	if x != nil {
		return x.ToolArguments
	}
	return nil
}

type UserApprovalAccessScope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*UserApprovalAccessScope_ExactAction
	//	*UserApprovalAccessScope_Full
	Kind          isUserApprovalAccessScope_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserApprovalAccessScope) Reset() {
	*x = UserApprovalAccessScope{}
	mi := &file_core_v1_approval_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserApprovalAccessScope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserApprovalAccessScope) ProtoMessage() {}

func (x *UserApprovalAccessScope) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_approval_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserApprovalAccessScope.ProtoReflect.Descriptor instead.
func (*UserApprovalAccessScope) Descriptor() ([]byte, []int) {
	return file_core_v1_approval_proto_rawDescGZIP(), []int{26}
}

func (x *UserApprovalAccessScope) GetKind() isUserApprovalAccessScope_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *UserApprovalAccessScope) GetExactAction() *UserExactActionScope {
	if x != nil {
		if x, ok := x.Kind.(*UserApprovalAccessScope_ExactAction); ok {
			return x.ExactAction
		}
	}
	return nil
}

func (x *UserApprovalAccessScope) GetFull() *UserFullPolicyScope {
	if x != nil {
		if x, ok := x.Kind.(*UserApprovalAccessScope_Full); ok {
			return x.Full
		}
	}
	return nil
}

type isUserApprovalAccessScope_Kind interface {
	isUserApprovalAccessScope_Kind()
}

type UserApprovalAccessScope_ExactAction struct {
	ExactAction *UserExactActionScope `protobuf:"bytes,1,opt,name=exact_action,json=exactAction,proto3,oneof"`
}

type UserApprovalAccessScope_Full struct {
	Full *UserFullPolicyScope `protobuf:"bytes,2,opt,name=full,proto3,oneof"`
}

func (*UserApprovalAccessScope_ExactAction) isUserApprovalAccessScope_Kind() {}

func (*UserApprovalAccessScope_Full) isUserApprovalAccessScope_Kind() {}

type UserFullPolicyScope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserFullPolicyScope) Reset() {
	*x = UserFullPolicyScope{}
	mi := &file_core_v1_approval_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserFullPolicyScope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFullPolicyScope) ProtoMessage() {}

func (x *UserFullPolicyScope) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_approval_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFullPolicyScope.ProtoReflect.Descriptor instead.
func (*UserFullPolicyScope) Descriptor() ([]byte, []int) {
	return file_core_v1_approval_proto_rawDescGZIP(), []int{27}
}

type UserMcpRegistryAccess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserMcpRegistryAccess) Reset() {
	*x = UserMcpRegistryAccess{}
	mi := &file_core_v1_approval_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserMcpRegistryAccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMcpRegistryAccess) ProtoMessage() {}

func (x *UserMcpRegistryAccess) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_approval_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMcpRegistryAccess.ProtoReflect.Descriptor instead.
func (*UserMcpRegistryAccess) Descriptor() ([]byte, []int) {
	return file_core_v1_approval_proto_rawDescGZIP(), []int{28}
}

func (x *UserMcpRegistryAccess) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

type UserCustomPolicyAccess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         *UserExactActionScope  `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCustomPolicyAccess) Reset() {
	*x = UserCustomPolicyAccess{}
	mi := &file_core_v1_approval_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCustomPolicyAccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCustomPolicyAccess) ProtoMessage() {}

func (x *UserCustomPolicyAccess) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_approval_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCustomPolicyAccess.ProtoReflect.Descriptor instead.
func (*UserCustomPolicyAccess) Descriptor() ([]byte, []int) {
	return file_core_v1_approval_proto_rawDescGZIP(), []int{29}
}

func (x *UserCustomPolicyAccess) GetScope() *UserExactActionScope {
	if x != nil {
		return x.Scope
	}
	return nil
}

type CreateAccessRequestRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Reason        string                    `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	PolicyId      string                    `protobuf:"bytes,2,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	Payload       *UserAccessRequestPayload `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccessRequestRequest) Reset() {
	*x = CreateAccessRequestRequest{}
	mi := &file_core_v1_approval_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccessRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccessRequestRequest) ProtoMessage() {}

func (x *CreateAccessRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_approval_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccessRequestRequest.ProtoReflect.Descriptor instead.
func (*CreateAccessRequestRequest) Descriptor() ([]byte, []int) {
	return file_core_v1_approval_proto_rawDescGZIP(), []int{30}
}

func (x *CreateAccessRequestRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CreateAccessRequestRequest) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *CreateAccessRequestRequest) GetPayload() *UserAccessRequestPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type CreateAccessRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccessRequestResponse) Reset() {
	*x = CreateAccessRequestResponse{}
	mi := &file_core_v1_approval_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccessRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccessRequestResponse) ProtoMessage() {}

func (x *CreateAccessRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_approval_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccessRequestResponse.ProtoReflect.Descriptor instead.
func (*CreateAccessRequestResponse) Descriptor() ([]byte, []int) {
	return file_core_v1_approval_proto_rawDescGZIP(), []int{31}
}

var File_core_v1_approval_proto protoreflect.FileDescriptor

const file_core_v1_approval_proto_rawDesc = "" +
	"\n" +
	"\x16core/v1/approval.proto\x12\acore.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1bcore/v1/list_metadata.proto\x1a\x11core/v1/mcp.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf7\x03\n" +
	"\x0fApprovalRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12*\n" +
	"\x11requester_user_id\x18\x02 \x01(\tR\x0frequesterUserId\x12'\n" +
	"\x0frequester_email\x18\x03 \x01(\tR\x0erequesterEmail\x129\n" +
	"\apayload\x18\x04 \x01(\v2\x1f.core.v1.ApprovalRequestPayloadR\apayload\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1b\n" +
	"\tpolicy_id\x18\b \x01(\tR\bpolicyId\x12(\n" +
	"\x10decision_user_id\x18\t \x01(\tR\x0edecisionUserId\x12.\n" +
	"\x13decision_user_email\x18\n" +
	" \x01(\tR\x11decisionUserEmail\x12'\n" +
	"\x0fdecision_reason\x18\v \x01(\tR\x0edecisionReason\x129\n" +
	"\n" +
	"decided_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tdecidedAt\"\x8c\x03\n" +
	"\x16ApprovalRequestPayload\x12M\n" +
	"\x11mcp_server_create\x18\x01 \x01(\v2\x1f.core.v1.CreateMcpServerRequestH\x00R\x0fmcpServerCreate\x12W\n" +
	"\x11policy_suspension\x18\x02 \x01(\v2(.core.v1.PolicySuspensionApprovalRequestH\x00R\x10policySuspension\x12[\n" +
	"\x13mcp_registry_access\x18\x03 \x01(\v2).core.v1.McpRegistryAccessApprovalRequestH\x00R\x11mcpRegistryAccess\x12^\n" +
	"\x14custom_policy_access\x18\x04 \x01(\v2*.core.v1.CustomPolicyAccessApprovalRequestH\x00R\x12customPolicyAccessB\r\n" +
	"\x04kind\x12\x05\xbaH\x02\b\x01\"\xf0\x01\n" +
	"\x1fPolicySuspensionApprovalRequest\x12;\n" +
	"\bone_time\x18\x01 \x01(\v2\x1e.core.v1.OneTimeApprovalAccessH\x00R\aoneTime\x12A\n" +
	"\n" +
	"time_bound\x18\x02 \x01(\v2 .core.v1.TimeBoundApprovalAccessH\x00R\ttimeBound\x12:\n" +
	"\x05scope\x18\x03 \x01(\v2\x1c.core.v1.ApprovalAccessScopeB\x06\xbaH\x03\xc8\x01\x01R\x05scopeB\x11\n" +
	"\bduration\x12\x05\xbaH\x02\b\x01\"\x17\n" +
	"\x15OneTimeApprovalAccess\"Q\n" +
	"\x17TimeBoundApprovalAccess\x126\n" +
	"\x12expiration_minutes\x18\x01 \x01(\x04B\a\xbaH\x042\x02 \x00R\x11expirationMinutes\"\xc0\x02\n" +
	"\x13ApprovalAccessScope\x12F\n" +
	"\fexact_action\x18\x01 \x01(\v2!.core.v1.ExactActionApprovalScopeH\x00R\vexactAction\x120\n" +
	"\x04tool\x18\x02 \x01(\v2\x1a.core.v1.ToolApprovalScopeH\x00R\x04tool\x126\n" +
	"\x06method\x18\x03 \x01(\v2\x1c.core.v1.MethodApprovalScopeH\x00R\x06method\x126\n" +
	"\x06device\x18\x04 \x01(\v2\x1c.core.v1.DeviceApprovalScopeH\x00R\x06device\x120\n" +
	"\x04full\x18\x05 \x01(\v2\x1a.core.v1.FullApprovalScopeH\x00R\x04fullB\r\n" +
	"\x04kind\x12\x05\xbaH\x02\b\x01\"\x9f\x01\n" +
	"\x18ExactActionApprovalScope\x12&\n" +
	"\n" +
	"mcp_method\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tmcpMethod\x12\x1b\n" +
	"\ttool_name\x18\x02 \x01(\tR\btoolName\x12>\n" +
	"\x0etool_arguments\x18\x03 \x01(\v2\x17.google.protobuf.StructR\rtoolArguments\"a\n" +
	"\x11ToolApprovalScope\x12&\n" +
	"\n" +
	"mcp_method\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tmcpMethod\x12$\n" +
	"\ttool_name\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\btoolName\"=\n" +
	"\x13MethodApprovalScope\x12&\n" +
	"\n" +
	"mcp_method\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tmcpMethod\"?\n" +
	"\x13DeviceApprovalScope\x12(\n" +
	"\vdevice_name\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\n" +
	"deviceName\"\x13\n" +
	"\x11FullApprovalScope\"L\n" +
	" McpRegistryAccessApprovalRequest\x12(\n" +
	"\vresource_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\n" +
	"resourceId\"_\n" +
	"!CustomPolicyAccessApprovalRequest\x12:\n" +
	"\x05scope\x18\x01 \x01(\v2\x1c.core.v1.ApprovalAccessScopeB\x06\xbaH\x03\xc8\x01\x01R\x05scope\"\x9e\x01\n" +
	"\x1bListApprovalRequestsRequest\x12 \n" +
	"\x05limit\x18\x01 \x01(\x05B\n" +
	"\xbaH\a\x1a\x05\x18\xf4\x03 \x00R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\x12E\n" +
	"\x06status\x18\x03 \x01(\x0e2#.core.v1.ListApprovalRequestsStatusB\b\xbaH\x05\x82\x01\x02\x10\x01R\x06status\"\x90\x01\n" +
	"\x1cListApprovalRequestsResponse\x124\n" +
	"\brequests\x18\x01 \x03(\v2\x18.core.v1.ApprovalRequestR\brequests\x12:\n" +
	"\rlist_metadata\x18\x02 \x01(\v2\x15.core.v1.ListMetadataR\flistMetadata\"\xa1\x01\n" +
	"\x1cUpdateApprovalRequestRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x02id\x12F\n" +
	"\x06action\x18\x02 \x01(\x0e2$.core.v1.UpdateApprovalRequestActionB\b\xbaH\x05\x82\x01\x02\x10\x01R\x06action\x12 \n" +
	"\x06reason\x18\x03 \x01(\tB\b\xbaH\x05r\x03\x18\xa0\x1fR\x06reason\"S\n" +
	"\x1dUpdateApprovalRequestResponse\x122\n" +
	"\arequest\x18\x01 \x01(\v2\x18.core.v1.ApprovalRequestR\arequest\"U\n" +
	"\x19ListAccessRequestsRequest\x12 \n" +
	"\x05limit\x18\x01 \x01(\x05B\n" +
	"\xbaH\a\x1a\x05\x18\xf4\x03 \x00R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\"\x90\x01\n" +
	"\x1aListAccessRequestsResponse\x126\n" +
	"\brequests\x18\x01 \x03(\v2\x1a.core.v1.UserAccessRequestR\brequests\x12:\n" +
	"\rlist_metadata\x18\x02 \x01(\v2\x15.core.v1.ListMetadataR\flistMetadata\"\x89\x03\n" +
	"\x11UserAccessRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12;\n" +
	"\apayload\x18\x02 \x01(\v2!.core.v1.UserAccessRequestPayloadR\apayload\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12(\n" +
	"\x10decision_user_id\x18\x06 \x01(\tR\x0edecisionUserId\x12.\n" +
	"\x13decision_user_email\x18\a \x01(\tR\x11decisionUserEmail\x12'\n" +
	"\x0fdecision_reason\x18\b \x01(\tR\x0edecisionReason\x129\n" +
	"\n" +
	"decided_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tdecidedAt\"\xea\x02\n" +
	"\x18UserAccessRequestPayload\x12J\n" +
	"\x11mcp_server_create\x18\x01 \x01(\v2\x1c.core.v1.UserMcpServerCreateH\x00R\x0fmcpServerCreate\x12L\n" +
	"\x11policy_suspension\x18\x02 \x01(\v2\x1d.core.v1.UserPolicySuspensionH\x00R\x10policySuspension\x12P\n" +
	"\x13mcp_registry_access\x18\x03 \x01(\v2\x1e.core.v1.UserMcpRegistryAccessH\x00R\x11mcpRegistryAccess\x12S\n" +
	"\x14custom_policy_access\x18\x04 \x01(\v2\x1f.core.v1.UserCustomPolicyAccessH\x00R\x12customPolicyAccessB\r\n" +
	"\x04kind\x12\x05\xbaH\x02\b\x01\"M\n" +
	"\x13UserMcpServerCreate\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04name\x12\x19\n" +
	"\x03url\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x03url\"\xe1\x01\n" +
	"\x14UserPolicySuspension\x127\n" +
	"\bone_time\x18\x01 \x01(\v2\x1a.core.v1.UserOneTimeAccessH\x00R\aoneTime\x12=\n" +
	"\n" +
	"time_bound\x18\x02 \x01(\v2\x1c.core.v1.UserTimeBoundAccessH\x00R\ttimeBound\x12>\n" +
	"\x05scope\x18\x03 \x01(\v2 .core.v1.UserApprovalAccessScopeB\x06\xbaH\x03\xc8\x01\x01R\x05scopeB\x11\n" +
	"\bduration\x12\x05\xbaH\x02\b\x01\"\x13\n" +
	"\x11UserOneTimeAccess\"M\n" +
	"\x13UserTimeBoundAccess\x126\n" +
	"\x12expiration_minutes\x18\x01 \x01(\x04B\a\xbaH\x042\x02 \x00R\x11expirationMinutes\"\x9b\x01\n" +
	"\x14UserExactActionScope\x12&\n" +
	"\n" +
	"mcp_method\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tmcpMethod\x12\x1b\n" +
	"\ttool_name\x18\x02 \x01(\tR\btoolName\x12>\n" +
	"\x0etool_arguments\x18\x03 \x01(\v2\x17.google.protobuf.StructR\rtoolArguments\"\xa0\x01\n" +
	"\x17UserApprovalAccessScope\x12B\n" +
	"\fexact_action\x18\x01 \x01(\v2\x1d.core.v1.UserExactActionScopeH\x00R\vexactAction\x122\n" +
	"\x04full\x18\x02 \x01(\v2\x1c.core.v1.UserFullPolicyScopeH\x00R\x04fullB\r\n" +
	"\x04kind\x12\x05\xbaH\x02\b\x01\"\x15\n" +
	"\x13UserFullPolicyScope\"A\n" +
	"\x15UserMcpRegistryAccess\x12(\n" +
	"\vresource_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\n" +
	"resourceId\"U\n" +
	"\x16UserCustomPolicyAccess\x12;\n" +
	"\x05scope\x18\x01 \x01(\v2\x1d.core.v1.UserExactActionScopeB\x06\xbaH\x03\xc8\x01\x01R\x05scope\"\xa0\x01\n" +
	"\x1aCreateAccessRequestRequest\x12 \n" +
	"\x06reason\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x18\xa0\x1fR\x06reason\x12\x1b\n" +
	"\tpolicy_id\x18\x02 \x01(\tR\bpolicyId\x12C\n" +
	"\apayload\x18\x03 \x01(\v2!.core.v1.UserAccessRequestPayloadB\x06\xbaH\x03\xc8\x01\x01R\apayload\"\x1d\n" +
	"\x1bCreateAccessRequestResponse*\xce\x01\n" +
	"\x1aListApprovalRequestsStatus\x12-\n" +
	")LIST_APPROVAL_REQUESTS_STATUS_UNSPECIFIED\x10\x00\x12)\n" +
	"%LIST_APPROVAL_REQUESTS_STATUS_PENDING\x10\x01\x12*\n" +
	"&LIST_APPROVAL_REQUESTS_STATUS_APPROVED\x10\x02\x12*\n" +
	"&LIST_APPROVAL_REQUESTS_STATUS_REJECTED\x10\x03*\xa4\x01\n" +
	"\x1bUpdateApprovalRequestAction\x12.\n" +
	"*UPDATE_APPROVAL_REQUEST_ACTION_UNSPECIFIED\x10\x00\x12*\n" +
	"&UPDATE_APPROVAL_REQUEST_ACTION_APPROVE\x10\x01\x12)\n" +
	"%UPDATE_APPROVAL_REQUEST_ACTION_REJECT\x10\x022\x8f\x05\n" +
	"\x0fApprovalService\x12\xa0\x01\n" +
	"\x14ListApprovalRequests\x12$.core.v1.ListApprovalRequestsRequest\x1a%.core.v1.ListApprovalRequestsResponse\";\x82\xd3\xe4\x93\x022:\x01*\"-/core.v1.ApprovalService/ListApprovalRequests\x90\x02\x01\x12\xa1\x01\n" +
	"\x15UpdateApprovalRequest\x12%.core.v1.UpdateApprovalRequestRequest\x1a&.core.v1.UpdateApprovalRequestResponse\"9\x82\xd3\xe4\x93\x023:\x01*\"./core.v1.ApprovalService/UpdateApprovalRequest\x12\x98\x01\n" +
	"\x12ListAccessRequests\x12\".core.v1.ListAccessRequestsRequest\x1a#.core.v1.ListAccessRequestsResponse\"9\x82\xd3\xe4\x93\x020:\x01*\"+/core.v1.ApprovalService/ListAccessRequests\x90\x02\x01\x12\x99\x01\n" +
	"\x13CreateAccessRequest\x12#.core.v1.CreateAccessRequestRequest\x1a$.core.v1.CreateAccessRequestResponse\"7\x82\xd3\xe4\x93\x021:\x01*\",/core.v1.ApprovalService/CreateAccessRequestB\x87\x01\n" +
	"\vcom.core.v1B\rApprovalProtoP\x01Z,github.com/formalco/go-sdk/v3/core/v1;corev1\xa2\x02\x03CXX\xaa\x02\aCore.V1\xca\x02\aCore\\V1\xe2\x02\x13Core\\V1\\GPBMetadata\xea\x02\bCore::V1b\x06proto3"

var (
	file_core_v1_approval_proto_rawDescOnce sync.Once
	file_core_v1_approval_proto_rawDescData []byte
)

func file_core_v1_approval_proto_rawDescGZIP() []byte {
	file_core_v1_approval_proto_rawDescOnce.Do(func() {
		file_core_v1_approval_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_v1_approval_proto_rawDesc), len(file_core_v1_approval_proto_rawDesc)))
	})
	return file_core_v1_approval_proto_rawDescData
}

var file_core_v1_approval_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_core_v1_approval_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_core_v1_approval_proto_goTypes = []any{
	(ListApprovalRequestsStatus)(0),           // 0: core.v1.ListApprovalRequestsStatus
	(UpdateApprovalRequestAction)(0),          // 1: core.v1.UpdateApprovalRequestAction
	(*ApprovalRequest)(nil),                   // 2: core.v1.ApprovalRequest
	(*ApprovalRequestPayload)(nil),            // 3: core.v1.ApprovalRequestPayload
	(*PolicySuspensionApprovalRequest)(nil),   // 4: core.v1.PolicySuspensionApprovalRequest
	(*OneTimeApprovalAccess)(nil),             // 5: core.v1.OneTimeApprovalAccess
	(*TimeBoundApprovalAccess)(nil),           // 6: core.v1.TimeBoundApprovalAccess
	(*ApprovalAccessScope)(nil),               // 7: core.v1.ApprovalAccessScope
	(*ExactActionApprovalScope)(nil),          // 8: core.v1.ExactActionApprovalScope
	(*ToolApprovalScope)(nil),                 // 9: core.v1.ToolApprovalScope
	(*MethodApprovalScope)(nil),               // 10: core.v1.MethodApprovalScope
	(*DeviceApprovalScope)(nil),               // 11: core.v1.DeviceApprovalScope
	(*FullApprovalScope)(nil),                 // 12: core.v1.FullApprovalScope
	(*McpRegistryAccessApprovalRequest)(nil),  // 13: core.v1.McpRegistryAccessApprovalRequest
	(*CustomPolicyAccessApprovalRequest)(nil), // 14: core.v1.CustomPolicyAccessApprovalRequest
	(*ListApprovalRequestsRequest)(nil),       // 15: core.v1.ListApprovalRequestsRequest
	(*ListApprovalRequestsResponse)(nil),      // 16: core.v1.ListApprovalRequestsResponse
	(*UpdateApprovalRequestRequest)(nil),      // 17: core.v1.UpdateApprovalRequestRequest
	(*UpdateApprovalRequestResponse)(nil),     // 18: core.v1.UpdateApprovalRequestResponse
	(*ListAccessRequestsRequest)(nil),         // 19: core.v1.ListAccessRequestsRequest
	(*ListAccessRequestsResponse)(nil),        // 20: core.v1.ListAccessRequestsResponse
	(*UserAccessRequest)(nil),                 // 21: core.v1.UserAccessRequest
	(*UserAccessRequestPayload)(nil),          // 22: core.v1.UserAccessRequestPayload
	(*UserMcpServerCreate)(nil),               // 23: core.v1.UserMcpServerCreate
	(*UserPolicySuspension)(nil),              // 24: core.v1.UserPolicySuspension
	(*UserOneTimeAccess)(nil),                 // 25: core.v1.UserOneTimeAccess
	(*UserTimeBoundAccess)(nil),               // 26: core.v1.UserTimeBoundAccess
	(*UserExactActionScope)(nil),              // 27: core.v1.UserExactActionScope
	(*UserApprovalAccessScope)(nil),           // 28: core.v1.UserApprovalAccessScope
	(*UserFullPolicyScope)(nil),               // 29: core.v1.UserFullPolicyScope
	(*UserMcpRegistryAccess)(nil),             // 30: core.v1.UserMcpRegistryAccess
	(*UserCustomPolicyAccess)(nil),            // 31: core.v1.UserCustomPolicyAccess
	(*CreateAccessRequestRequest)(nil),        // 32: core.v1.CreateAccessRequestRequest
	(*CreateAccessRequestResponse)(nil),       // 33: core.v1.CreateAccessRequestResponse
	(*timestamppb.Timestamp)(nil),             // 34: google.protobuf.Timestamp
	(*CreateMcpServerRequest)(nil),            // 35: core.v1.CreateMcpServerRequest
	(*structpb.Struct)(nil),                   // 36: google.protobuf.Struct
	(*ListMetadata)(nil),                      // 37: core.v1.ListMetadata
}
var file_core_v1_approval_proto_depIdxs = []int32{
	3,  // 0: core.v1.ApprovalRequest.payload:type_name -> core.v1.ApprovalRequestPayload
	34, // 1: core.v1.ApprovalRequest.created_at:type_name -> google.protobuf.Timestamp
	34, // 2: core.v1.ApprovalRequest.decided_at:type_name -> google.protobuf.Timestamp
	35, // 3: core.v1.ApprovalRequestPayload.mcp_server_create:type_name -> core.v1.CreateMcpServerRequest
	4,  // 4: core.v1.ApprovalRequestPayload.policy_suspension:type_name -> core.v1.PolicySuspensionApprovalRequest
	13, // 5: core.v1.ApprovalRequestPayload.mcp_registry_access:type_name -> core.v1.McpRegistryAccessApprovalRequest
	14, // 6: core.v1.ApprovalRequestPayload.custom_policy_access:type_name -> core.v1.CustomPolicyAccessApprovalRequest
	5,  // 7: core.v1.PolicySuspensionApprovalRequest.one_time:type_name -> core.v1.OneTimeApprovalAccess
	6,  // 8: core.v1.PolicySuspensionApprovalRequest.time_bound:type_name -> core.v1.TimeBoundApprovalAccess
	7,  // 9: core.v1.PolicySuspensionApprovalRequest.scope:type_name -> core.v1.ApprovalAccessScope
	8,  // 10: core.v1.ApprovalAccessScope.exact_action:type_name -> core.v1.ExactActionApprovalScope
	9,  // 11: core.v1.ApprovalAccessScope.tool:type_name -> core.v1.ToolApprovalScope
	10, // 12: core.v1.ApprovalAccessScope.method:type_name -> core.v1.MethodApprovalScope
	11, // 13: core.v1.ApprovalAccessScope.device:type_name -> core.v1.DeviceApprovalScope
	12, // 14: core.v1.ApprovalAccessScope.full:type_name -> core.v1.FullApprovalScope
	36, // 15: core.v1.ExactActionApprovalScope.tool_arguments:type_name -> google.protobuf.Struct
	7,  // 16: core.v1.CustomPolicyAccessApprovalRequest.scope:type_name -> core.v1.ApprovalAccessScope
	0,  // 17: core.v1.ListApprovalRequestsRequest.status:type_name -> core.v1.ListApprovalRequestsStatus
	2,  // 18: core.v1.ListApprovalRequestsResponse.requests:type_name -> core.v1.ApprovalRequest
	37, // 19: core.v1.ListApprovalRequestsResponse.list_metadata:type_name -> core.v1.ListMetadata
	1,  // 20: core.v1.UpdateApprovalRequestRequest.action:type_name -> core.v1.UpdateApprovalRequestAction
	2,  // 21: core.v1.UpdateApprovalRequestResponse.request:type_name -> core.v1.ApprovalRequest
	21, // 22: core.v1.ListAccessRequestsResponse.requests:type_name -> core.v1.UserAccessRequest
	37, // 23: core.v1.ListAccessRequestsResponse.list_metadata:type_name -> core.v1.ListMetadata
	22, // 24: core.v1.UserAccessRequest.payload:type_name -> core.v1.UserAccessRequestPayload
	34, // 25: core.v1.UserAccessRequest.created_at:type_name -> google.protobuf.Timestamp
	34, // 26: core.v1.UserAccessRequest.decided_at:type_name -> google.protobuf.Timestamp
	23, // 27: core.v1.UserAccessRequestPayload.mcp_server_create:type_name -> core.v1.UserMcpServerCreate
	24, // 28: core.v1.UserAccessRequestPayload.policy_suspension:type_name -> core.v1.UserPolicySuspension
	30, // 29: core.v1.UserAccessRequestPayload.mcp_registry_access:type_name -> core.v1.UserMcpRegistryAccess
	31, // 30: core.v1.UserAccessRequestPayload.custom_policy_access:type_name -> core.v1.UserCustomPolicyAccess
	25, // 31: core.v1.UserPolicySuspension.one_time:type_name -> core.v1.UserOneTimeAccess
	26, // 32: core.v1.UserPolicySuspension.time_bound:type_name -> core.v1.UserTimeBoundAccess
	28, // 33: core.v1.UserPolicySuspension.scope:type_name -> core.v1.UserApprovalAccessScope
	36, // 34: core.v1.UserExactActionScope.tool_arguments:type_name -> google.protobuf.Struct
	27, // 35: core.v1.UserApprovalAccessScope.exact_action:type_name -> core.v1.UserExactActionScope
	29, // 36: core.v1.UserApprovalAccessScope.full:type_name -> core.v1.UserFullPolicyScope
	27, // 37: core.v1.UserCustomPolicyAccess.scope:type_name -> core.v1.UserExactActionScope
	22, // 38: core.v1.CreateAccessRequestRequest.payload:type_name -> core.v1.UserAccessRequestPayload
	15, // 39: core.v1.ApprovalService.ListApprovalRequests:input_type -> core.v1.ListApprovalRequestsRequest
	17, // 40: core.v1.ApprovalService.UpdateApprovalRequest:input_type -> core.v1.UpdateApprovalRequestRequest
	19, // 41: core.v1.ApprovalService.ListAccessRequests:input_type -> core.v1.ListAccessRequestsRequest
	32, // 42: core.v1.ApprovalService.CreateAccessRequest:input_type -> core.v1.CreateAccessRequestRequest
	16, // 43: core.v1.ApprovalService.ListApprovalRequests:output_type -> core.v1.ListApprovalRequestsResponse
	18, // 44: core.v1.ApprovalService.UpdateApprovalRequest:output_type -> core.v1.UpdateApprovalRequestResponse
	20, // 45: core.v1.ApprovalService.ListAccessRequests:output_type -> core.v1.ListAccessRequestsResponse
	33, // 46: core.v1.ApprovalService.CreateAccessRequest:output_type -> core.v1.CreateAccessRequestResponse
	43, // [43:47] is the sub-list for method output_type
	39, // [39:43] is the sub-list for method input_type
	39, // [39:39] is the sub-list for extension type_name
	39, // [39:39] is the sub-list for extension extendee
	0,  // [0:39] is the sub-list for field type_name
}

func init() { file_core_v1_approval_proto_init() }
func file_core_v1_approval_proto_init() {
	if File_core_v1_approval_proto != nil {
		return
	}
	file_core_v1_list_metadata_proto_init()
	file_core_v1_mcp_proto_init()
	file_core_v1_approval_proto_msgTypes[1].OneofWrappers = []any{
		(*ApprovalRequestPayload_McpServerCreate)(nil),
		(*ApprovalRequestPayload_PolicySuspension)(nil),
		(*ApprovalRequestPayload_McpRegistryAccess)(nil),
		(*ApprovalRequestPayload_CustomPolicyAccess)(nil),
	}
	file_core_v1_approval_proto_msgTypes[2].OneofWrappers = []any{
		(*PolicySuspensionApprovalRequest_OneTime)(nil),
		(*PolicySuspensionApprovalRequest_TimeBound)(nil),
	}
	file_core_v1_approval_proto_msgTypes[5].OneofWrappers = []any{
		(*ApprovalAccessScope_ExactAction)(nil),
		(*ApprovalAccessScope_Tool)(nil),
		(*ApprovalAccessScope_Method)(nil),
		(*ApprovalAccessScope_Device)(nil),
		(*ApprovalAccessScope_Full)(nil),
	}
	file_core_v1_approval_proto_msgTypes[20].OneofWrappers = []any{
		(*UserAccessRequestPayload_McpServerCreate)(nil),
		(*UserAccessRequestPayload_PolicySuspension)(nil),
		(*UserAccessRequestPayload_McpRegistryAccess)(nil),
		(*UserAccessRequestPayload_CustomPolicyAccess)(nil),
	}
	file_core_v1_approval_proto_msgTypes[22].OneofWrappers = []any{
		(*UserPolicySuspension_OneTime)(nil),
		(*UserPolicySuspension_TimeBound)(nil),
	}
	file_core_v1_approval_proto_msgTypes[26].OneofWrappers = []any{
		(*UserApprovalAccessScope_ExactAction)(nil),
		(*UserApprovalAccessScope_Full)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_v1_approval_proto_rawDesc), len(file_core_v1_approval_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_v1_approval_proto_goTypes,
		DependencyIndexes: file_core_v1_approval_proto_depIdxs,
		EnumInfos:         file_core_v1_approval_proto_enumTypes,
		MessageInfos:      file_core_v1_approval_proto_msgTypes,
	}.Build()
	File_core_v1_approval_proto = out.File
	file_core_v1_approval_proto_goTypes = nil
	file_core_v1_approval_proto_depIdxs = nil
}
