// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        (unknown)
// source: core/v1/change_authorization.proto

package corev1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SigningKey struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PublicKey             string                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Algorithm             string                 `protobuf:"bytes,4,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	Status                string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt             *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt             *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	UserId                string                 `protobuf:"bytes,8,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TerminationProtection bool                   `protobuf:"varint,9,opt,name=termination_protection,json=terminationProtection,proto3" json:"termination_protection,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SigningKey) Reset() {
	*x = SigningKey{}
	mi := &file_core_v1_change_authorization_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SigningKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigningKey) ProtoMessage() {}

func (x *SigningKey) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_change_authorization_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigningKey.ProtoReflect.Descriptor instead.
func (*SigningKey) Descriptor() ([]byte, []int) {
	return file_core_v1_change_authorization_proto_rawDescGZIP(), []int{0}
}

func (x *SigningKey) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SigningKey) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SigningKey) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *SigningKey) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *SigningKey) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SigningKey) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SigningKey) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *SigningKey) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SigningKey) GetTerminationProtection() bool {
	if x != nil {
		return x.TerminationProtection
	}
	return false
}

type CreateSigningKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PublicKey     string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Algorithm     string                 `protobuf:"bytes,3,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSigningKeyRequest) Reset() {
	*x = CreateSigningKeyRequest{}
	mi := &file_core_v1_change_authorization_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSigningKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSigningKeyRequest) ProtoMessage() {}

func (x *CreateSigningKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_change_authorization_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSigningKeyRequest.ProtoReflect.Descriptor instead.
func (*CreateSigningKeyRequest) Descriptor() ([]byte, []int) {
	return file_core_v1_change_authorization_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSigningKeyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSigningKeyRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *CreateSigningKeyRequest) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

type CreateSigningKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SigningKey    *SigningKey            `protobuf:"bytes,1,opt,name=signing_key,json=signingKey,proto3" json:"signing_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSigningKeyResponse) Reset() {
	*x = CreateSigningKeyResponse{}
	mi := &file_core_v1_change_authorization_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSigningKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSigningKeyResponse) ProtoMessage() {}

func (x *CreateSigningKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_change_authorization_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSigningKeyResponse.ProtoReflect.Descriptor instead.
func (*CreateSigningKeyResponse) Descriptor() ([]byte, []int) {
	return file_core_v1_change_authorization_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSigningKeyResponse) GetSigningKey() *SigningKey {
	if x != nil {
		return x.SigningKey
	}
	return nil
}

type UpdateSigningKeyRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status                string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	TerminationProtection *bool                  `protobuf:"varint,3,opt,name=termination_protection,json=terminationProtection,proto3,oneof" json:"termination_protection,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *UpdateSigningKeyRequest) Reset() {
	*x = UpdateSigningKeyRequest{}
	mi := &file_core_v1_change_authorization_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSigningKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSigningKeyRequest) ProtoMessage() {}

func (x *UpdateSigningKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_change_authorization_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSigningKeyRequest.ProtoReflect.Descriptor instead.
func (*UpdateSigningKeyRequest) Descriptor() ([]byte, []int) {
	return file_core_v1_change_authorization_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateSigningKeyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateSigningKeyRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateSigningKeyRequest) GetTerminationProtection() bool {
	if x != nil && x.TerminationProtection != nil {
		return *x.TerminationProtection
	}
	return false
}

type UpdateSigningKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SigningKey    *SigningKey            `protobuf:"bytes,1,opt,name=signing_key,json=signingKey,proto3" json:"signing_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSigningKeyResponse) Reset() {
	*x = UpdateSigningKeyResponse{}
	mi := &file_core_v1_change_authorization_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSigningKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSigningKeyResponse) ProtoMessage() {}

func (x *UpdateSigningKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_change_authorization_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSigningKeyResponse.ProtoReflect.Descriptor instead.
func (*UpdateSigningKeyResponse) Descriptor() ([]byte, []int) {
	return file_core_v1_change_authorization_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateSigningKeyResponse) GetSigningKey() *SigningKey {
	if x != nil {
		return x.SigningKey
	}
	return nil
}

type UpdateSigningKeyV2Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SigningKey    *SigningKey            `protobuf:"bytes,1,opt,name=signing_key,json=signingKey,proto3" json:"signing_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSigningKeyV2Request) Reset() {
	*x = UpdateSigningKeyV2Request{}
	mi := &file_core_v1_change_authorization_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSigningKeyV2Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSigningKeyV2Request) ProtoMessage() {}

func (x *UpdateSigningKeyV2Request) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_change_authorization_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSigningKeyV2Request.ProtoReflect.Descriptor instead.
func (*UpdateSigningKeyV2Request) Descriptor() ([]byte, []int) {
	return file_core_v1_change_authorization_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateSigningKeyV2Request) GetSigningKey() *SigningKey {
	if x != nil {
		return x.SigningKey
	}
	return nil
}

type UpdateSigningKeyV2Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SigningKey    *SigningKey            `protobuf:"bytes,1,opt,name=signing_key,json=signingKey,proto3" json:"signing_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSigningKeyV2Response) Reset() {
	*x = UpdateSigningKeyV2Response{}
	mi := &file_core_v1_change_authorization_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSigningKeyV2Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSigningKeyV2Response) ProtoMessage() {}

func (x *UpdateSigningKeyV2Response) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_change_authorization_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSigningKeyV2Response.ProtoReflect.Descriptor instead.
func (*UpdateSigningKeyV2Response) Descriptor() ([]byte, []int) {
	return file_core_v1_change_authorization_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateSigningKeyV2Response) GetSigningKey() *SigningKey {
	if x != nil {
		return x.SigningKey
	}
	return nil
}

type ListSigningKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Order         string                 `protobuf:"bytes,3,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSigningKeysRequest) Reset() {
	*x = ListSigningKeysRequest{}
	mi := &file_core_v1_change_authorization_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSigningKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSigningKeysRequest) ProtoMessage() {}

func (x *ListSigningKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_change_authorization_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSigningKeysRequest.ProtoReflect.Descriptor instead.
func (*ListSigningKeysRequest) Descriptor() ([]byte, []int) {
	return file_core_v1_change_authorization_proto_rawDescGZIP(), []int{7}
}

func (x *ListSigningKeysRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListSigningKeysRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListSigningKeysRequest) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

type ListSigningKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SigningKeys   []*SigningKey          `protobuf:"bytes,1,rep,name=signing_keys,json=signingKeys,proto3" json:"signing_keys,omitempty"`
	ListMetadata  *ListMetadata          `protobuf:"bytes,2,opt,name=list_metadata,json=listMetadata,proto3" json:"list_metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSigningKeysResponse) Reset() {
	*x = ListSigningKeysResponse{}
	mi := &file_core_v1_change_authorization_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSigningKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSigningKeysResponse) ProtoMessage() {}

func (x *ListSigningKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_change_authorization_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSigningKeysResponse.ProtoReflect.Descriptor instead.
func (*ListSigningKeysResponse) Descriptor() ([]byte, []int) {
	return file_core_v1_change_authorization_proto_rawDescGZIP(), []int{8}
}

func (x *ListSigningKeysResponse) GetSigningKeys() []*SigningKey {
	if x != nil {
		return x.SigningKeys
	}
	return nil
}

func (x *ListSigningKeysResponse) GetListMetadata() *ListMetadata {
	if x != nil {
		return x.ListMetadata
	}
	return nil
}

type DeleteSigningKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSigningKeyRequest) Reset() {
	*x = DeleteSigningKeyRequest{}
	mi := &file_core_v1_change_authorization_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSigningKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSigningKeyRequest) ProtoMessage() {}

func (x *DeleteSigningKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_change_authorization_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSigningKeyRequest.ProtoReflect.Descriptor instead.
func (*DeleteSigningKeyRequest) Descriptor() ([]byte, []int) {
	return file_core_v1_change_authorization_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteSigningKeyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteSigningKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSigningKeyResponse) Reset() {
	*x = DeleteSigningKeyResponse{}
	mi := &file_core_v1_change_authorization_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSigningKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSigningKeyResponse) ProtoMessage() {}

func (x *DeleteSigningKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_change_authorization_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSigningKeyResponse.ProtoReflect.Descriptor instead.
func (*DeleteSigningKeyResponse) Descriptor() ([]byte, []int) {
	return file_core_v1_change_authorization_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteSigningKeyResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_core_v1_change_authorization_proto protoreflect.FileDescriptor

const file_core_v1_change_authorization_proto_rawDesc = "" +
	"\n" +
	"\"core/v1/change_authorization.proto\x12\acore.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1bcore/v1/list_metadata.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xae\x03\n" +
	"\n" +
	"SigningKey\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x02id\x12\x1b\n" +
	"\x04name\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04name\x12&\n" +
	"\n" +
	"public_key\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tpublicKey\x12C\n" +
	"\talgorithm\x18\x04 \x01(\tB%\xbaH\"r R\n" +
	"ecdsa-p384R\aed25519R\tml-dsa-87R\talgorithm\x12.\n" +
	"\x06status\x18\x05 \x01(\tB\x16\xbaH\x13r\x11R\x06activeR\arevokedR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12 \n" +
	"\auser_id\x18\b \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06userId\x125\n" +
	"\x16termination_protection\x18\t \x01(\bR\x15terminationProtection\"\xa3\x01\n" +
	"\x17CreateSigningKeyRequest\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04name\x12&\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tpublicKey\x12C\n" +
	"\talgorithm\x18\x03 \x01(\tB%\xbaH\"r R\n" +
	"ecdsa-p384R\aed25519R\tml-dsa-87R\talgorithm\"P\n" +
	"\x18CreateSigningKeyResponse\x124\n" +
	"\vsigning_key\x18\x01 \x01(\v2\x13.core.v1.SigningKeyR\n" +
	"signingKey\"\xb9\x01\n" +
	"\x17UpdateSigningKeyRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x02id\x12.\n" +
	"\x06status\x18\x02 \x01(\tB\x16\xbaH\x13r\x11R\x06activeR\arevokedR\x06status\x12:\n" +
	"\x16termination_protection\x18\x03 \x01(\bH\x00R\x15terminationProtection\x88\x01\x01B\x19\n" +
	"\x17_termination_protection\"P\n" +
	"\x18UpdateSigningKeyResponse\x124\n" +
	"\vsigning_key\x18\x01 \x01(\v2\x13.core.v1.SigningKeyR\n" +
	"signingKey\"Y\n" +
	"\x19UpdateSigningKeyV2Request\x12<\n" +
	"\vsigning_key\x18\x01 \x01(\v2\x13.core.v1.SigningKeyB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"signingKey\"R\n" +
	"\x1aUpdateSigningKeyV2Response\x124\n" +
	"\vsigning_key\x18\x01 \x01(\v2\x13.core.v1.SigningKeyR\n" +
	"signingKey\"h\n" +
	"\x16ListSigningKeysRequest\x12 \n" +
	"\x05limit\x18\x01 \x01(\x05B\n" +
	"\xbaH\a\x1a\x05\x18\xf4\x03 \x00R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\x12\x14\n" +
	"\x05order\x18\x03 \x01(\tR\x05order\"\x8d\x01\n" +
	"\x17ListSigningKeysResponse\x126\n" +
	"\fsigning_keys\x18\x01 \x03(\v2\x13.core.v1.SigningKeyR\vsigningKeys\x12:\n" +
	"\rlist_metadata\x18\x02 \x01(\v2\x15.core.v1.ListMetadataR\flistMetadata\"2\n" +
	"\x17DeleteSigningKeyRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x02id\"3\n" +
	"\x18DeleteSigningKeyResponse\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x02id2\xaa\x06\n" +
	"\x1aChangeAuthorizationService\x12\x98\x01\n" +
	"\x10CreateSigningKey\x12 .core.v1.CreateSigningKeyRequest\x1a!.core.v1.CreateSigningKeyResponse\"?\x82\xd3\xe4\x93\x029:\x01*\"4/core.v1.ChangeAuthorizationService/CreateSigningKey\x12\x97\x01\n" +
	"\x0fListSigningKeys\x12\x1f.core.v1.ListSigningKeysRequest\x1a .core.v1.ListSigningKeysResponse\"A\x82\xd3\xe4\x93\x028:\x01*\"3/core.v1.ChangeAuthorizationService/ListSigningKeys\x90\x02\x01\x12\x98\x01\n" +
	"\x10UpdateSigningKey\x12 .core.v1.UpdateSigningKeyRequest\x1a!.core.v1.UpdateSigningKeyResponse\"?\x82\xd3\xe4\x93\x029:\x01*\"4/core.v1.ChangeAuthorizationService/UpdateSigningKey\x12\xa0\x01\n" +
	"\x12UpdateSigningKeyV2\x12\".core.v1.UpdateSigningKeyV2Request\x1a#.core.v1.UpdateSigningKeyV2Response\"A\x82\xd3\xe4\x93\x02;:\x01*\"6/core.v1.ChangeAuthorizationService/UpdateSigningKeyV2\x12\x98\x01\n" +
	"\x10DeleteSigningKey\x12 .core.v1.DeleteSigningKeyRequest\x1a!.core.v1.DeleteSigningKeyResponse\"?\x82\xd3\xe4\x93\x029:\x01*\"4/core.v1.ChangeAuthorizationService/DeleteSigningKeyB\x92\x01\n" +
	"\vcom.core.v1B\x18ChangeAuthorizationProtoP\x01Z,github.com/formalco/go-sdk/v3/core/v1;corev1\xa2\x02\x03CXX\xaa\x02\aCore.V1\xca\x02\aCore\\V1\xe2\x02\x13Core\\V1\\GPBMetadata\xea\x02\bCore::V1b\x06proto3"

var (
	file_core_v1_change_authorization_proto_rawDescOnce sync.Once
	file_core_v1_change_authorization_proto_rawDescData []byte
)

func file_core_v1_change_authorization_proto_rawDescGZIP() []byte {
	file_core_v1_change_authorization_proto_rawDescOnce.Do(func() {
		file_core_v1_change_authorization_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_v1_change_authorization_proto_rawDesc), len(file_core_v1_change_authorization_proto_rawDesc)))
	})
	return file_core_v1_change_authorization_proto_rawDescData
}

var file_core_v1_change_authorization_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_core_v1_change_authorization_proto_goTypes = []any{
	(*SigningKey)(nil),                 // 0: core.v1.SigningKey
	(*CreateSigningKeyRequest)(nil),    // 1: core.v1.CreateSigningKeyRequest
	(*CreateSigningKeyResponse)(nil),   // 2: core.v1.CreateSigningKeyResponse
	(*UpdateSigningKeyRequest)(nil),    // 3: core.v1.UpdateSigningKeyRequest
	(*UpdateSigningKeyResponse)(nil),   // 4: core.v1.UpdateSigningKeyResponse
	(*UpdateSigningKeyV2Request)(nil),  // 5: core.v1.UpdateSigningKeyV2Request
	(*UpdateSigningKeyV2Response)(nil), // 6: core.v1.UpdateSigningKeyV2Response
	(*ListSigningKeysRequest)(nil),     // 7: core.v1.ListSigningKeysRequest
	(*ListSigningKeysResponse)(nil),    // 8: core.v1.ListSigningKeysResponse
	(*DeleteSigningKeyRequest)(nil),    // 9: core.v1.DeleteSigningKeyRequest
	(*DeleteSigningKeyResponse)(nil),   // 10: core.v1.DeleteSigningKeyResponse
	(*timestamppb.Timestamp)(nil),      // 11: google.protobuf.Timestamp
	(*ListMetadata)(nil),               // 12: core.v1.ListMetadata
}
var file_core_v1_change_authorization_proto_depIdxs = []int32{
	11, // 0: core.v1.SigningKey.created_at:type_name -> google.protobuf.Timestamp
	11, // 1: core.v1.SigningKey.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: core.v1.CreateSigningKeyResponse.signing_key:type_name -> core.v1.SigningKey
	0,  // 3: core.v1.UpdateSigningKeyResponse.signing_key:type_name -> core.v1.SigningKey
	0,  // 4: core.v1.UpdateSigningKeyV2Request.signing_key:type_name -> core.v1.SigningKey
	0,  // 5: core.v1.UpdateSigningKeyV2Response.signing_key:type_name -> core.v1.SigningKey
	0,  // 6: core.v1.ListSigningKeysResponse.signing_keys:type_name -> core.v1.SigningKey
	12, // 7: core.v1.ListSigningKeysResponse.list_metadata:type_name -> core.v1.ListMetadata
	1,  // 8: core.v1.ChangeAuthorizationService.CreateSigningKey:input_type -> core.v1.CreateSigningKeyRequest
	7,  // 9: core.v1.ChangeAuthorizationService.ListSigningKeys:input_type -> core.v1.ListSigningKeysRequest
	3,  // 10: core.v1.ChangeAuthorizationService.UpdateSigningKey:input_type -> core.v1.UpdateSigningKeyRequest
	5,  // 11: core.v1.ChangeAuthorizationService.UpdateSigningKeyV2:input_type -> core.v1.UpdateSigningKeyV2Request
	9,  // 12: core.v1.ChangeAuthorizationService.DeleteSigningKey:input_type -> core.v1.DeleteSigningKeyRequest
	2,  // 13: core.v1.ChangeAuthorizationService.CreateSigningKey:output_type -> core.v1.CreateSigningKeyResponse
	8,  // 14: core.v1.ChangeAuthorizationService.ListSigningKeys:output_type -> core.v1.ListSigningKeysResponse
	4,  // 15: core.v1.ChangeAuthorizationService.UpdateSigningKey:output_type -> core.v1.UpdateSigningKeyResponse
	6,  // 16: core.v1.ChangeAuthorizationService.UpdateSigningKeyV2:output_type -> core.v1.UpdateSigningKeyV2Response
	10, // 17: core.v1.ChangeAuthorizationService.DeleteSigningKey:output_type -> core.v1.DeleteSigningKeyResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_core_v1_change_authorization_proto_init() }
func file_core_v1_change_authorization_proto_init() {
	if File_core_v1_change_authorization_proto != nil {
		return
	}
	file_core_v1_list_metadata_proto_init()
	file_core_v1_change_authorization_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_v1_change_authorization_proto_rawDesc), len(file_core_v1_change_authorization_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_v1_change_authorization_proto_goTypes,
		DependencyIndexes: file_core_v1_change_authorization_proto_depIdxs,
		MessageInfos:      file_core_v1_change_authorization_proto_msgTypes,
	}.Build()
	File_core_v1_change_authorization_proto = out.File
	file_core_v1_change_authorization_proto_goTypes = nil
	file_core_v1_change_authorization_proto_depIdxs = nil
}
