// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        (unknown)
// source: core/v1/filter.proto

package corev1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Field struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Operator      string                 `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	Value         *anypb.Any             `protobuf:"bytes,3,opt,name=value,proto3,oneof" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Field) Reset() {
	*x = Field{}
	mi := &file_core_v1_filter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_filter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_core_v1_filter_proto_rawDescGZIP(), []int{0}
}

func (x *Field) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Field) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *Field) GetValue() *anypb.Any {
	if x != nil {
		return x.Value
	}
	return nil
}

type FieldGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operator      string                 `protobuf:"bytes,1,opt,name=operator,proto3" json:"operator,omitempty"`
	Filters       []*Filter              `protobuf:"bytes,2,rep,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldGroup) Reset() {
	*x = FieldGroup{}
	mi := &file_core_v1_filter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldGroup) ProtoMessage() {}

func (x *FieldGroup) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_filter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldGroup.ProtoReflect.Descriptor instead.
func (*FieldGroup) Descriptor() ([]byte, []int) {
	return file_core_v1_filter_proto_rawDescGZIP(), []int{1}
}

func (x *FieldGroup) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *FieldGroup) GetFilters() []*Filter {
	if x != nil {
		return x.Filters
	}
	return nil
}

type Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         *Field                 `protobuf:"bytes,1,opt,name=field,proto3,oneof" json:"field,omitempty"`
	Group         *FieldGroup            `protobuf:"bytes,2,opt,name=group,proto3,oneof" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_core_v1_filter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_filter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_core_v1_filter_proto_rawDescGZIP(), []int{2}
}

func (x *Filter) GetField() *Field {
	if x != nil {
		return x.Field
	}
	return nil
}

func (x *Filter) GetGroup() *FieldGroup {
	if x != nil {
		return x.Group
	}
	return nil
}

var File_core_v1_filter_proto protoreflect.FileDescriptor

const file_core_v1_filter_proto_rawDesc = "" +
	"\n" +
	"\x14core/v1/filter.proto\x12\acore.v1\x1a\x1bbuf/validate/validate.proto\x1a\x19google/protobuf/any.proto\"\xf1\x01\n" +
	"\x05Field\x12\x19\n" +
	"\x03key\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x03key\x12\x91\x01\n" +
	"\boperator\x18\x02 \x01(\tBu\xbaHrrpR\x06equalsR\n" +
	"not_equalsR\bcontainsR\fnot_containsR\x05emptyR\tnot_emptyR\vstarts_withR\tends_withR\n" +
	"lower_thanR\fgreater_thanR\boperator\x12/\n" +
	"\x05value\x18\x03 \x01(\v2\x14.google.protobuf.AnyH\x00R\x05value\x88\x01\x01B\b\n" +
	"\x06_value\"m\n" +
	"\n" +
	"FieldGroup\x12*\n" +
	"\boperator\x18\x01 \x01(\tB\x0e\xbaH\vr\tR\x03andR\x02orR\boperator\x123\n" +
	"\afilters\x18\x02 \x03(\v2\x0f.core.v1.FilterB\b\xbaH\x05\x92\x01\x02\b\x01R\afilters\"w\n" +
	"\x06Filter\x12)\n" +
	"\x05field\x18\x01 \x01(\v2\x0e.core.v1.FieldH\x00R\x05field\x88\x01\x01\x12.\n" +
	"\x05group\x18\x02 \x01(\v2\x13.core.v1.FieldGroupH\x01R\x05group\x88\x01\x01B\b\n" +
	"\x06_fieldB\b\n" +
	"\x06_groupB\x85\x01\n" +
	"\vcom.core.v1B\vFilterProtoP\x01Z,github.com/formalco/go-sdk/v3/core/v1;corev1\xa2\x02\x03CXX\xaa\x02\aCore.V1\xca\x02\aCore\\V1\xe2\x02\x13Core\\V1\\GPBMetadata\xea\x02\bCore::V1b\x06proto3"

var (
	file_core_v1_filter_proto_rawDescOnce sync.Once
	file_core_v1_filter_proto_rawDescData []byte
)

func file_core_v1_filter_proto_rawDescGZIP() []byte {
	file_core_v1_filter_proto_rawDescOnce.Do(func() {
		file_core_v1_filter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_v1_filter_proto_rawDesc), len(file_core_v1_filter_proto_rawDesc)))
	})
	return file_core_v1_filter_proto_rawDescData
}

var file_core_v1_filter_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_core_v1_filter_proto_goTypes = []any{
	(*Field)(nil),      // 0: core.v1.Field
	(*FieldGroup)(nil), // 1: core.v1.FieldGroup
	(*Filter)(nil),     // 2: core.v1.Filter
	(*anypb.Any)(nil),  // 3: google.protobuf.Any
}
var file_core_v1_filter_proto_depIdxs = []int32{
	3, // 0: core.v1.Field.value:type_name -> google.protobuf.Any
	2, // 1: core.v1.FieldGroup.filters:type_name -> core.v1.Filter
	0, // 2: core.v1.Filter.field:type_name -> core.v1.Field
	1, // 3: core.v1.Filter.group:type_name -> core.v1.FieldGroup
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_core_v1_filter_proto_init() }
func file_core_v1_filter_proto_init() {
	if File_core_v1_filter_proto != nil {
		return
	}
	file_core_v1_filter_proto_msgTypes[0].OneofWrappers = []any{}
	file_core_v1_filter_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_v1_filter_proto_rawDesc), len(file_core_v1_filter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_v1_filter_proto_goTypes,
		DependencyIndexes: file_core_v1_filter_proto_depIdxs,
		MessageInfos:      file_core_v1_filter_proto_msgTypes,
	}.Build()
	File_core_v1_filter_proto = out.File
	file_core_v1_filter_proto_goTypes = nil
	file_core_v1_filter_proto_depIdxs = nil
}
