// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        (unknown)
// source: core/v1/group.proto

package corev1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListGroupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Order         string                 `protobuf:"bytes,3,opt,name=order,proto3" json:"order,omitempty"`
	Search        string                 `protobuf:"bytes,4,opt,name=search,proto3" json:"search,omitempty"`
	SearchFields  []string               `protobuf:"bytes,5,rep,name=search_fields,json=searchFields,proto3" json:"search_fields,omitempty"`
	Filter        *Filter                `protobuf:"bytes,6,opt,name=filter,proto3,oneof" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupsRequest) Reset() {
	*x = ListGroupsRequest{}
	mi := &file_core_v1_group_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupsRequest) ProtoMessage() {}

func (x *ListGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_group_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupsRequest.ProtoReflect.Descriptor instead.
func (*ListGroupsRequest) Descriptor() ([]byte, []int) {
	return file_core_v1_group_proto_rawDescGZIP(), []int{0}
}

func (x *ListGroupsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListGroupsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListGroupsRequest) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

func (x *ListGroupsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListGroupsRequest) GetSearchFields() []string {
	if x != nil {
		return x.SearchFields
	}
	return nil
}

func (x *ListGroupsRequest) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type ListGroupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*Group               `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	ListMetadata  *ListMetadata          `protobuf:"bytes,2,opt,name=list_metadata,json=listMetadata,proto3" json:"list_metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupsResponse) Reset() {
	*x = ListGroupsResponse{}
	mi := &file_core_v1_group_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupsResponse) ProtoMessage() {}

func (x *ListGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_group_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupsResponse.ProtoReflect.Descriptor instead.
func (*ListGroupsResponse) Descriptor() ([]byte, []int) {
	return file_core_v1_group_proto_rawDescGZIP(), []int{1}
}

func (x *ListGroupsResponse) GetGroups() []*Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *ListGroupsResponse) GetListMetadata() *ListMetadata {
	if x != nil {
		return x.ListMetadata
	}
	return nil
}

type CreateGroupRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Name                  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description           string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	TerminationProtection bool                   `protobuf:"varint,3,opt,name=termination_protection,json=terminationProtection,proto3" json:"termination_protection,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CreateGroupRequest) Reset() {
	*x = CreateGroupRequest{}
	mi := &file_core_v1_group_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupRequest) ProtoMessage() {}

func (x *CreateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_group_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateGroupRequest) Descriptor() ([]byte, []int) {
	return file_core_v1_group_proto_rawDescGZIP(), []int{2}
}

func (x *CreateGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGroupRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateGroupRequest) GetTerminationProtection() bool {
	if x != nil {
		return x.TerminationProtection
	}
	return false
}

type CreateGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *Group                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupResponse) Reset() {
	*x = CreateGroupResponse{}
	mi := &file_core_v1_group_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupResponse) ProtoMessage() {}

func (x *CreateGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_group_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupResponse.ProtoReflect.Descriptor instead.
func (*CreateGroupResponse) Descriptor() ([]byte, []int) {
	return file_core_v1_group_proto_rawDescGZIP(), []int{3}
}

func (x *CreateGroupResponse) GetGroup() *Group {
	if x != nil {
		return x.Group
	}
	return nil
}

type GetGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupRequest) Reset() {
	*x = GetGroupRequest{}
	mi := &file_core_v1_group_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupRequest) ProtoMessage() {}

func (x *GetGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_group_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupRequest.ProtoReflect.Descriptor instead.
func (*GetGroupRequest) Descriptor() ([]byte, []int) {
	return file_core_v1_group_proto_rawDescGZIP(), []int{4}
}

func (x *GetGroupRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *Group                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupResponse) Reset() {
	*x = GetGroupResponse{}
	mi := &file_core_v1_group_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupResponse) ProtoMessage() {}

func (x *GetGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_group_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupResponse.ProtoReflect.Descriptor instead.
func (*GetGroupResponse) Descriptor() ([]byte, []int) {
	return file_core_v1_group_proto_rawDescGZIP(), []int{5}
}

func (x *GetGroupResponse) GetGroup() *Group {
	if x != nil {
		return x.Group
	}
	return nil
}

type DeleteGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGroupRequest) Reset() {
	*x = DeleteGroupRequest{}
	mi := &file_core_v1_group_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGroupRequest) ProtoMessage() {}

func (x *DeleteGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_group_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGroupRequest.ProtoReflect.Descriptor instead.
func (*DeleteGroupRequest) Descriptor() ([]byte, []int) {
	return file_core_v1_group_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteGroupRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGroupResponse) Reset() {
	*x = DeleteGroupResponse{}
	mi := &file_core_v1_group_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGroupResponse) ProtoMessage() {}

func (x *DeleteGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_group_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGroupResponse.ProtoReflect.Descriptor instead.
func (*DeleteGroupResponse) Descriptor() ([]byte, []int) {
	return file_core_v1_group_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteGroupResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateGroupRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                  *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description           *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	TerminationProtection *bool                  `protobuf:"varint,4,opt,name=termination_protection,json=terminationProtection,proto3,oneof" json:"termination_protection,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *UpdateGroupRequest) Reset() {
	*x = UpdateGroupRequest{}
	mi := &file_core_v1_group_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupRequest) ProtoMessage() {}

func (x *UpdateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_group_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupRequest.ProtoReflect.Descriptor instead.
func (*UpdateGroupRequest) Descriptor() ([]byte, []int) {
	return file_core_v1_group_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateGroupRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateGroupRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateGroupRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateGroupRequest) GetTerminationProtection() bool {
	if x != nil && x.TerminationProtection != nil {
		return *x.TerminationProtection
	}
	return false
}

type UpdateGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *Group                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGroupResponse) Reset() {
	*x = UpdateGroupResponse{}
	mi := &file_core_v1_group_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupResponse) ProtoMessage() {}

func (x *UpdateGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_group_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupResponse.ProtoReflect.Descriptor instead.
func (*UpdateGroupResponse) Descriptor() ([]byte, []int) {
	return file_core_v1_group_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateGroupResponse) GetGroup() *Group {
	if x != nil {
		return x.Group
	}
	return nil
}

type UpdateGroupV2Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *Group                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGroupV2Request) Reset() {
	*x = UpdateGroupV2Request{}
	mi := &file_core_v1_group_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupV2Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupV2Request) ProtoMessage() {}

func (x *UpdateGroupV2Request) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_group_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupV2Request.ProtoReflect.Descriptor instead.
func (*UpdateGroupV2Request) Descriptor() ([]byte, []int) {
	return file_core_v1_group_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateGroupV2Request) GetGroup() *Group {
	if x != nil {
		return x.Group
	}
	return nil
}

type UpdateGroupV2Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *Group                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGroupV2Response) Reset() {
	*x = UpdateGroupV2Response{}
	mi := &file_core_v1_group_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupV2Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupV2Response) ProtoMessage() {}

func (x *UpdateGroupV2Response) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_group_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupV2Response.ProtoReflect.Descriptor instead.
func (*UpdateGroupV2Response) Descriptor() ([]byte, []int) {
	return file_core_v1_group_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateGroupV2Response) GetGroup() *Group {
	if x != nil {
		return x.Group
	}
	return nil
}

type CreateUserGroupLinkRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	GroupId               string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId                string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TerminationProtection bool                   `protobuf:"varint,3,opt,name=termination_protection,json=terminationProtection,proto3" json:"termination_protection,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CreateUserGroupLinkRequest) Reset() {
	*x = CreateUserGroupLinkRequest{}
	mi := &file_core_v1_group_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserGroupLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserGroupLinkRequest) ProtoMessage() {}

func (x *CreateUserGroupLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_group_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserGroupLinkRequest.ProtoReflect.Descriptor instead.
func (*CreateUserGroupLinkRequest) Descriptor() ([]byte, []int) {
	return file_core_v1_group_proto_rawDescGZIP(), []int{12}
}

func (x *CreateUserGroupLinkRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *CreateUserGroupLinkRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateUserGroupLinkRequest) GetTerminationProtection() bool {
	if x != nil {
		return x.TerminationProtection
	}
	return false
}

type CreateUserGroupLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserGroupLink *UserGroupLink         `protobuf:"bytes,1,opt,name=user_group_link,json=userGroupLink,proto3" json:"user_group_link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserGroupLinkResponse) Reset() {
	*x = CreateUserGroupLinkResponse{}
	mi := &file_core_v1_group_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserGroupLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserGroupLinkResponse) ProtoMessage() {}

func (x *CreateUserGroupLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_group_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserGroupLinkResponse.ProtoReflect.Descriptor instead.
func (*CreateUserGroupLinkResponse) Descriptor() ([]byte, []int) {
	return file_core_v1_group_proto_rawDescGZIP(), []int{13}
}

func (x *CreateUserGroupLinkResponse) GetUserGroupLink() *UserGroupLink {
	if x != nil {
		return x.UserGroupLink
	}
	return nil
}

type ListUserGroupLinksRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	GroupId string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Limit   int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor  string                 `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Order   string                 `protobuf:"bytes,4,opt,name=order,proto3" json:"order,omitempty"`
	// Types that are valid to be assigned to Id:
	//
	//	*ListUserGroupLinksRequest_GroupId2
	//	*ListUserGroupLinksRequest_UserId
	Id            isListUserGroupLinksRequest_Id `protobuf_oneof:"id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserGroupLinksRequest) Reset() {
	*x = ListUserGroupLinksRequest{}
	mi := &file_core_v1_group_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserGroupLinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserGroupLinksRequest) ProtoMessage() {}

func (x *ListUserGroupLinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_group_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserGroupLinksRequest.ProtoReflect.Descriptor instead.
func (*ListUserGroupLinksRequest) Descriptor() ([]byte, []int) {
	return file_core_v1_group_proto_rawDescGZIP(), []int{14}
}

func (x *ListUserGroupLinksRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *ListUserGroupLinksRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListUserGroupLinksRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListUserGroupLinksRequest) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

func (x *ListUserGroupLinksRequest) GetId() isListUserGroupLinksRequest_Id {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *ListUserGroupLinksRequest) GetGroupId2() string {
	if x != nil {
		if x, ok := x.Id.(*ListUserGroupLinksRequest_GroupId2); ok {
			return x.GroupId2
		}
	}
	return ""
}

func (x *ListUserGroupLinksRequest) GetUserId() string {
	if x != nil {
		if x, ok := x.Id.(*ListUserGroupLinksRequest_UserId); ok {
			return x.UserId
		}
	}
	return ""
}

type isListUserGroupLinksRequest_Id interface {
	isListUserGroupLinksRequest_Id()
}

type ListUserGroupLinksRequest_GroupId2 struct {
	GroupId2 string `protobuf:"bytes,5,opt,name=group_id2,json=groupId2,proto3,oneof"`
}

type ListUserGroupLinksRequest_UserId struct {
	UserId string `protobuf:"bytes,6,opt,name=user_id,json=userId,proto3,oneof"`
}

func (*ListUserGroupLinksRequest_GroupId2) isListUserGroupLinksRequest_Id() {}

func (*ListUserGroupLinksRequest_UserId) isListUserGroupLinksRequest_Id() {}

type ListUserGroupLinksResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserGroupLinks []*UserGroupLink       `protobuf:"bytes,1,rep,name=user_group_links,json=userGroupLinks,proto3" json:"user_group_links,omitempty"`
	ListMetadata   *ListMetadata          `protobuf:"bytes,2,opt,name=list_metadata,json=listMetadata,proto3" json:"list_metadata,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListUserGroupLinksResponse) Reset() {
	*x = ListUserGroupLinksResponse{}
	mi := &file_core_v1_group_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserGroupLinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserGroupLinksResponse) ProtoMessage() {}

func (x *ListUserGroupLinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_group_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserGroupLinksResponse.ProtoReflect.Descriptor instead.
func (*ListUserGroupLinksResponse) Descriptor() ([]byte, []int) {
	return file_core_v1_group_proto_rawDescGZIP(), []int{15}
}

func (x *ListUserGroupLinksResponse) GetUserGroupLinks() []*UserGroupLink {
	if x != nil {
		return x.UserGroupLinks
	}
	return nil
}

func (x *ListUserGroupLinksResponse) GetListMetadata() *ListMetadata {
	if x != nil {
		return x.ListMetadata
	}
	return nil
}

type DeleteUserGroupLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserGroupLinkRequest) Reset() {
	*x = DeleteUserGroupLinkRequest{}
	mi := &file_core_v1_group_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserGroupLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserGroupLinkRequest) ProtoMessage() {}

func (x *DeleteUserGroupLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_group_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserGroupLinkRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserGroupLinkRequest) Descriptor() ([]byte, []int) {
	return file_core_v1_group_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteUserGroupLinkRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteUserGroupLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserGroupLinkResponse) Reset() {
	*x = DeleteUserGroupLinkResponse{}
	mi := &file_core_v1_group_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserGroupLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserGroupLinkResponse) ProtoMessage() {}

func (x *DeleteUserGroupLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_group_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserGroupLinkResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserGroupLinkResponse) Descriptor() ([]byte, []int) {
	return file_core_v1_group_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteUserGroupLinkResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteUserGroupLinkByUserIdAndGroupIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GroupId       string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserGroupLinkByUserIdAndGroupIdRequest) Reset() {
	*x = DeleteUserGroupLinkByUserIdAndGroupIdRequest{}
	mi := &file_core_v1_group_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserGroupLinkByUserIdAndGroupIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserGroupLinkByUserIdAndGroupIdRequest) ProtoMessage() {}

func (x *DeleteUserGroupLinkByUserIdAndGroupIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_group_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserGroupLinkByUserIdAndGroupIdRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserGroupLinkByUserIdAndGroupIdRequest) Descriptor() ([]byte, []int) {
	return file_core_v1_group_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteUserGroupLinkByUserIdAndGroupIdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteUserGroupLinkByUserIdAndGroupIdRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type DeleteUserGroupLinkByUserIdAndGroupIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GroupId       string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserGroupLinkByUserIdAndGroupIdResponse) Reset() {
	*x = DeleteUserGroupLinkByUserIdAndGroupIdResponse{}
	mi := &file_core_v1_group_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserGroupLinkByUserIdAndGroupIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserGroupLinkByUserIdAndGroupIdResponse) ProtoMessage() {}

func (x *DeleteUserGroupLinkByUserIdAndGroupIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_group_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserGroupLinkByUserIdAndGroupIdResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserGroupLinkByUserIdAndGroupIdResponse) Descriptor() ([]byte, []int) {
	return file_core_v1_group_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteUserGroupLinkByUserIdAndGroupIdResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteUserGroupLinkByUserIdAndGroupIdResponse) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

var File_core_v1_group_proto protoreflect.FileDescriptor

const file_core_v1_group_proto_rawDesc = "" +
	"\n" +
	"\x13core/v1/group.proto\x12\acore.v1\x1a\x1bbuf/validate/validate.proto\x1a\x14core/v1/filter.proto\x1a\x1bcore/v1/list_metadata.proto\x1a\x13core/v1/types.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfc\x01\n" +
	"\x11ListGroupsRequest\x12 \n" +
	"\x05limit\x18\x01 \x01(\x05B\n" +
	"\xbaH\a\x1a\x05\x18\xf4\x03 \x00R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\x12\x14\n" +
	"\x05order\x18\x03 \x01(\tR\x05order\x12\x16\n" +
	"\x06search\x18\x04 \x01(\tR\x06search\x12F\n" +
	"\rsearch_fields\x18\x05 \x03(\tB!\xbaH\x1e\x92\x01\x1b\"\x19r\x17R\x02idR\x04nameR\vdescriptionR\fsearchFields\x12,\n" +
	"\x06filter\x18\x06 \x01(\v2\x0f.core.v1.FilterH\x00R\x06filter\x88\x01\x01B\t\n" +
	"\a_filter\"x\n" +
	"\x12ListGroupsResponse\x12&\n" +
	"\x06groups\x18\x01 \x03(\v2\x0e.core.v1.GroupR\x06groups\x12:\n" +
	"\rlist_metadata\x18\x02 \x01(\v2\x15.core.v1.ListMetadataR\flistMetadata\"\x8a\x01\n" +
	"\x12CreateGroupRequest\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x125\n" +
	"\x16termination_protection\x18\x03 \x01(\bR\x15terminationProtection\";\n" +
	"\x13CreateGroupResponse\x12$\n" +
	"\x05group\x18\x01 \x01(\v2\x0e.core.v1.GroupR\x05group\"*\n" +
	"\x0fGetGroupRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x02id\"8\n" +
	"\x10GetGroupResponse\x12$\n" +
	"\x05group\x18\x01 \x01(\v2\x0e.core.v1.GroupR\x05group\"-\n" +
	"\x12DeleteGroupRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x02id\".\n" +
	"\x13DeleteGroupResponse\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x02id\"\xdd\x01\n" +
	"\x12UpdateGroupRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12:\n" +
	"\x16termination_protection\x18\x04 \x01(\bH\x02R\x15terminationProtection\x88\x01\x01B\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_descriptionB\x19\n" +
	"\x17_termination_protection\";\n" +
	"\x13UpdateGroupResponse\x12$\n" +
	"\x05group\x18\x01 \x01(\v2\x0e.core.v1.GroupR\x05group\"D\n" +
	"\x14UpdateGroupV2Request\x12,\n" +
	"\x05group\x18\x01 \x01(\v2\x0e.core.v1.GroupB\x06\xbaH\x03\xc8\x01\x01R\x05group\"=\n" +
	"\x15UpdateGroupV2Response\x12$\n" +
	"\x05group\x18\x01 \x01(\v2\x0e.core.v1.GroupR\x05group\"\x99\x01\n" +
	"\x1aCreateUserGroupLinkRequest\x12\"\n" +
	"\bgroup_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\agroupId\x12 \n" +
	"\auser_id\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06userId\x125\n" +
	"\x16termination_protection\x18\x03 \x01(\bR\x15terminationProtection\"]\n" +
	"\x1bCreateUserGroupLinkResponse\x12>\n" +
	"\x0fuser_group_link\x18\x01 \x01(\v2\x16.core.v1.UserGroupLinkR\ruserGroupLink\"\xe1\x01\n" +
	"\x19ListUserGroupLinksRequest\x12\"\n" +
	"\bgroup_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\agroupId\x12 \n" +
	"\x05limit\x18\x02 \x01(\x05B\n" +
	"\xbaH\a\x1a\x05\x18\xf4\x03 \x00R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\tR\x06cursor\x12\x14\n" +
	"\x05order\x18\x04 \x01(\tR\x05order\x12&\n" +
	"\tgroup_id2\x18\x05 \x01(\tB\a\xbaH\x04r\x02\x10\x01H\x00R\bgroupId2\x12\"\n" +
	"\auser_id\x18\x06 \x01(\tB\a\xbaH\x04r\x02\x10\x01H\x00R\x06userIdB\x04\n" +
	"\x02id\"\x9a\x01\n" +
	"\x1aListUserGroupLinksResponse\x12@\n" +
	"\x10user_group_links\x18\x01 \x03(\v2\x16.core.v1.UserGroupLinkR\x0euserGroupLinks\x12:\n" +
	"\rlist_metadata\x18\x02 \x01(\v2\x15.core.v1.ListMetadataR\flistMetadata\"5\n" +
	"\x1aDeleteUserGroupLinkRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x02id\"6\n" +
	"\x1bDeleteUserGroupLinkResponse\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x02id\"t\n" +
	",DeleteUserGroupLinkByUserIdAndGroupIdRequest\x12 \n" +
	"\auser_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06userId\x12\"\n" +
	"\bgroup_id\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\agroupId\"c\n" +
	"-DeleteUserGroupLinkByUserIdAndGroupIdResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId2\x87\v\n" +
	"\fGroupService\x12v\n" +
	"\vCreateGroup\x12\x1b.core.v1.CreateGroupRequest\x1a\x1c.core.v1.CreateGroupResponse\",\x82\xd3\xe4\x93\x02&:\x01*\"!/core.v1.GroupService/CreateGroup\x12u\n" +
	"\n" +
	"ListGroups\x12\x1a.core.v1.ListGroupsRequest\x1a\x1b.core.v1.ListGroupsResponse\".\x82\xd3\xe4\x93\x02%:\x01*\" /core.v1.GroupService/ListGroups\x90\x02\x01\x12m\n" +
	"\bGetGroup\x12\x18.core.v1.GetGroupRequest\x1a\x19.core.v1.GetGroupResponse\",\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/core.v1.GroupService/GetGroup\x90\x02\x01\x12v\n" +
	"\vUpdateGroup\x12\x1b.core.v1.UpdateGroupRequest\x1a\x1c.core.v1.UpdateGroupResponse\",\x82\xd3\xe4\x93\x02&:\x01*\"!/core.v1.GroupService/UpdateGroup\x12~\n" +
	"\rUpdateGroupV2\x12\x1d.core.v1.UpdateGroupV2Request\x1a\x1e.core.v1.UpdateGroupV2Response\".\x82\xd3\xe4\x93\x02(:\x01*\"#/core.v1.GroupService/UpdateGroupV2\x12v\n" +
	"\vDeleteGroup\x12\x1b.core.v1.DeleteGroupRequest\x1a\x1c.core.v1.DeleteGroupResponse\",\x82\xd3\xe4\x93\x02&:\x01*\"!/core.v1.GroupService/DeleteGroup\x12\x95\x01\n" +
	"\x12ListUserGroupLinks\x12\".core.v1.ListUserGroupLinksRequest\x1a#.core.v1.ListUserGroupLinksResponse\"6\x82\xd3\xe4\x93\x02-:\x01*\"(/core.v1.GroupService/ListUserGroupLinks\x90\x02\x01\x12\x96\x01\n" +
	"\x13CreateUserGroupLink\x12#.core.v1.CreateUserGroupLinkRequest\x1a$.core.v1.CreateUserGroupLinkResponse\"4\x82\xd3\xe4\x93\x02.:\x01*\")/core.v1.GroupService/CreateUserGroupLink\x12\x96\x01\n" +
	"\x13DeleteUserGroupLink\x12#.core.v1.DeleteUserGroupLinkRequest\x1a$.core.v1.DeleteUserGroupLinkResponse\"4\x82\xd3\xe4\x93\x02.:\x01*\")/core.v1.GroupService/DeleteUserGroupLink\x12\xde\x01\n" +
	"%DeleteUserGroupLinkByUserIdAndGroupId\x125.core.v1.DeleteUserGroupLinkByUserIdAndGroupIdRequest\x1a6.core.v1.DeleteUserGroupLinkByUserIdAndGroupIdResponse\"F\x82\xd3\xe4\x93\x02@:\x01*\";/core.v1.GroupService/DeleteUserGroupLinkByUserIdAndGroupIdB\x84\x01\n" +
	"\vcom.core.v1B\n" +
	"GroupProtoP\x01Z,github.com/formalco/go-sdk/v3/core/v1;corev1\xa2\x02\x03CXX\xaa\x02\aCore.V1\xca\x02\aCore\\V1\xe2\x02\x13Core\\V1\\GPBMetadata\xea\x02\bCore::V1b\x06proto3"

var (
	file_core_v1_group_proto_rawDescOnce sync.Once
	file_core_v1_group_proto_rawDescData []byte
)

func file_core_v1_group_proto_rawDescGZIP() []byte {
	file_core_v1_group_proto_rawDescOnce.Do(func() {
		file_core_v1_group_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_v1_group_proto_rawDesc), len(file_core_v1_group_proto_rawDesc)))
	})
	return file_core_v1_group_proto_rawDescData
}

var file_core_v1_group_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_core_v1_group_proto_goTypes = []any{
	(*ListGroupsRequest)(nil),                             // 0: core.v1.ListGroupsRequest
	(*ListGroupsResponse)(nil),                            // 1: core.v1.ListGroupsResponse
	(*CreateGroupRequest)(nil),                            // 2: core.v1.CreateGroupRequest
	(*CreateGroupResponse)(nil),                           // 3: core.v1.CreateGroupResponse
	(*GetGroupRequest)(nil),                               // 4: core.v1.GetGroupRequest
	(*GetGroupResponse)(nil),                              // 5: core.v1.GetGroupResponse
	(*DeleteGroupRequest)(nil),                            // 6: core.v1.DeleteGroupRequest
	(*DeleteGroupResponse)(nil),                           // 7: core.v1.DeleteGroupResponse
	(*UpdateGroupRequest)(nil),                            // 8: core.v1.UpdateGroupRequest
	(*UpdateGroupResponse)(nil),                           // 9: core.v1.UpdateGroupResponse
	(*UpdateGroupV2Request)(nil),                          // 10: core.v1.UpdateGroupV2Request
	(*UpdateGroupV2Response)(nil),                         // 11: core.v1.UpdateGroupV2Response
	(*CreateUserGroupLinkRequest)(nil),                    // 12: core.v1.CreateUserGroupLinkRequest
	(*CreateUserGroupLinkResponse)(nil),                   // 13: core.v1.CreateUserGroupLinkResponse
	(*ListUserGroupLinksRequest)(nil),                     // 14: core.v1.ListUserGroupLinksRequest
	(*ListUserGroupLinksResponse)(nil),                    // 15: core.v1.ListUserGroupLinksResponse
	(*DeleteUserGroupLinkRequest)(nil),                    // 16: core.v1.DeleteUserGroupLinkRequest
	(*DeleteUserGroupLinkResponse)(nil),                   // 17: core.v1.DeleteUserGroupLinkResponse
	(*DeleteUserGroupLinkByUserIdAndGroupIdRequest)(nil),  // 18: core.v1.DeleteUserGroupLinkByUserIdAndGroupIdRequest
	(*DeleteUserGroupLinkByUserIdAndGroupIdResponse)(nil), // 19: core.v1.DeleteUserGroupLinkByUserIdAndGroupIdResponse
	(*Filter)(nil),                                        // 20: core.v1.Filter
	(*Group)(nil),                                         // 21: core.v1.Group
	(*ListMetadata)(nil),                                  // 22: core.v1.ListMetadata
	(*UserGroupLink)(nil),                                 // 23: core.v1.UserGroupLink
}
var file_core_v1_group_proto_depIdxs = []int32{
	20, // 0: core.v1.ListGroupsRequest.filter:type_name -> core.v1.Filter
	21, // 1: core.v1.ListGroupsResponse.groups:type_name -> core.v1.Group
	22, // 2: core.v1.ListGroupsResponse.list_metadata:type_name -> core.v1.ListMetadata
	21, // 3: core.v1.CreateGroupResponse.group:type_name -> core.v1.Group
	21, // 4: core.v1.GetGroupResponse.group:type_name -> core.v1.Group
	21, // 5: core.v1.UpdateGroupResponse.group:type_name -> core.v1.Group
	21, // 6: core.v1.UpdateGroupV2Request.group:type_name -> core.v1.Group
	21, // 7: core.v1.UpdateGroupV2Response.group:type_name -> core.v1.Group
	23, // 8: core.v1.CreateUserGroupLinkResponse.user_group_link:type_name -> core.v1.UserGroupLink
	23, // 9: core.v1.ListUserGroupLinksResponse.user_group_links:type_name -> core.v1.UserGroupLink
	22, // 10: core.v1.ListUserGroupLinksResponse.list_metadata:type_name -> core.v1.ListMetadata
	2,  // 11: core.v1.GroupService.CreateGroup:input_type -> core.v1.CreateGroupRequest
	0,  // 12: core.v1.GroupService.ListGroups:input_type -> core.v1.ListGroupsRequest
	4,  // 13: core.v1.GroupService.GetGroup:input_type -> core.v1.GetGroupRequest
	8,  // 14: core.v1.GroupService.UpdateGroup:input_type -> core.v1.UpdateGroupRequest
	10, // 15: core.v1.GroupService.UpdateGroupV2:input_type -> core.v1.UpdateGroupV2Request
	6,  // 16: core.v1.GroupService.DeleteGroup:input_type -> core.v1.DeleteGroupRequest
	14, // 17: core.v1.GroupService.ListUserGroupLinks:input_type -> core.v1.ListUserGroupLinksRequest
	12, // 18: core.v1.GroupService.CreateUserGroupLink:input_type -> core.v1.CreateUserGroupLinkRequest
	16, // 19: core.v1.GroupService.DeleteUserGroupLink:input_type -> core.v1.DeleteUserGroupLinkRequest
	18, // 20: core.v1.GroupService.DeleteUserGroupLinkByUserIdAndGroupId:input_type -> core.v1.DeleteUserGroupLinkByUserIdAndGroupIdRequest
	3,  // 21: core.v1.GroupService.CreateGroup:output_type -> core.v1.CreateGroupResponse
	1,  // 22: core.v1.GroupService.ListGroups:output_type -> core.v1.ListGroupsResponse
	5,  // 23: core.v1.GroupService.GetGroup:output_type -> core.v1.GetGroupResponse
	9,  // 24: core.v1.GroupService.UpdateGroup:output_type -> core.v1.UpdateGroupResponse
	11, // 25: core.v1.GroupService.UpdateGroupV2:output_type -> core.v1.UpdateGroupV2Response
	7,  // 26: core.v1.GroupService.DeleteGroup:output_type -> core.v1.DeleteGroupResponse
	15, // 27: core.v1.GroupService.ListUserGroupLinks:output_type -> core.v1.ListUserGroupLinksResponse
	13, // 28: core.v1.GroupService.CreateUserGroupLink:output_type -> core.v1.CreateUserGroupLinkResponse
	17, // 29: core.v1.GroupService.DeleteUserGroupLink:output_type -> core.v1.DeleteUserGroupLinkResponse
	19, // 30: core.v1.GroupService.DeleteUserGroupLinkByUserIdAndGroupId:output_type -> core.v1.DeleteUserGroupLinkByUserIdAndGroupIdResponse
	21, // [21:31] is the sub-list for method output_type
	11, // [11:21] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_core_v1_group_proto_init() }
func file_core_v1_group_proto_init() {
	if File_core_v1_group_proto != nil {
		return
	}
	file_core_v1_filter_proto_init()
	file_core_v1_list_metadata_proto_init()
	file_core_v1_types_proto_init()
	file_core_v1_group_proto_msgTypes[0].OneofWrappers = []any{}
	file_core_v1_group_proto_msgTypes[8].OneofWrappers = []any{}
	file_core_v1_group_proto_msgTypes[14].OneofWrappers = []any{
		(*ListUserGroupLinksRequest_GroupId2)(nil),
		(*ListUserGroupLinksRequest_UserId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_v1_group_proto_rawDesc), len(file_core_v1_group_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_v1_group_proto_goTypes,
		DependencyIndexes: file_core_v1_group_proto_depIdxs,
		MessageInfos:      file_core_v1_group_proto_msgTypes,
	}.Build()
	File_core_v1_group_proto = out.File
	file_core_v1_group_proto_goTypes = nil
	file_core_v1_group_proto_depIdxs = nil
}
