// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        (unknown)
// source: core/v1/hooks.proto

package corev1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Hook struct {
	state                           protoimpl.MessageState `protogen:"open.v1"`
	Id                              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description                     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Code                            string                 `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	Status                          string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	TimeoutMs                       int32                  `protobuf:"varint,6,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	CreatedAt                       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt                       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	AllowlistedEnvironmentVariables []string               `protobuf:"bytes,9,rep,name=allowlisted_environment_variables,json=allowlistedEnvironmentVariables,proto3" json:"allowlisted_environment_variables,omitempty"`
	AllowlistedNetworkHosts         []string               `protobuf:"bytes,10,rep,name=allowlisted_network_hosts,json=allowlistedNetworkHosts,proto3" json:"allowlisted_network_hosts,omitempty"`
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *Hook) Reset() {
	*x = Hook{}
	mi := &file_core_v1_hooks_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hook) ProtoMessage() {}

func (x *Hook) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_hooks_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hook.ProtoReflect.Descriptor instead.
func (*Hook) Descriptor() ([]byte, []int) {
	return file_core_v1_hooks_proto_rawDescGZIP(), []int{0}
}

func (x *Hook) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Hook) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Hook) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Hook) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Hook) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Hook) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *Hook) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Hook) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Hook) GetAllowlistedEnvironmentVariables() []string {
	if x != nil {
		return x.AllowlistedEnvironmentVariables
	}
	return nil
}

func (x *Hook) GetAllowlistedNetworkHosts() []string {
	if x != nil {
		return x.AllowlistedNetworkHosts
	}
	return nil
}

type CreateHookRequest struct {
	state                           protoimpl.MessageState `protogen:"open.v1"`
	Name                            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description                     string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Code                            string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Status                          string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	TimeoutMs                       int32                  `protobuf:"varint,5,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	AllowlistedEnvironmentVariables []string               `protobuf:"bytes,6,rep,name=allowlisted_environment_variables,json=allowlistedEnvironmentVariables,proto3" json:"allowlisted_environment_variables,omitempty"`
	AllowlistedNetworkHosts         []string               `protobuf:"bytes,7,rep,name=allowlisted_network_hosts,json=allowlistedNetworkHosts,proto3" json:"allowlisted_network_hosts,omitempty"`
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *CreateHookRequest) Reset() {
	*x = CreateHookRequest{}
	mi := &file_core_v1_hooks_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHookRequest) ProtoMessage() {}

func (x *CreateHookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_hooks_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHookRequest.ProtoReflect.Descriptor instead.
func (*CreateHookRequest) Descriptor() ([]byte, []int) {
	return file_core_v1_hooks_proto_rawDescGZIP(), []int{1}
}

func (x *CreateHookRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateHookRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateHookRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateHookRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateHookRequest) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *CreateHookRequest) GetAllowlistedEnvironmentVariables() []string {
	if x != nil {
		return x.AllowlistedEnvironmentVariables
	}
	return nil
}

func (x *CreateHookRequest) GetAllowlistedNetworkHosts() []string {
	if x != nil {
		return x.AllowlistedNetworkHosts
	}
	return nil
}

type CreateHookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hook          *Hook                  `protobuf:"bytes,1,opt,name=hook,proto3" json:"hook,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHookResponse) Reset() {
	*x = CreateHookResponse{}
	mi := &file_core_v1_hooks_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHookResponse) ProtoMessage() {}

func (x *CreateHookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_hooks_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHookResponse.ProtoReflect.Descriptor instead.
func (*CreateHookResponse) Descriptor() ([]byte, []int) {
	return file_core_v1_hooks_proto_rawDescGZIP(), []int{2}
}

func (x *CreateHookResponse) GetHook() *Hook {
	if x != nil {
		return x.Hook
	}
	return nil
}

type ListHooksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Order         string                 `protobuf:"bytes,3,opt,name=order,proto3" json:"order,omitempty"`
	Search        string                 `protobuf:"bytes,4,opt,name=search,proto3" json:"search,omitempty"`
	SearchFields  []string               `protobuf:"bytes,5,rep,name=search_fields,json=searchFields,proto3" json:"search_fields,omitempty"`
	Filter        *Filter                `protobuf:"bytes,6,opt,name=filter,proto3,oneof" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHooksRequest) Reset() {
	*x = ListHooksRequest{}
	mi := &file_core_v1_hooks_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHooksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHooksRequest) ProtoMessage() {}

func (x *ListHooksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_hooks_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHooksRequest.ProtoReflect.Descriptor instead.
func (*ListHooksRequest) Descriptor() ([]byte, []int) {
	return file_core_v1_hooks_proto_rawDescGZIP(), []int{3}
}

func (x *ListHooksRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListHooksRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListHooksRequest) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

func (x *ListHooksRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListHooksRequest) GetSearchFields() []string {
	if x != nil {
		return x.SearchFields
	}
	return nil
}

func (x *ListHooksRequest) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type ListHooksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hooks         []*Hook                `protobuf:"bytes,1,rep,name=hooks,proto3" json:"hooks,omitempty"`
	ListMetadata  *ListMetadata          `protobuf:"bytes,2,opt,name=list_metadata,json=listMetadata,proto3" json:"list_metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHooksResponse) Reset() {
	*x = ListHooksResponse{}
	mi := &file_core_v1_hooks_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHooksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHooksResponse) ProtoMessage() {}

func (x *ListHooksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_hooks_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHooksResponse.ProtoReflect.Descriptor instead.
func (*ListHooksResponse) Descriptor() ([]byte, []int) {
	return file_core_v1_hooks_proto_rawDescGZIP(), []int{4}
}

func (x *ListHooksResponse) GetHooks() []*Hook {
	if x != nil {
		return x.Hooks
	}
	return nil
}

func (x *ListHooksResponse) GetListMetadata() *ListMetadata {
	if x != nil {
		return x.ListMetadata
	}
	return nil
}

type GetHookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHookRequest) Reset() {
	*x = GetHookRequest{}
	mi := &file_core_v1_hooks_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHookRequest) ProtoMessage() {}

func (x *GetHookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_hooks_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHookRequest.ProtoReflect.Descriptor instead.
func (*GetHookRequest) Descriptor() ([]byte, []int) {
	return file_core_v1_hooks_proto_rawDescGZIP(), []int{5}
}

func (x *GetHookRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetHookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hook          *Hook                  `protobuf:"bytes,1,opt,name=hook,proto3" json:"hook,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHookResponse) Reset() {
	*x = GetHookResponse{}
	mi := &file_core_v1_hooks_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHookResponse) ProtoMessage() {}

func (x *GetHookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_hooks_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHookResponse.ProtoReflect.Descriptor instead.
func (*GetHookResponse) Descriptor() ([]byte, []int) {
	return file_core_v1_hooks_proto_rawDescGZIP(), []int{6}
}

func (x *GetHookResponse) GetHook() *Hook {
	if x != nil {
		return x.Hook
	}
	return nil
}

type UpdateHookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hook          *Hook                  `protobuf:"bytes,1,opt,name=hook,proto3" json:"hook,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateHookRequest) Reset() {
	*x = UpdateHookRequest{}
	mi := &file_core_v1_hooks_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateHookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHookRequest) ProtoMessage() {}

func (x *UpdateHookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_hooks_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHookRequest.ProtoReflect.Descriptor instead.
func (*UpdateHookRequest) Descriptor() ([]byte, []int) {
	return file_core_v1_hooks_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateHookRequest) GetHook() *Hook {
	if x != nil {
		return x.Hook
	}
	return nil
}

type UpdateHookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hook          *Hook                  `protobuf:"bytes,1,opt,name=hook,proto3" json:"hook,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateHookResponse) Reset() {
	*x = UpdateHookResponse{}
	mi := &file_core_v1_hooks_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateHookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHookResponse) ProtoMessage() {}

func (x *UpdateHookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_hooks_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHookResponse.ProtoReflect.Descriptor instead.
func (*UpdateHookResponse) Descriptor() ([]byte, []int) {
	return file_core_v1_hooks_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateHookResponse) GetHook() *Hook {
	if x != nil {
		return x.Hook
	}
	return nil
}

type DeleteHookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteHookRequest) Reset() {
	*x = DeleteHookRequest{}
	mi := &file_core_v1_hooks_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteHookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHookRequest) ProtoMessage() {}

func (x *DeleteHookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_hooks_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHookRequest.ProtoReflect.Descriptor instead.
func (*DeleteHookRequest) Descriptor() ([]byte, []int) {
	return file_core_v1_hooks_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteHookRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteHookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteHookResponse) Reset() {
	*x = DeleteHookResponse{}
	mi := &file_core_v1_hooks_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteHookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHookResponse) ProtoMessage() {}

func (x *DeleteHookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_hooks_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHookResponse.ProtoReflect.Descriptor instead.
func (*DeleteHookResponse) Descriptor() ([]byte, []int) {
	return file_core_v1_hooks_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteHookResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_core_v1_hooks_proto protoreflect.FileDescriptor

const file_core_v1_hooks_proto_rawDesc = "" +
	"\n" +
	"\x13core/v1/hooks.proto\x12\acore.v1\x1a\x1bbuf/validate/validate.proto\x1a\x14core/v1/filter.proto\x1a\x1bcore/v1/list_metadata.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb7\x04\n" +
	"\x04Hook\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x02id\x125\n" +
	"\x04name\x18\x02 \x01(\tB!\xbaH\x1er\x1c\x10\x012\x18^[A-Za-z_][A-Za-z0-9_]*$R\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\x04code\x18\x04 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04code\x12,\n" +
	"\x06status\x18\x05 \x01(\tB\x14\xbaH\x11r\x0fR\x05draftR\x06activeR\x06status\x12*\n" +
	"\n" +
	"timeout_ms\x18\x06 \x01(\x05B\v\xbaH\b\x1a\x06\x18\xe0\xd4\x03 \x00R\ttimeoutMs\x12C\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampB\b\xbaH\x05\xb2\x01\x028\x01R\tcreatedAt\x12C\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampB\b\xbaH\x05\xb2\x01\x028\x01R\tupdatedAt\x12r\n" +
	"!allowlisted_environment_variables\x18\t \x03(\tB&\xbaH#\x92\x01 \"\x1er\x1c\x10\x012\x18^[A-Za-z_][A-Za-z0-9_]*$R\x1fallowlistedEnvironmentVariables\x12H\n" +
	"\x19allowlisted_network_hosts\x18\n" +
	" \x03(\tB\f\xbaH\t\x92\x01\x06\"\x04r\x02\x10\x01R\x17allowlistedNetworkHosts\"\xa1\x03\n" +
	"\x11CreateHookRequest\x125\n" +
	"\x04name\x18\x01 \x01(\tB!\xbaH\x1er\x1c\x10\x012\x18^[A-Za-z_][A-Za-z0-9_]*$R\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1b\n" +
	"\x04code\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04code\x12,\n" +
	"\x06status\x18\x04 \x01(\tB\x14\xbaH\x11r\x0fR\x05draftR\x06activeR\x06status\x12*\n" +
	"\n" +
	"timeout_ms\x18\x05 \x01(\x05B\v\xbaH\b\x1a\x06\x18\xe0\xd4\x03 \x00R\ttimeoutMs\x12r\n" +
	"!allowlisted_environment_variables\x18\x06 \x03(\tB&\xbaH#\x92\x01 \"\x1er\x1c\x10\x012\x18^[A-Za-z_][A-Za-z0-9_]*$R\x1fallowlistedEnvironmentVariables\x12H\n" +
	"\x19allowlisted_network_hosts\x18\a \x03(\tB\f\xbaH\t\x92\x01\x06\"\x04r\x02\x10\x01R\x17allowlistedNetworkHosts\"7\n" +
	"\x12CreateHookResponse\x12!\n" +
	"\x04hook\x18\x01 \x01(\v2\r.core.v1.HookR\x04hook\"\xff\x01\n" +
	"\x10ListHooksRequest\x12 \n" +
	"\x05limit\x18\x01 \x01(\x05B\n" +
	"\xbaH\a\x1a\x05\x18\xf4\x03 \x00R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\x12\x14\n" +
	"\x05order\x18\x03 \x01(\tR\x05order\x12\x16\n" +
	"\x06search\x18\x04 \x01(\tR\x06search\x12J\n" +
	"\rsearch_fields\x18\x05 \x03(\tB%\xbaH\"\x92\x01\x1f\"\x1dr\x1bR\x04nameR\vdescriptionR\x06statusR\fsearchFields\x12,\n" +
	"\x06filter\x18\x06 \x01(\v2\x0f.core.v1.FilterH\x00R\x06filter\x88\x01\x01B\t\n" +
	"\a_filter\"t\n" +
	"\x11ListHooksResponse\x12#\n" +
	"\x05hooks\x18\x01 \x03(\v2\r.core.v1.HookR\x05hooks\x12:\n" +
	"\rlist_metadata\x18\x02 \x01(\v2\x15.core.v1.ListMetadataR\flistMetadata\")\n" +
	"\x0eGetHookRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x02id\"4\n" +
	"\x0fGetHookResponse\x12!\n" +
	"\x04hook\x18\x01 \x01(\v2\r.core.v1.HookR\x04hook\">\n" +
	"\x11UpdateHookRequest\x12)\n" +
	"\x04hook\x18\x01 \x01(\v2\r.core.v1.HookB\x06\xbaH\x03\xc8\x01\x01R\x04hook\"7\n" +
	"\x12UpdateHookResponse\x12!\n" +
	"\x04hook\x18\x01 \x01(\v2\r.core.v1.HookR\x04hook\",\n" +
	"\x11DeleteHookRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x02id\"-\n" +
	"\x12DeleteHookResponse\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x02id2\xc2\x04\n" +
	"\vHookService\x12q\n" +
	"\n" +
	"CreateHook\x12\x1a.core.v1.CreateHookRequest\x1a\x1b.core.v1.CreateHookResponse\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/core.v1.HookService/CreateHook\x12p\n" +
	"\tListHooks\x12\x19.core.v1.ListHooksRequest\x1a\x1a.core.v1.ListHooksResponse\",\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/core.v1.HookService/ListHooks\x90\x02\x01\x12h\n" +
	"\aGetHook\x12\x17.core.v1.GetHookRequest\x1a\x18.core.v1.GetHookResponse\"*\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/core.v1.HookService/GetHook\x90\x02\x01\x12q\n" +
	"\n" +
	"UpdateHook\x12\x1a.core.v1.UpdateHookRequest\x1a\x1b.core.v1.UpdateHookResponse\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/core.v1.HookService/UpdateHook\x12q\n" +
	"\n" +
	"DeleteHook\x12\x1a.core.v1.DeleteHookRequest\x1a\x1b.core.v1.DeleteHookResponse\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/core.v1.HookService/DeleteHookB\x84\x01\n" +
	"\vcom.core.v1B\n" +
	"HooksProtoP\x01Z,github.com/formalco/go-sdk/v3/core/v1;corev1\xa2\x02\x03CXX\xaa\x02\aCore.V1\xca\x02\aCore\\V1\xe2\x02\x13Core\\V1\\GPBMetadata\xea\x02\bCore::V1b\x06proto3"

var (
	file_core_v1_hooks_proto_rawDescOnce sync.Once
	file_core_v1_hooks_proto_rawDescData []byte
)

func file_core_v1_hooks_proto_rawDescGZIP() []byte {
	file_core_v1_hooks_proto_rawDescOnce.Do(func() {
		file_core_v1_hooks_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_v1_hooks_proto_rawDesc), len(file_core_v1_hooks_proto_rawDesc)))
	})
	return file_core_v1_hooks_proto_rawDescData
}

var file_core_v1_hooks_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_core_v1_hooks_proto_goTypes = []any{
	(*Hook)(nil),                  // 0: core.v1.Hook
	(*CreateHookRequest)(nil),     // 1: core.v1.CreateHookRequest
	(*CreateHookResponse)(nil),    // 2: core.v1.CreateHookResponse
	(*ListHooksRequest)(nil),      // 3: core.v1.ListHooksRequest
	(*ListHooksResponse)(nil),     // 4: core.v1.ListHooksResponse
	(*GetHookRequest)(nil),        // 5: core.v1.GetHookRequest
	(*GetHookResponse)(nil),       // 6: core.v1.GetHookResponse
	(*UpdateHookRequest)(nil),     // 7: core.v1.UpdateHookRequest
	(*UpdateHookResponse)(nil),    // 8: core.v1.UpdateHookResponse
	(*DeleteHookRequest)(nil),     // 9: core.v1.DeleteHookRequest
	(*DeleteHookResponse)(nil),    // 10: core.v1.DeleteHookResponse
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
	(*Filter)(nil),                // 12: core.v1.Filter
	(*ListMetadata)(nil),          // 13: core.v1.ListMetadata
}
var file_core_v1_hooks_proto_depIdxs = []int32{
	11, // 0: core.v1.Hook.created_at:type_name -> google.protobuf.Timestamp
	11, // 1: core.v1.Hook.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: core.v1.CreateHookResponse.hook:type_name -> core.v1.Hook
	12, // 3: core.v1.ListHooksRequest.filter:type_name -> core.v1.Filter
	0,  // 4: core.v1.ListHooksResponse.hooks:type_name -> core.v1.Hook
	13, // 5: core.v1.ListHooksResponse.list_metadata:type_name -> core.v1.ListMetadata
	0,  // 6: core.v1.GetHookResponse.hook:type_name -> core.v1.Hook
	0,  // 7: core.v1.UpdateHookRequest.hook:type_name -> core.v1.Hook
	0,  // 8: core.v1.UpdateHookResponse.hook:type_name -> core.v1.Hook
	1,  // 9: core.v1.HookService.CreateHook:input_type -> core.v1.CreateHookRequest
	3,  // 10: core.v1.HookService.ListHooks:input_type -> core.v1.ListHooksRequest
	5,  // 11: core.v1.HookService.GetHook:input_type -> core.v1.GetHookRequest
	7,  // 12: core.v1.HookService.UpdateHook:input_type -> core.v1.UpdateHookRequest
	9,  // 13: core.v1.HookService.DeleteHook:input_type -> core.v1.DeleteHookRequest
	2,  // 14: core.v1.HookService.CreateHook:output_type -> core.v1.CreateHookResponse
	4,  // 15: core.v1.HookService.ListHooks:output_type -> core.v1.ListHooksResponse
	6,  // 16: core.v1.HookService.GetHook:output_type -> core.v1.GetHookResponse
	8,  // 17: core.v1.HookService.UpdateHook:output_type -> core.v1.UpdateHookResponse
	10, // 18: core.v1.HookService.DeleteHook:output_type -> core.v1.DeleteHookResponse
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_core_v1_hooks_proto_init() }
func file_core_v1_hooks_proto_init() {
	if File_core_v1_hooks_proto != nil {
		return
	}
	file_core_v1_filter_proto_init()
	file_core_v1_list_metadata_proto_init()
	file_core_v1_hooks_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_v1_hooks_proto_rawDesc), len(file_core_v1_hooks_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_v1_hooks_proto_goTypes,
		DependencyIndexes: file_core_v1_hooks_proto_depIdxs,
		MessageInfos:      file_core_v1_hooks_proto_msgTypes,
	}.Build()
	File_core_v1_hooks_proto = out.File
	file_core_v1_hooks_proto_goTypes = nil
	file_core_v1_hooks_proto_depIdxs = nil
}
