// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        (unknown)
// source: core/v1/permissions.proto

package corev1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Permission struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description           string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Code                  string                 `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	Status                string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	TerminationProtection bool                   `protobuf:"varint,6,opt,name=termination_protection,json=terminationProtection,proto3" json:"termination_protection,omitempty"`
	CreatedAt             *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt             *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Permission) Reset() {
	*x = Permission{}
	mi := &file_core_v1_permissions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Permission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Permission) ProtoMessage() {}

func (x *Permission) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_permissions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Permission.ProtoReflect.Descriptor instead.
func (*Permission) Descriptor() ([]byte, []int) {
	return file_core_v1_permissions_proto_rawDescGZIP(), []int{0}
}

func (x *Permission) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Permission) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Permission) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Permission) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Permission) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Permission) GetTerminationProtection() bool {
	if x != nil {
		return x.TerminationProtection
	}
	return false
}

func (x *Permission) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Permission) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListPermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Order         string                 `protobuf:"bytes,3,opt,name=order,proto3" json:"order,omitempty"`
	Search        string                 `protobuf:"bytes,4,opt,name=search,proto3" json:"search,omitempty"`
	SearchFields  []string               `protobuf:"bytes,5,rep,name=search_fields,json=searchFields,proto3" json:"search_fields,omitempty"`
	Filter        *Filter                `protobuf:"bytes,6,opt,name=filter,proto3,oneof" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPermissionsRequest) Reset() {
	*x = ListPermissionsRequest{}
	mi := &file_core_v1_permissions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermissionsRequest) ProtoMessage() {}

func (x *ListPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_permissions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermissionsRequest.ProtoReflect.Descriptor instead.
func (*ListPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_core_v1_permissions_proto_rawDescGZIP(), []int{1}
}

func (x *ListPermissionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListPermissionsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListPermissionsRequest) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

func (x *ListPermissionsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListPermissionsRequest) GetSearchFields() []string {
	if x != nil {
		return x.SearchFields
	}
	return nil
}

func (x *ListPermissionsRequest) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type ListPermissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permissions   []*Permission          `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
	ListMetadata  *ListMetadata          `protobuf:"bytes,2,opt,name=list_metadata,json=listMetadata,proto3" json:"list_metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPermissionsResponse) Reset() {
	*x = ListPermissionsResponse{}
	mi := &file_core_v1_permissions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermissionsResponse) ProtoMessage() {}

func (x *ListPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_permissions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermissionsResponse.ProtoReflect.Descriptor instead.
func (*ListPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_core_v1_permissions_proto_rawDescGZIP(), []int{2}
}

func (x *ListPermissionsResponse) GetPermissions() []*Permission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *ListPermissionsResponse) GetListMetadata() *ListMetadata {
	if x != nil {
		return x.ListMetadata
	}
	return nil
}

type GetPermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPermissionRequest) Reset() {
	*x = GetPermissionRequest{}
	mi := &file_core_v1_permissions_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPermissionRequest) ProtoMessage() {}

func (x *GetPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_permissions_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPermissionRequest.ProtoReflect.Descriptor instead.
func (*GetPermissionRequest) Descriptor() ([]byte, []int) {
	return file_core_v1_permissions_proto_rawDescGZIP(), []int{3}
}

func (x *GetPermissionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetPermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permission    *Permission            `protobuf:"bytes,1,opt,name=permission,proto3" json:"permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPermissionResponse) Reset() {
	*x = GetPermissionResponse{}
	mi := &file_core_v1_permissions_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPermissionResponse) ProtoMessage() {}

func (x *GetPermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_permissions_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPermissionResponse.ProtoReflect.Descriptor instead.
func (*GetPermissionResponse) Descriptor() ([]byte, []int) {
	return file_core_v1_permissions_proto_rawDescGZIP(), []int{4}
}

func (x *GetPermissionResponse) GetPermission() *Permission {
	if x != nil {
		return x.Permission
	}
	return nil
}

type CreatePermissionRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Name                  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description           string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Code                  string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Status                string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	TerminationProtection bool                   `protobuf:"varint,5,opt,name=termination_protection,json=terminationProtection,proto3" json:"termination_protection,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CreatePermissionRequest) Reset() {
	*x = CreatePermissionRequest{}
	mi := &file_core_v1_permissions_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePermissionRequest) ProtoMessage() {}

func (x *CreatePermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_permissions_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePermissionRequest.ProtoReflect.Descriptor instead.
func (*CreatePermissionRequest) Descriptor() ([]byte, []int) {
	return file_core_v1_permissions_proto_rawDescGZIP(), []int{5}
}

func (x *CreatePermissionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePermissionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreatePermissionRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreatePermissionRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreatePermissionRequest) GetTerminationProtection() bool {
	if x != nil {
		return x.TerminationProtection
	}
	return false
}

type CreatePermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permission    *Permission            `protobuf:"bytes,1,opt,name=permission,proto3" json:"permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePermissionResponse) Reset() {
	*x = CreatePermissionResponse{}
	mi := &file_core_v1_permissions_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePermissionResponse) ProtoMessage() {}

func (x *CreatePermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_permissions_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePermissionResponse.ProtoReflect.Descriptor instead.
func (*CreatePermissionResponse) Descriptor() ([]byte, []int) {
	return file_core_v1_permissions_proto_rawDescGZIP(), []int{6}
}

func (x *CreatePermissionResponse) GetPermission() *Permission {
	if x != nil {
		return x.Permission
	}
	return nil
}

type UpdatePermissionRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description           string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Code                  string                 `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	Status                string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	TerminationProtection bool                   `protobuf:"varint,6,opt,name=termination_protection,json=terminationProtection,proto3" json:"termination_protection,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *UpdatePermissionRequest) Reset() {
	*x = UpdatePermissionRequest{}
	mi := &file_core_v1_permissions_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePermissionRequest) ProtoMessage() {}

func (x *UpdatePermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_permissions_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePermissionRequest.ProtoReflect.Descriptor instead.
func (*UpdatePermissionRequest) Descriptor() ([]byte, []int) {
	return file_core_v1_permissions_proto_rawDescGZIP(), []int{7}
}

func (x *UpdatePermissionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatePermissionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdatePermissionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdatePermissionRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UpdatePermissionRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdatePermissionRequest) GetTerminationProtection() bool {
	if x != nil {
		return x.TerminationProtection
	}
	return false
}

type UpdatePermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permission    *Permission            `protobuf:"bytes,1,opt,name=permission,proto3" json:"permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePermissionResponse) Reset() {
	*x = UpdatePermissionResponse{}
	mi := &file_core_v1_permissions_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePermissionResponse) ProtoMessage() {}

func (x *UpdatePermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_permissions_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePermissionResponse.ProtoReflect.Descriptor instead.
func (*UpdatePermissionResponse) Descriptor() ([]byte, []int) {
	return file_core_v1_permissions_proto_rawDescGZIP(), []int{8}
}

func (x *UpdatePermissionResponse) GetPermission() *Permission {
	if x != nil {
		return x.Permission
	}
	return nil
}

type UpdatePermissionV2Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permission    *Permission            `protobuf:"bytes,1,opt,name=permission,proto3" json:"permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePermissionV2Request) Reset() {
	*x = UpdatePermissionV2Request{}
	mi := &file_core_v1_permissions_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePermissionV2Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePermissionV2Request) ProtoMessage() {}

func (x *UpdatePermissionV2Request) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_permissions_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePermissionV2Request.ProtoReflect.Descriptor instead.
func (*UpdatePermissionV2Request) Descriptor() ([]byte, []int) {
	return file_core_v1_permissions_proto_rawDescGZIP(), []int{9}
}

func (x *UpdatePermissionV2Request) GetPermission() *Permission {
	if x != nil {
		return x.Permission
	}
	return nil
}

type UpdatePermissionV2Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permission    *Permission            `protobuf:"bytes,1,opt,name=permission,proto3" json:"permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePermissionV2Response) Reset() {
	*x = UpdatePermissionV2Response{}
	mi := &file_core_v1_permissions_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePermissionV2Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePermissionV2Response) ProtoMessage() {}

func (x *UpdatePermissionV2Response) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_permissions_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePermissionV2Response.ProtoReflect.Descriptor instead.
func (*UpdatePermissionV2Response) Descriptor() ([]byte, []int) {
	return file_core_v1_permissions_proto_rawDescGZIP(), []int{10}
}

func (x *UpdatePermissionV2Response) GetPermission() *Permission {
	if x != nil {
		return x.Permission
	}
	return nil
}

type DeletePermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePermissionRequest) Reset() {
	*x = DeletePermissionRequest{}
	mi := &file_core_v1_permissions_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePermissionRequest) ProtoMessage() {}

func (x *DeletePermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_permissions_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePermissionRequest.ProtoReflect.Descriptor instead.
func (*DeletePermissionRequest) Descriptor() ([]byte, []int) {
	return file_core_v1_permissions_proto_rawDescGZIP(), []int{11}
}

func (x *DeletePermissionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeletePermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePermissionResponse) Reset() {
	*x = DeletePermissionResponse{}
	mi := &file_core_v1_permissions_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePermissionResponse) ProtoMessage() {}

func (x *DeletePermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_permissions_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePermissionResponse.ProtoReflect.Descriptor instead.
func (*DeletePermissionResponse) Descriptor() ([]byte, []int) {
	return file_core_v1_permissions_proto_rawDescGZIP(), []int{12}
}

func (x *DeletePermissionResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_core_v1_permissions_proto protoreflect.FileDescriptor

const file_core_v1_permissions_proto_rawDesc = "" +
	"\n" +
	"\x19core/v1/permissions.proto\x12\acore.v1\x1a\x1bbuf/validate/validate.proto\x1a\x14core/v1/filter.proto\x1a\x1bcore/v1/list_metadata.proto\x1a\x13core/v1/types.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf0\x02\n" +
	"\n" +
	"Permission\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x02id\x12\x1b\n" +
	"\x04name\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04name\x12)\n" +
	"\vdescription\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\vdescription\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04code\x12,\n" +
	"\x06status\x18\x05 \x01(\tB\x14\xbaH\x11r\x0fR\x05draftR\x06activeR\x06status\x125\n" +
	"\x16termination_protection\x18\x06 \x01(\bR\x15terminationProtection\x12C\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampB\b\xbaH\x05\xb2\x01\x028\x01R\tcreatedAt\x12C\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampB\b\xbaH\x05\xb2\x01\x028\x01R\tupdatedAt\"\x89\x02\n" +
	"\x16ListPermissionsRequest\x12 \n" +
	"\x05limit\x18\x01 \x01(\x05B\n" +
	"\xbaH\a\x1a\x05\x18\xf4\x03 \x00R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\x12\x14\n" +
	"\x05order\x18\x03 \x01(\tR\x05order\x12\x16\n" +
	"\x06search\x18\x04 \x01(\tR\x06search\x12N\n" +
	"\rsearch_fields\x18\x05 \x03(\tB)\xbaH&\x92\x01#\"!r\x1fR\x02idR\x04nameR\vdescriptionR\x06statusR\fsearchFields\x12,\n" +
	"\x06filter\x18\x06 \x01(\v2\x0f.core.v1.FilterH\x00R\x06filter\x88\x01\x01B\t\n" +
	"\a_filter\"\x8c\x01\n" +
	"\x17ListPermissionsResponse\x125\n" +
	"\vpermissions\x18\x01 \x03(\v2\x13.core.v1.PermissionR\vpermissions\x12:\n" +
	"\rlist_metadata\x18\x02 \x01(\v2\x15.core.v1.ListMetadataR\flistMetadata\"/\n" +
	"\x14GetPermissionRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x02id\"L\n" +
	"\x15GetPermissionResponse\x123\n" +
	"\n" +
	"permission\x18\x01 \x01(\v2\x13.core.v1.PermissionR\n" +
	"permission\"\xe3\x01\n" +
	"\x17CreatePermissionRequest\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04name\x12)\n" +
	"\vdescription\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\vdescription\x12\x1b\n" +
	"\x04code\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04code\x12,\n" +
	"\x06status\x18\x04 \x01(\tB\x14\xbaH\x11r\x0fR\x05draftR\x06activeR\x06status\x125\n" +
	"\x16termination_protection\x18\x05 \x01(\bR\x15terminationProtection\"O\n" +
	"\x18CreatePermissionResponse\x123\n" +
	"\n" +
	"permission\x18\x01 \x01(\v2\x13.core.v1.PermissionR\n" +
	"permission\"\xf3\x01\n" +
	"\x17UpdatePermissionRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x02id\x12\x1b\n" +
	"\x04name\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04name\x12)\n" +
	"\vdescription\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\vdescription\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04code\x12,\n" +
	"\x06status\x18\x05 \x01(\tB\x14\xbaH\x11r\x0fR\x05draftR\x06activeR\x06status\x125\n" +
	"\x16termination_protection\x18\x06 \x01(\bR\x15terminationProtection\"O\n" +
	"\x18UpdatePermissionResponse\x123\n" +
	"\n" +
	"permission\x18\x01 \x01(\v2\x13.core.v1.PermissionR\n" +
	"permission\"X\n" +
	"\x19UpdatePermissionV2Request\x12;\n" +
	"\n" +
	"permission\x18\x01 \x01(\v2\x13.core.v1.PermissionB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"permission\"Q\n" +
	"\x1aUpdatePermissionV2Response\x123\n" +
	"\n" +
	"permission\x18\x01 \x01(\v2\x13.core.v1.PermissionR\n" +
	"permission\"2\n" +
	"\x17DeletePermissionRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x02id\"3\n" +
	"\x18DeletePermissionResponse\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x02id2\xf0\x04\n" +
	"\x12PermissionsService\x12Y\n" +
	"\x0fListPermissions\x12\x1f.core.v1.ListPermissionsRequest\x1a .core.v1.ListPermissionsResponse\"\x03\x90\x02\x01\x12S\n" +
	"\rGetPermission\x12\x1d.core.v1.GetPermissionRequest\x1a\x1e.core.v1.GetPermissionResponse\"\x03\x90\x02\x01\x12Y\n" +
	"\x10CreatePermission\x12 .core.v1.CreatePermissionRequest\x1a!.core.v1.CreatePermissionResponse\"\x00\x12Y\n" +
	"\x10UpdatePermission\x12 .core.v1.UpdatePermissionRequest\x1a!.core.v1.UpdatePermissionResponse\"\x00\x12\x98\x01\n" +
	"\x12UpdatePermissionV2\x12\".core.v1.UpdatePermissionV2Request\x1a#.core.v1.UpdatePermissionV2Response\"9\x82\xd3\xe4\x93\x023:\x01*\"./core.v1.PermissionsService/UpdatePermissionV2\x12Y\n" +
	"\x10DeletePermission\x12 .core.v1.DeletePermissionRequest\x1a!.core.v1.DeletePermissionResponse\"\x00B\x8a\x01\n" +
	"\vcom.core.v1B\x10PermissionsProtoP\x01Z,github.com/formalco/go-sdk/v3/core/v1;corev1\xa2\x02\x03CXX\xaa\x02\aCore.V1\xca\x02\aCore\\V1\xe2\x02\x13Core\\V1\\GPBMetadata\xea\x02\bCore::V1b\x06proto3"

var (
	file_core_v1_permissions_proto_rawDescOnce sync.Once
	file_core_v1_permissions_proto_rawDescData []byte
)

func file_core_v1_permissions_proto_rawDescGZIP() []byte {
	file_core_v1_permissions_proto_rawDescOnce.Do(func() {
		file_core_v1_permissions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_v1_permissions_proto_rawDesc), len(file_core_v1_permissions_proto_rawDesc)))
	})
	return file_core_v1_permissions_proto_rawDescData
}

var file_core_v1_permissions_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_core_v1_permissions_proto_goTypes = []any{
	(*Permission)(nil),                 // 0: core.v1.Permission
	(*ListPermissionsRequest)(nil),     // 1: core.v1.ListPermissionsRequest
	(*ListPermissionsResponse)(nil),    // 2: core.v1.ListPermissionsResponse
	(*GetPermissionRequest)(nil),       // 3: core.v1.GetPermissionRequest
	(*GetPermissionResponse)(nil),      // 4: core.v1.GetPermissionResponse
	(*CreatePermissionRequest)(nil),    // 5: core.v1.CreatePermissionRequest
	(*CreatePermissionResponse)(nil),   // 6: core.v1.CreatePermissionResponse
	(*UpdatePermissionRequest)(nil),    // 7: core.v1.UpdatePermissionRequest
	(*UpdatePermissionResponse)(nil),   // 8: core.v1.UpdatePermissionResponse
	(*UpdatePermissionV2Request)(nil),  // 9: core.v1.UpdatePermissionV2Request
	(*UpdatePermissionV2Response)(nil), // 10: core.v1.UpdatePermissionV2Response
	(*DeletePermissionRequest)(nil),    // 11: core.v1.DeletePermissionRequest
	(*DeletePermissionResponse)(nil),   // 12: core.v1.DeletePermissionResponse
	(*timestamppb.Timestamp)(nil),      // 13: google.protobuf.Timestamp
	(*Filter)(nil),                     // 14: core.v1.Filter
	(*ListMetadata)(nil),               // 15: core.v1.ListMetadata
}
var file_core_v1_permissions_proto_depIdxs = []int32{
	13, // 0: core.v1.Permission.created_at:type_name -> google.protobuf.Timestamp
	13, // 1: core.v1.Permission.updated_at:type_name -> google.protobuf.Timestamp
	14, // 2: core.v1.ListPermissionsRequest.filter:type_name -> core.v1.Filter
	0,  // 3: core.v1.ListPermissionsResponse.permissions:type_name -> core.v1.Permission
	15, // 4: core.v1.ListPermissionsResponse.list_metadata:type_name -> core.v1.ListMetadata
	0,  // 5: core.v1.GetPermissionResponse.permission:type_name -> core.v1.Permission
	0,  // 6: core.v1.CreatePermissionResponse.permission:type_name -> core.v1.Permission
	0,  // 7: core.v1.UpdatePermissionResponse.permission:type_name -> core.v1.Permission
	0,  // 8: core.v1.UpdatePermissionV2Request.permission:type_name -> core.v1.Permission
	0,  // 9: core.v1.UpdatePermissionV2Response.permission:type_name -> core.v1.Permission
	1,  // 10: core.v1.PermissionsService.ListPermissions:input_type -> core.v1.ListPermissionsRequest
	3,  // 11: core.v1.PermissionsService.GetPermission:input_type -> core.v1.GetPermissionRequest
	5,  // 12: core.v1.PermissionsService.CreatePermission:input_type -> core.v1.CreatePermissionRequest
	7,  // 13: core.v1.PermissionsService.UpdatePermission:input_type -> core.v1.UpdatePermissionRequest
	9,  // 14: core.v1.PermissionsService.UpdatePermissionV2:input_type -> core.v1.UpdatePermissionV2Request
	11, // 15: core.v1.PermissionsService.DeletePermission:input_type -> core.v1.DeletePermissionRequest
	2,  // 16: core.v1.PermissionsService.ListPermissions:output_type -> core.v1.ListPermissionsResponse
	4,  // 17: core.v1.PermissionsService.GetPermission:output_type -> core.v1.GetPermissionResponse
	6,  // 18: core.v1.PermissionsService.CreatePermission:output_type -> core.v1.CreatePermissionResponse
	8,  // 19: core.v1.PermissionsService.UpdatePermission:output_type -> core.v1.UpdatePermissionResponse
	10, // 20: core.v1.PermissionsService.UpdatePermissionV2:output_type -> core.v1.UpdatePermissionV2Response
	12, // 21: core.v1.PermissionsService.DeletePermission:output_type -> core.v1.DeletePermissionResponse
	16, // [16:22] is the sub-list for method output_type
	10, // [10:16] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_core_v1_permissions_proto_init() }
func file_core_v1_permissions_proto_init() {
	if File_core_v1_permissions_proto != nil {
		return
	}
	file_core_v1_filter_proto_init()
	file_core_v1_list_metadata_proto_init()
	file_core_v1_types_proto_init()
	file_core_v1_permissions_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_v1_permissions_proto_rawDesc), len(file_core_v1_permissions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_v1_permissions_proto_goTypes,
		DependencyIndexes: file_core_v1_permissions_proto_depIdxs,
		MessageInfos:      file_core_v1_permissions_proto_msgTypes,
	}.Build()
	File_core_v1_permissions_proto = out.File
	file_core_v1_permissions_proto_goTypes = nil
	file_core_v1_permissions_proto_depIdxs = nil
}
