// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        (unknown)
// source: core/v1/scenario_monitoring.proto

package corev1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for creating an SSH scenario monitor
type CreateScenarioMonitorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Scenario      string                 `protobuf:"bytes,2,opt,name=scenario,proto3" json:"scenario,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateScenarioMonitorRequest) Reset() {
	*x = CreateScenarioMonitorRequest{}
	mi := &file_core_v1_scenario_monitoring_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateScenarioMonitorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScenarioMonitorRequest) ProtoMessage() {}

func (x *CreateScenarioMonitorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_scenario_monitoring_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScenarioMonitorRequest.ProtoReflect.Descriptor instead.
func (*CreateScenarioMonitorRequest) Descriptor() ([]byte, []int) {
	return file_core_v1_scenario_monitoring_proto_rawDescGZIP(), []int{0}
}

func (x *CreateScenarioMonitorRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateScenarioMonitorRequest) GetScenario() string {
	if x != nil {
		return x.Scenario
	}
	return ""
}

func (x *CreateScenarioMonitorRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Response message for creating an SSH scenario monitor
type CreateScenarioMonitorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateScenarioMonitorResponse) Reset() {
	*x = CreateScenarioMonitorResponse{}
	mi := &file_core_v1_scenario_monitoring_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateScenarioMonitorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScenarioMonitorResponse) ProtoMessage() {}

func (x *CreateScenarioMonitorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_scenario_monitoring_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScenarioMonitorResponse.ProtoReflect.Descriptor instead.
func (*CreateScenarioMonitorResponse) Descriptor() ([]byte, []int) {
	return file_core_v1_scenario_monitoring_proto_rawDescGZIP(), []int{1}
}

func (x *CreateScenarioMonitorResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Request message for deleting a scenario monitor
type DeleteScenarioMonitorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteScenarioMonitorRequest) Reset() {
	*x = DeleteScenarioMonitorRequest{}
	mi := &file_core_v1_scenario_monitoring_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteScenarioMonitorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteScenarioMonitorRequest) ProtoMessage() {}

func (x *DeleteScenarioMonitorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_scenario_monitoring_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteScenarioMonitorRequest.ProtoReflect.Descriptor instead.
func (*DeleteScenarioMonitorRequest) Descriptor() ([]byte, []int) {
	return file_core_v1_scenario_monitoring_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteScenarioMonitorRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Response message for deleting an SSH scenario monitor
type DeleteScenarioMonitorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteScenarioMonitorResponse) Reset() {
	*x = DeleteScenarioMonitorResponse{}
	mi := &file_core_v1_scenario_monitoring_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteScenarioMonitorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteScenarioMonitorResponse) ProtoMessage() {}

func (x *DeleteScenarioMonitorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_scenario_monitoring_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteScenarioMonitorResponse.ProtoReflect.Descriptor instead.
func (*DeleteScenarioMonitorResponse) Descriptor() ([]byte, []int) {
	return file_core_v1_scenario_monitoring_proto_rawDescGZIP(), []int{3}
}

// Request message for getting all SSH scenario monitors
type GetScenarioMonitorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScenarioMonitorRequest) Reset() {
	*x = GetScenarioMonitorRequest{}
	mi := &file_core_v1_scenario_monitoring_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScenarioMonitorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScenarioMonitorRequest) ProtoMessage() {}

func (x *GetScenarioMonitorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_scenario_monitoring_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScenarioMonitorRequest.ProtoReflect.Descriptor instead.
func (*GetScenarioMonitorRequest) Descriptor() ([]byte, []int) {
	return file_core_v1_scenario_monitoring_proto_rawDescGZIP(), []int{4}
}

func (x *GetScenarioMonitorRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Response message for getting all SSH scenario monitors
type GetScenarioMonitorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Monitor       *ScenarioMonitor       `protobuf:"bytes,1,opt,name=monitor,proto3" json:"monitor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScenarioMonitorResponse) Reset() {
	*x = GetScenarioMonitorResponse{}
	mi := &file_core_v1_scenario_monitoring_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScenarioMonitorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScenarioMonitorResponse) ProtoMessage() {}

func (x *GetScenarioMonitorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_scenario_monitoring_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScenarioMonitorResponse.ProtoReflect.Descriptor instead.
func (*GetScenarioMonitorResponse) Descriptor() ([]byte, []int) {
	return file_core_v1_scenario_monitoring_proto_rawDescGZIP(), []int{5}
}

func (x *GetScenarioMonitorResponse) GetMonitor() *ScenarioMonitor {
	if x != nil {
		return x.Monitor
	}
	return nil
}

// Request message for listing all SSH scenario monitors
type ListScenarioMonitorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Order         string                 `protobuf:"bytes,3,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScenarioMonitorsRequest) Reset() {
	*x = ListScenarioMonitorsRequest{}
	mi := &file_core_v1_scenario_monitoring_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScenarioMonitorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScenarioMonitorsRequest) ProtoMessage() {}

func (x *ListScenarioMonitorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_scenario_monitoring_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScenarioMonitorsRequest.ProtoReflect.Descriptor instead.
func (*ListScenarioMonitorsRequest) Descriptor() ([]byte, []int) {
	return file_core_v1_scenario_monitoring_proto_rawDescGZIP(), []int{6}
}

func (x *ListScenarioMonitorsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListScenarioMonitorsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListScenarioMonitorsRequest) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

// Response message for listing all SSH scenario monitors
type ListScenarioMonitorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Monitors      []*ScenarioMonitor     `protobuf:"bytes,1,rep,name=monitors,proto3" json:"monitors,omitempty"`
	ListMetadata  *ListMetadata          `protobuf:"bytes,2,opt,name=list_metadata,json=listMetadata,proto3" json:"list_metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScenarioMonitorsResponse) Reset() {
	*x = ListScenarioMonitorsResponse{}
	mi := &file_core_v1_scenario_monitoring_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScenarioMonitorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScenarioMonitorsResponse) ProtoMessage() {}

func (x *ListScenarioMonitorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_scenario_monitoring_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScenarioMonitorsResponse.ProtoReflect.Descriptor instead.
func (*ListScenarioMonitorsResponse) Descriptor() ([]byte, []int) {
	return file_core_v1_scenario_monitoring_proto_rawDescGZIP(), []int{7}
}

func (x *ListScenarioMonitorsResponse) GetMonitors() []*ScenarioMonitor {
	if x != nil {
		return x.Monitors
	}
	return nil
}

func (x *ListScenarioMonitorsResponse) GetListMetadata() *ListMetadata {
	if x != nil {
		return x.ListMetadata
	}
	return nil
}

// Scenario Monitor entity
type ScenarioMonitor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Scenario      string                 `protobuf:"bytes,3,opt,name=scenario,proto3" json:"scenario,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScenarioMonitor) Reset() {
	*x = ScenarioMonitor{}
	mi := &file_core_v1_scenario_monitoring_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScenarioMonitor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScenarioMonitor) ProtoMessage() {}

func (x *ScenarioMonitor) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_scenario_monitoring_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScenarioMonitor.ProtoReflect.Descriptor instead.
func (*ScenarioMonitor) Descriptor() ([]byte, []int) {
	return file_core_v1_scenario_monitoring_proto_rawDescGZIP(), []int{8}
}

func (x *ScenarioMonitor) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ScenarioMonitor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ScenarioMonitor) GetScenario() string {
	if x != nil {
		return x.Scenario
	}
	return ""
}

func (x *ScenarioMonitor) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ScenarioMonitor) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ScenarioMonitor) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Request message for updating a scenario monitor
type UpdateScenarioMonitorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Scenario      *string                `protobuf:"bytes,3,opt,name=scenario,proto3,oneof" json:"scenario,omitempty"`
	Status        *string                `protobuf:"bytes,4,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateScenarioMonitorRequest) Reset() {
	*x = UpdateScenarioMonitorRequest{}
	mi := &file_core_v1_scenario_monitoring_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateScenarioMonitorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateScenarioMonitorRequest) ProtoMessage() {}

func (x *UpdateScenarioMonitorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_scenario_monitoring_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateScenarioMonitorRequest.ProtoReflect.Descriptor instead.
func (*UpdateScenarioMonitorRequest) Descriptor() ([]byte, []int) {
	return file_core_v1_scenario_monitoring_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateScenarioMonitorRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateScenarioMonitorRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateScenarioMonitorRequest) GetScenario() string {
	if x != nil && x.Scenario != nil {
		return *x.Scenario
	}
	return ""
}

func (x *UpdateScenarioMonitorRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

// Response message for updating a scenario monitor
type UpdateScenarioMonitorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateScenarioMonitorResponse) Reset() {
	*x = UpdateScenarioMonitorResponse{}
	mi := &file_core_v1_scenario_monitoring_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateScenarioMonitorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateScenarioMonitorResponse) ProtoMessage() {}

func (x *UpdateScenarioMonitorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_scenario_monitoring_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateScenarioMonitorResponse.ProtoReflect.Descriptor instead.
func (*UpdateScenarioMonitorResponse) Descriptor() ([]byte, []int) {
	return file_core_v1_scenario_monitoring_proto_rawDescGZIP(), []int{10}
}

type UpdateScenarioMonitorV2Request struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ScenarioMonitor *ScenarioMonitor       `protobuf:"bytes,1,opt,name=scenario_monitor,json=scenarioMonitor,proto3" json:"scenario_monitor,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateScenarioMonitorV2Request) Reset() {
	*x = UpdateScenarioMonitorV2Request{}
	mi := &file_core_v1_scenario_monitoring_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateScenarioMonitorV2Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateScenarioMonitorV2Request) ProtoMessage() {}

func (x *UpdateScenarioMonitorV2Request) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_scenario_monitoring_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateScenarioMonitorV2Request.ProtoReflect.Descriptor instead.
func (*UpdateScenarioMonitorV2Request) Descriptor() ([]byte, []int) {
	return file_core_v1_scenario_monitoring_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateScenarioMonitorV2Request) GetScenarioMonitor() *ScenarioMonitor {
	if x != nil {
		return x.ScenarioMonitor
	}
	return nil
}

type UpdateScenarioMonitorV2Response struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ScenarioMonitor *ScenarioMonitor       `protobuf:"bytes,1,opt,name=scenario_monitor,json=scenarioMonitor,proto3" json:"scenario_monitor,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateScenarioMonitorV2Response) Reset() {
	*x = UpdateScenarioMonitorV2Response{}
	mi := &file_core_v1_scenario_monitoring_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateScenarioMonitorV2Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateScenarioMonitorV2Response) ProtoMessage() {}

func (x *UpdateScenarioMonitorV2Response) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_scenario_monitoring_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateScenarioMonitorV2Response.ProtoReflect.Descriptor instead.
func (*UpdateScenarioMonitorV2Response) Descriptor() ([]byte, []int) {
	return file_core_v1_scenario_monitoring_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateScenarioMonitorV2Response) GetScenarioMonitor() *ScenarioMonitor {
	if x != nil {
		return x.ScenarioMonitor
	}
	return nil
}

var File_core_v1_scenario_monitoring_proto protoreflect.FileDescriptor

const file_core_v1_scenario_monitoring_proto_rawDesc = "" +
	"\n" +
	"!core/v1/scenario_monitoring.proto\x12\acore.v1\x1a\x1bbuf/validate/validate.proto\x1a\x14core/v1/filter.proto\x1a\x1bcore/v1/list_metadata.proto\x1a\x13core/v1/types.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x85\x01\n" +
	"\x1cCreateScenarioMonitorRequest\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04name\x12\x1a\n" +
	"\bscenario\x18\x02 \x01(\tR\bscenario\x12,\n" +
	"\x06status\x18\x03 \x01(\tB\x14\xbaH\x11r\x0fR\x06activeR\x05draftR\x06status\"/\n" +
	"\x1dCreateScenarioMonitorResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"7\n" +
	"\x1cDeleteScenarioMonitorRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x02id\"\x1f\n" +
	"\x1dDeleteScenarioMonitorResponse\"4\n" +
	"\x19GetScenarioMonitorRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x02id\"P\n" +
	"\x1aGetScenarioMonitorResponse\x122\n" +
	"\amonitor\x18\x01 \x01(\v2\x18.core.v1.ScenarioMonitorR\amonitor\"m\n" +
	"\x1bListScenarioMonitorsRequest\x12 \n" +
	"\x05limit\x18\x01 \x01(\x05B\n" +
	"\xbaH\a\x1a\x05\x18\xf4\x03 \x00R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\x12\x14\n" +
	"\x05order\x18\x03 \x01(\tR\x05order\"\x90\x01\n" +
	"\x1cListScenarioMonitorsResponse\x124\n" +
	"\bmonitors\x18\x01 \x03(\v2\x18.core.v1.ScenarioMonitorR\bmonitors\x12:\n" +
	"\rlist_metadata\x18\x02 \x01(\v2\x15.core.v1.ListMetadataR\flistMetadata\"\xdf\x01\n" +
	"\x0fScenarioMonitor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bscenario\x18\x03 \x01(\tR\bscenario\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xc5\x01\n" +
	"\x1cUpdateScenarioMonitorRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x1f\n" +
	"\bscenario\x18\x03 \x01(\tH\x01R\bscenario\x88\x01\x01\x121\n" +
	"\x06status\x18\x04 \x01(\tB\x14\xbaH\x11r\x0fR\x06activeR\x05draftH\x02R\x06status\x88\x01\x01B\a\n" +
	"\x05_nameB\v\n" +
	"\t_scenarioB\t\n" +
	"\a_status\"\x1f\n" +
	"\x1dUpdateScenarioMonitorResponse\"m\n" +
	"\x1eUpdateScenarioMonitorV2Request\x12K\n" +
	"\x10scenario_monitor\x18\x01 \x01(\v2\x18.core.v1.ScenarioMonitorB\x06\xbaH\x03\xc8\x01\x01R\x0fscenarioMonitor\"f\n" +
	"\x1fUpdateScenarioMonitorV2Response\x12C\n" +
	"\x10scenario_monitor\x18\x01 \x01(\v2\x18.core.v1.ScenarioMonitorR\x0fscenarioMonitor2\xa7\b\n" +
	"\x19ScenarioMonitoringService\x12\xab\x01\n" +
	"\x15CreateScenarioMonitor\x12%.core.v1.CreateScenarioMonitorRequest\x1a&.core.v1.CreateScenarioMonitorResponse\"C\x82\xd3\xe4\x93\x02=:\x01*\"8/core.v1.ScenarioMonitoringService/CreateScenarioMonitor\x12\xab\x01\n" +
	"\x15DeleteScenarioMonitor\x12%.core.v1.DeleteScenarioMonitorRequest\x1a&.core.v1.DeleteScenarioMonitorResponse\"C\x82\xd3\xe4\x93\x02=:\x01*\"8/core.v1.ScenarioMonitoringService/DeleteScenarioMonitor\x12\x9f\x01\n" +
	"\x12GetScenarioMonitor\x12\".core.v1.GetScenarioMonitorRequest\x1a#.core.v1.GetScenarioMonitorResponse\"@\x82\xd3\xe4\x93\x02::\x01*\"5/core.v1.ScenarioMonitoringService/GetScenarioMonitor\x12\xa7\x01\n" +
	"\x14ListScenarioMonitors\x12$.core.v1.ListScenarioMonitorsRequest\x1a%.core.v1.ListScenarioMonitorsResponse\"B\x82\xd3\xe4\x93\x02<:\x01*\"7/core.v1.ScenarioMonitoringService/ListScenarioMonitors\x12\xab\x01\n" +
	"\x15UpdateScenarioMonitor\x12%.core.v1.UpdateScenarioMonitorRequest\x1a&.core.v1.UpdateScenarioMonitorResponse\"C\x82\xd3\xe4\x93\x02=:\x01*\"8/core.v1.ScenarioMonitoringService/UpdateScenarioMonitor\x12\xb3\x01\n" +
	"\x17UpdateScenarioMonitorV2\x12'.core.v1.UpdateScenarioMonitorV2Request\x1a(.core.v1.UpdateScenarioMonitorV2Response\"E\x82\xd3\xe4\x93\x02?:\x01*\":/core.v1.ScenarioMonitoringService/UpdateScenarioMonitorV2B\x91\x01\n" +
	"\vcom.core.v1B\x17ScenarioMonitoringProtoP\x01Z,github.com/formalco/go-sdk/v3/core/v1;corev1\xa2\x02\x03CXX\xaa\x02\aCore.V1\xca\x02\aCore\\V1\xe2\x02\x13Core\\V1\\GPBMetadata\xea\x02\bCore::V1b\x06proto3"

var (
	file_core_v1_scenario_monitoring_proto_rawDescOnce sync.Once
	file_core_v1_scenario_monitoring_proto_rawDescData []byte
)

func file_core_v1_scenario_monitoring_proto_rawDescGZIP() []byte {
	file_core_v1_scenario_monitoring_proto_rawDescOnce.Do(func() {
		file_core_v1_scenario_monitoring_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_v1_scenario_monitoring_proto_rawDesc), len(file_core_v1_scenario_monitoring_proto_rawDesc)))
	})
	return file_core_v1_scenario_monitoring_proto_rawDescData
}

var file_core_v1_scenario_monitoring_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_core_v1_scenario_monitoring_proto_goTypes = []any{
	(*CreateScenarioMonitorRequest)(nil),    // 0: core.v1.CreateScenarioMonitorRequest
	(*CreateScenarioMonitorResponse)(nil),   // 1: core.v1.CreateScenarioMonitorResponse
	(*DeleteScenarioMonitorRequest)(nil),    // 2: core.v1.DeleteScenarioMonitorRequest
	(*DeleteScenarioMonitorResponse)(nil),   // 3: core.v1.DeleteScenarioMonitorResponse
	(*GetScenarioMonitorRequest)(nil),       // 4: core.v1.GetScenarioMonitorRequest
	(*GetScenarioMonitorResponse)(nil),      // 5: core.v1.GetScenarioMonitorResponse
	(*ListScenarioMonitorsRequest)(nil),     // 6: core.v1.ListScenarioMonitorsRequest
	(*ListScenarioMonitorsResponse)(nil),    // 7: core.v1.ListScenarioMonitorsResponse
	(*ScenarioMonitor)(nil),                 // 8: core.v1.ScenarioMonitor
	(*UpdateScenarioMonitorRequest)(nil),    // 9: core.v1.UpdateScenarioMonitorRequest
	(*UpdateScenarioMonitorResponse)(nil),   // 10: core.v1.UpdateScenarioMonitorResponse
	(*UpdateScenarioMonitorV2Request)(nil),  // 11: core.v1.UpdateScenarioMonitorV2Request
	(*UpdateScenarioMonitorV2Response)(nil), // 12: core.v1.UpdateScenarioMonitorV2Response
	(*ListMetadata)(nil),                    // 13: core.v1.ListMetadata
	(*timestamppb.Timestamp)(nil),           // 14: google.protobuf.Timestamp
}
var file_core_v1_scenario_monitoring_proto_depIdxs = []int32{
	8,  // 0: core.v1.GetScenarioMonitorResponse.monitor:type_name -> core.v1.ScenarioMonitor
	8,  // 1: core.v1.ListScenarioMonitorsResponse.monitors:type_name -> core.v1.ScenarioMonitor
	13, // 2: core.v1.ListScenarioMonitorsResponse.list_metadata:type_name -> core.v1.ListMetadata
	14, // 3: core.v1.ScenarioMonitor.created_at:type_name -> google.protobuf.Timestamp
	14, // 4: core.v1.ScenarioMonitor.updated_at:type_name -> google.protobuf.Timestamp
	8,  // 5: core.v1.UpdateScenarioMonitorV2Request.scenario_monitor:type_name -> core.v1.ScenarioMonitor
	8,  // 6: core.v1.UpdateScenarioMonitorV2Response.scenario_monitor:type_name -> core.v1.ScenarioMonitor
	0,  // 7: core.v1.ScenarioMonitoringService.CreateScenarioMonitor:input_type -> core.v1.CreateScenarioMonitorRequest
	2,  // 8: core.v1.ScenarioMonitoringService.DeleteScenarioMonitor:input_type -> core.v1.DeleteScenarioMonitorRequest
	4,  // 9: core.v1.ScenarioMonitoringService.GetScenarioMonitor:input_type -> core.v1.GetScenarioMonitorRequest
	6,  // 10: core.v1.ScenarioMonitoringService.ListScenarioMonitors:input_type -> core.v1.ListScenarioMonitorsRequest
	9,  // 11: core.v1.ScenarioMonitoringService.UpdateScenarioMonitor:input_type -> core.v1.UpdateScenarioMonitorRequest
	11, // 12: core.v1.ScenarioMonitoringService.UpdateScenarioMonitorV2:input_type -> core.v1.UpdateScenarioMonitorV2Request
	1,  // 13: core.v1.ScenarioMonitoringService.CreateScenarioMonitor:output_type -> core.v1.CreateScenarioMonitorResponse
	3,  // 14: core.v1.ScenarioMonitoringService.DeleteScenarioMonitor:output_type -> core.v1.DeleteScenarioMonitorResponse
	5,  // 15: core.v1.ScenarioMonitoringService.GetScenarioMonitor:output_type -> core.v1.GetScenarioMonitorResponse
	7,  // 16: core.v1.ScenarioMonitoringService.ListScenarioMonitors:output_type -> core.v1.ListScenarioMonitorsResponse
	10, // 17: core.v1.ScenarioMonitoringService.UpdateScenarioMonitor:output_type -> core.v1.UpdateScenarioMonitorResponse
	12, // 18: core.v1.ScenarioMonitoringService.UpdateScenarioMonitorV2:output_type -> core.v1.UpdateScenarioMonitorV2Response
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_core_v1_scenario_monitoring_proto_init() }
func file_core_v1_scenario_monitoring_proto_init() {
	if File_core_v1_scenario_monitoring_proto != nil {
		return
	}
	file_core_v1_filter_proto_init()
	file_core_v1_list_metadata_proto_init()
	file_core_v1_types_proto_init()
	file_core_v1_scenario_monitoring_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_v1_scenario_monitoring_proto_rawDesc), len(file_core_v1_scenario_monitoring_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_v1_scenario_monitoring_proto_goTypes,
		DependencyIndexes: file_core_v1_scenario_monitoring_proto_depIdxs,
		MessageInfos:      file_core_v1_scenario_monitoring_proto_msgTypes,
	}.Build()
	File_core_v1_scenario_monitoring_proto = out.File
	file_core_v1_scenario_monitoring_proto_goTypes = nil
	file_core_v1_scenario_monitoring_proto_depIdxs = nil
}
