name: Publish Go SDK version tag
on:
  push:
    branches:
      - main
    paths:
      - 'sdk/**'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Latest Go SDK version
        id: get-go-sdk-version
        run: |
          echo "version=$(cat VERSION | tr -d '\n')" >> $GITHUB_OUTPUT
          echo "$(cat VERSION | tr -d '\n')"
      - name: Push new version tag
        uses: mathieudutour/github-tag-action@fcfbdceb3093f6d85a3b194740f8c6cec632f4e2 # v6.1
        with:
          github_token: ${{ steps.generate-token.outputs.token }}
          custom_tag: ${{ steps.get-go-sdk-version.outputs.version }}
          tag_prefix: "sdk/v"
