name: Update Go SDK
on:
  pull_request:
  # workflow_dispatch:
  #   inputs:
  #     buf_version:
  #       description: 'version'
  #       required: true

jobs:
  update-buf-dependency:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'sdk/go.mod'
      - name: Update buf
        run: |
            go get -u buf.build/gen/go/formal/admin/bufbuild/connect-go
            go run main.go
            mv sdk.go sdk/sdk.go
            cd sdk
            go get -u buf.build/gen/go/formal/admin/bufbuild/connect-go
            go get -u buf.build/gen/go/formal/admin/protocolbuffers/go
      - name: Bump Up Version
        run: |
          ./bump_version.sh
      - uses: tibdex/github-app-token@v2
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      # - name: Create Pull Request
      #   uses: peter-evans/create-pull-request@v5
      #   with:
      #     base: master
      #     token: ${{ steps.generate-token.outputs.token }}
      #     title: "Bump Up Go SDK"
      #     body: "Bump up Go SDK version. New tag will be created automatically after merge." 
